### ISSUE TITLE
List of potential changes for the Draft 3.0 IMPORTANT

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#101]
1.	Add to the Bill of Right’s preamble that it applies also regardless of sexual orientation.
2.	Make the Justices of the Supreme Court who are to replace the ones removed in a referendum directly elected.
3.	Oblige the Cabinet to consider a bill proposal put forward by 5 Assembly Representatives (no obligation to actually submit such a bill) 
4.	Remove the word ‘indenture’ from II.4 because as someone pointed out there were forms of voluntary indenture and the involuntary ones are already covered by the article.
5.	Add a possibility to issue a warrant where there is a risk the accused will flee or interfere with the investigation (not only pose a threat to others) in III.4.
6.	Add a ban on being a judge and an Assembly Representative at the same time.
7.	Qualify the term for the Chief Public Prosecutor (see #94)
8.	Add a ban on requirement to identify oneself (see #64 ).
9.	 Add a ‘persons of age’ qualification to II.3 (ban on victimless crimes).
10.	Clarify that agents of the Public Administration can be required to be adequately educated and qualified (in II.12).
11.	Clarify that ban on regulation of marriage does not preclude the Assembly from regulating inheritance rules where there is no will.
12.	Remove word ‘associate’ from II.6 because it might preclude the court from issuing injunction for stalkers etc. plus the word ‘transact’ is enough.
13.	Clarify that the right to issue anything as commodity does not apply to ‘things’ which are illegal (e.g.: add "unless either party of transaction is legally prohibited to possess such item or commodity" to II.10).
14.	Add protection ‘of others’ to the right of self-defence and defence (in addition to the right to defend ‘the close ones’ in II.11).
15.   Consider whether 1 year limitation for prosecution is appropriate (see #99 )
16.   Lift the threshold for constitutional amendment (and taxation if remains) to 3/4 in a (mandatory) referendum.
17.	Restate the right to bear arms (as partially proposed by the gun expert, criminologist and a person who will be responsible for the future gun laws): 

"No person of age shall be deprived of the right to own, manufacture, sell, transport, and bear any small arms unless decided otherwise by a decision of the court where law allows it as punishment for crime, or on medical grounds; licensing shall not be used to infringe upon this right, nor restrictions as to the purchase and/or use of ammunition and/or the firearms accessories.” 

We protect ammunition and firearms accessories and preclude the right to possess weapons of mass destruction (“In international arms control, small arms include revolvers and self-loading pistols, rifles and carbines, assault rifles, submachine guns and light machine guns.”)

Please comment here :)

**Comment by liberlandcitizen** [comment]
"§III.14. In criminal proceedings, the defendant shall have the right to the following:
§III.14(5) to the assistance of legal counsel free of charge where appropriate;
§III.14(8) to be provided without expense with the services of an interpreter if he or she does not speak the language of proceedings."

Why have socialized legal services?  Much like medical and retirement services, I believe the market, without regulation, will keep prices for legal services low.  I believe charity will take care of the rest.

**Comment by Jean-LouisMesic** [comment]
@KacperZajc 

Yea to 1., 2., 3., 4., 5., 6., 8., 10., 13., 16., 17.

7. Needs to be determined, yes.

9. This deserves discussion, but I can see it getting rather lengthy. I'd open a separate issue for it. At what age does one suddenly become responsible and able to consent for their own reactions? What crimes could become feasible after opening up this section to youth? Should youth have a separate set of rights to protect them further, if we do open up this section?

11. Must be determined in a civil court in the presence of all potential heirs, both biological, adoptive, and marital. In the case of the estate including the ownership of a business, executives and other officers of the firm must also be considered.

12. Why not just write "§II.6. No law shall mandate nor forbid any natural and/or legal person to associate and/or transact with any other CONSENTING natural and/or legal person." This protects all associations that are not facilitated by any transaction of commodity, good, or service, and also accounts for your special cases.

14. I hesitate to include this, simply because one could try to justify preemptive attacks as defending others. "I believed he was going to kill my neighbors." Even though the accused was in no position to immediately do so.

15. I still think we're both interpreting this differently. I'm applying it to pre-apprehension, and you are applying it to post-detention/awaiting trial. Needs more clarity.

**Comment by liberlandcitizen** [comment]
(2) If judges become politicians (complete with elections and opponents and campaigns and advertisements and debates) then their decisions will become political.  I think it's great that the public can take them out, but how about putting them into their judgeship a consistent way?  Otherwise the public may be motivated to take them out (just so they can put their own in).  

(11) This will likely result in the government taking a marriage stance.  The assembly doesn't have to involve itself in such matters.  

(16)  Please yes to this (though of course I hope there will be no taxes or the right not pay is guaranteed)

**Comment by Jean-LouisMesic** [comment]
@liberlandcitizen (2) It would only be in the case of a judge being impeached and removed through referendum. Otherwise, we'd be down a judge until another appointment can be made, and if the last Court was unjust, then the next appointee will also likely be unjust.

I can see your point that electing Justices to replace removed Justices could pose a problem, where impeachment referendums are abused to make the Supreme Court a political game.

**Comment by Jean-LouisMesic** [comment]
@liberlandcitizen (11) Could you elaborate on how this could be a marriage stance?

**Comment by ke7ofi** [comment]
> Add to the Bill of Right’s preamble that it applies also regardless of sexual orientation.

Why not just say that it applies to everyone? Is there anyone it *shouldn’t* apply to?

**Comment by KacperZajc** [comment]
@Jean-LouisMesic 

9) I think it is natural that the non-aggression principles does not fully apply to ,minors? 
11) We really need inheritance rules where there is no will, how otherwise would you regulate that? We allow the Assembly to make rules which will be applied by the Civil Court. This will not affect the ban on regulating marriage itself.
12) I really like your wording. 
14) What does it have to do with the change I proposed?
15) Yeah this needs further discussion.

@ke7ofi:

Maybe you are right here.

**Comment by ke7ofi** [comment]
@KacperZajc Small arms will change over time (Miniaturised electrolasers? Basically anything could pop up if it’s small enough). You may want to find a broader definition.

**Comment by mayapurmedia** [comment]
17) Regarding guns. There should be centralized database where seller of the gun can check if buyer is allowed by law to have gun (means buyer is not forbidden to have gun because of crime or medical situation).

**Comment by KacperZajc** [comment]
@mayapurmedia I agree but this is not for the Constitution to regulate.

**Comment by Jean-LouisMesic** [comment]
@KacperZajc (9) Of course, but does this mean that the government is allowed to ban table sugar for all minors? There need to be some provisions. There should be ample evidence that taking some form of intervening action will alleviate some problem in youth health or well-being. This deserves more discussion.

@KacperZajc (11) I was referencing what I believe should be included in whatever we determine to be inheritance provisions included in the Constitution, not that we shouldn't make a stance on it.

@KacperZajc  (14) I was trying to make the point that said "others" must be in reasonably immediate and apparent danger to justify defensive action. Undoubtedly, a jury would determine this, but I think this is important to stipulate.

(17) Perhaps to cover @ke7ofi 's concerns, and to avoid the whole "They meant muzzle-loading muskets and rifles for hunting purposes" arguments in 300 years like we are currently facing in the U.S., perhaps we should edit our bear arms section to be worded as such: 

"No person of age shall be deprived of the right to own, manufacture, sell, transport, and bear any small arms, BE THEY NOW HISTORIC, CONTEMPORARY, AND/OR EXPERIMENTAL, REGARDLESS OF CONDITION, MEANS OF ARMAMENT, OR PRIMARY LEGAL UTILITY, unless decided otherwise by a decision of the court where law allows it as punishment for crime, or on medical grounds; licensing shall not be used to infringe upon this right, nor restrictions as to the purchase and/or use of ammunition and/or the firearms accessories.”

Next on the docket, what is the stance on Light Weapons?

**Comment by KacperZajc** [comment]
@Jean-LouisMesic 
(9) I dont think we are able to stipulate that in the Constitution unfortunately.
(11) same here
(14) we will add 'under direct threat'
(17) I really like BE THEY NOW HISTORIC, CONTEMPORARY, AND/OR EXPERIMENTAL, REGARDLESS OF CONDITION, MEANS OF ARMAMENT, OR PRIMARY LEGAL UTILITY

**Comment by Jean-LouisMesic** [comment]
@KacperZajc Sounds fine by me.

**Comment by FellowTraveler** [comment]
We should also specifically eliminate gun registration. The current language says that "licensing" cannot be used to infringe. We should change that to "licensing of gun owners and registration of guns" cannot be used to infringe.

The reason is because gun registration is a common tactic of authoritarian regimes. For example, the Nazis enforced gun registration, and then they later used the records to confiscate the guns.

**Comment by Jean-LouisMesic** [comment]
Good point. Perhaps place this in a new pull request?

**Comment by terrorist96** [comment]
I did a quick pull.
