### ISSUE TITLE
My list of Ideal Government characteristics

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#107]
The following is a list I have put together over some time. Some of the points may already be included in the draft constitution, some may not be applicable. I'd like to see as many of them incorporated in some way.
I have attempted to strike anything that's already been incorporated or isn't relevant.

* ~~Term limits for all elected government servants~~
* ~~All laws should apply to everyone~~
* ~~Bills must be publicly available online and ~~read before being voted on (read out loud during a quorum, prior to voting)~~
* No Bills to Exceed 10 pages (or 10 minutes or X words long)
* ~~All bills are to be accompanied by the Constitutional Article Authorizing said Bill.~~
* ~~No content in the Bill that does not pertain to the Title of the Bill.~~
* ~~All bills requiring expenditures must disclose ~~TOTAL Costs~~, How the Bill will be funded, Who the Beneficiaries are~~, and a Sunset Date.
* ~~Law enforcement should be required to maintain video footage of all interactions (dash cams, body cams) for accountability. Absent footage will be grounds to dismiss charges in court~~
* ~~Judges should be required to fully inform juries of their power to nullify the law if it is against their conscience~~ and it should be illegal for prosecutors to ask jurors if they would have a problem convicting someone (see New Hampshire law)
* Illegal for government to lie to the people
* **Recall process for elected representatives (Currently only limited to Judicial branch; should be expanded to include executive/legislative branch members too)**
* All checkpoints are illegal except at the border
* ~~Illegal for government and private businesses to exchange information without warrant/subpoena. Any private online information NOT pursuant to an active, legitimate investigation shall not be disseminated to any party absent a legitimate warrant.~~
* Illegal to be ticketed by a camera
* Separate citizen community oversight committees to investigate complaints about police and general government accountability. They should have broad authority to act on their findings
* Prison shall be publicly owned and no perverse incentives for prosecutions
* **Illegal to make laws for specific entities to give them special protections**
* Legislatively neutral sessions, where in order to pass a new law, an old/unenforced/antiquated law must be repealed first
* ~~Income tax = illegal~~
* ~~Any newly passed law shall not go into effect until it has been reviewed by the judicial branch to deem its constitutionality~~
* ~~No victimless crimes~~
* Any judge appointed by a president shall recuse themselves from any case that is regarding a law that the aforementioned president enacted
* Any establishment that forbids the carrying of arms in the premises shall be liable for the safety of any and all occupants. Gun free zones are only permissible if all entrances to that zone are protected by metal detectors and armed guards.
* Prohibit public or private employers from establishing policies that prohibit law-abiding citizens from storing lawfully-owned firearms and/or ammunition out of sight within their locked motor vehicles
* If being prosecuted, the Public Administration can't spend more money prosecuting you than you are in capable of spending in order to defend yourself
* ~~If a judge is overturned more than 50% of the time by higher judges, they should be disbarred~~ (referendum)
* Any time a citizen has to go out of his way to obtain money that rightfully belonged to them, then his time needs to be compensated and any reasonable interest too
* ~~A prison sentence shall only be imposed on perpetrators of violence and anyone else that poses a threat to society~~
* ~~No civil asset forfeiture without due process~~

The rest are more specific to the US, you can ignore them:
* Congress shall have standing to sue other parts of the government if law breaking is going on and no prosecutor is appointed by the president cuz of politics
* No qualified immunity for anyone
* No police quotas
* No enforcement of law solely for the purpose of raising revenue
* No speed limits. Only "recommended" speed limit signs may be posted
* No unmarked police vehicles except for specific undercover investigations (similar to Washington state law)
* No money allowed in politics. Government funded debates only. No party identification, voters should be informed on who they are voting for
* Federal Government can't "bribe" states to implement programs
* Only taxes to be paid to governments are those which you support. If you don't want your tax money to go towards DEA, then you don't send money to them. This way, only programs/departments that the public supports will be funded
* Second amendment applies to anything your local police department is allowed to have. If they have tanks and surface to air missiles, then you as a citizen should be afforded that right as well. Don't agree? Then demilitarize the police.
* 2/3 of the legislature shall be required to ratify war (or any other hostilities)

**Comment by liberlandcitizen** [comment]
Yes to jury nullification.  It is a great check and balance to give to the population.  But is this really allowed for/encouraged in the current draft of the constitution?

**Comment by terrorist96** [comment]
§VI.15(4) The Jury shall retain the unequivocal right to acquit, and shall be informed of this right;

Also, it should be added that the jury may not be punished/penalized for their verdict.

**Comment by Jean-LouisMesic** [comment]
Alot of this only applies to the US Constitution, which is fundamentally different from what we are doing.

Re-read the Constitution and go back an revise your list, so we can better understand what you want to discuss.

**Comment by terrorist96** [comment]
I made some more edits to my OP,  hope it's more clear now. 

Another idea I had:

*No one should be kept in jail prior to trial for the sole purpose that they cannot economically afford to pay bail; unless the accused is a flight risk or a danger to the general public; release upon one's own recognizance shall be the preferred option; bounty hunters shall have the ability to attempt recovery of any fugitives

**Comment by Jean-LouisMesic** [comment]
*Term limits for all elected government servants.
Done.

*All laws should apply to everyone
Yea. Needs to be included.

*Bills must be publicly available online and read before being voted on (read out loud during a quorum, prior to voting)
First part isn't exactly a matter for any constitution. Perhaps "All Bills proposed by the Cabinet shall be made public in print prior to the Assembly's voting session" or something along those lines.

*No Bills to Exceed 10 pages
Not feasible. We'll start getting bills with 1pt font being submitted to the above database, so no one would be able to read them anyway.

*All bills are to be accompanied by the Constitutional Article Authorizing said Bill.
Done.

*No content in the Bill that does not pertain to the Title of the Bill.
Done.

*All bills requiring expenditures must disclose TOTAL Costs, How the Bill will be funded, Who the Beneficiaries are, and a Sunset Date.
Costs, done. How funded, done. Who the beneficiaries are, done. Sunset Clause is still under debate.

*Law enforcement should be required to maintain video footage of all interactions (dash cams, body cams) for accountability. Absent footage will be grounds to dismiss charges in court
Interesting. Deserves talking about.

*Judges should be required to fully inform juries of their power to nullify the law if it is against their conscience and it should be illegal for prosecutors to ask jurors if they would have a problem convicting someone (see New Hampshire law)
This is facing too much debate. Should be a no-brainer.

*Illegal for government to lie to the people
Unenforceable by any document.

*Recall process for elected representatives (Currently only limited to Judicial branch; should be expanded to include executive/legislative branch members too)
Deserves discussion.

*All checkpoints are illegal except at the border
Are they necessary at the border, even? Rather, on our side of the border?

*Illegal for government and private businesses to exchange information without warrant/subpoena. Any private online information NOT pursuant to an active, legitimate investigation shall not be disseminated to any party absent a legitimate warrant.
Fairly certain this has been covered in a recent pull request.

*Illegal to be ticketed by a camera
Not a matter for the Constitution. Beyond the scope of our document.

*Separate citizen community oversight committees to investigate complaints about police and general government accountability. They should have broad authority to act on their findings
This is a function of a free market, and beyond the scope of our document.

*Prison shall be publicly owned and no perverse incentives for prosecutions
Deserves discussion.

*Illegal to make laws for specific entities to give them special protections
Not sure if this is covered yet. Deserves discussion.

*Legislatively neutral sessions, where in order to pass a new law, an old/unenforced/antiquated law must be repealed first
Unfeasible, this would result in imbeciles repealing laws against rape and murder in order to pass laws outlawing toilet paper.

*Income tax = illegal
Done.

*Any newly passed law shall not go into effect until it has been reviewed by the judicial branch to deem its constitutionality
Unfeasible. Better for the people to challenge the law rather than to hear from an echo box.

*No victimless crimes
Done-ish. We're debating how this applies to minors.

*Any judge appointed by a president shall recuse themselves from any case that is regarding a law that the aforementioned president enacted
We have no president. This isn't really relevant to even the way our judges are selected. Re-read the Constitution. The Assembly appoints judges; this would mean all judges would have to recuse themselves from all cases.

*Any establishment that forbids the carrying of arms in the premises shall be liable for the safety of any and all occupants. Gun free zones are only permissible if all entrances to that zone are protected by metal detectors and armed guards.
Gun Free Zones are against the Constitution, I believe. Or should be. Deserves discussion.

*Prohibit public or private employers from establishing policies that prohibit law-abiding citizens from storing lawfully-owned firearms and/or ammunition out of sight within their locked motor vehicles
Done for public. Nothing can be done for private sector until we start enacting legislation.

*If being prosecuted, the Public Administration can't spend more money prosecuting you than you are in capable of spending in order to defend yourself
Unfeasible with the "free attorney" and "free interpreter" clauses.

*If a judge is overturned more than 50% of the time by higher judges, they should be disbarred
Unfeasible. What if the higher judges are the corrupt ones?

*Any time a citizen has to go out of his way to obtain money that rightfully belonged to them, then his time needs to be compensated and any reasonable interest too
How does this apply to government?

*A prison sentence shall only be imposed on perpetrators of violence and anyone else that poses a threat to society
Done.

*No civil asset forfeiture without due process
Done.

*The rest are more specific to the US, you can ignore them:

*Congress shall have standing to sue other parts of the government if law breaking is going on and no prosecutor is appointed by the president cuz of politics
Ignored.

*No qualified immunity for anyone
Fairly certain this is done.

*No police quotas
Beyond the scope of this document.

*No enforcement of law solely for the purpose of raising revenue
Deserves discussion

*No speed limits. Only "recommended" speed limit signs may be posted
Beyond the scope of this document.

*No unmarked police vehicles except for specific undercover investigations (similar to Washington state law)
Deserves discussion.

*No money allowed in politics. Government funded debates only. No party identification, voters should be informed on who they are voting for
Unfeasible with our method of funding the government.

*Federal Government can't "bribe" states to implement programs
We have no tiered government (yet) so this isn't relevant (yet).

*Only taxes to be paid to governments are those which you support. If you don't want your tax money to go towards DEA, then you don't send money to them. This way, only programs/departments that the public supports will be funded
This has been proposed, but I am personally now against it. I'll debate you on it.

*Second amendment applies to anything your local police department is allowed to have. If they have tanks and surface to air missiles, then you as a citizen should be afforded that right as well. Don't agree? Then demilitarize the police.
This is a good point.

*2/3 of the legislature shall be required to ratify war (or any other hostilities)
I'm fairly certain we're simply avoiding war altogether.

**Comment by Jean-LouisMesic** [comment]
"Only taxes to be paid to governments are those which you support. If you don't want your tax money to go towards DEA, then you don't send money to them. This way, only programs/departments that the public supports will be funded"

This allows people with special interests and large amounts of money to fund programs that favor themselves and are a detriment to others, like stimulus packages.

**Comment by KacperZajc** [comment]
see #118

**Comment by terrorist96** [comment]
> *No Bills to Exceed 10 pages
Not feasible. We'll start getting bills with 1pt font being submitted to the above database, so no one would be able to read them anyway.

It can be changed to, no bills to exceed X number of words, or X number of minutes it takes to read outloud.

> *Legislatively neutral sessions, where in order to pass a new law, an old/unenforced/antiquated law must be repealed first
Unfeasible, this would result in imbeciles repealing laws against rape and murder in order to pass laws outlawing toilet paper.

This would be something that would go into effect many years down the road when the government starts getting bloated. No Assembly member would vote to legalize rape/murder. If they did, they'd be recalled and replaced.


> *Any newly passed law shall not go into effect until it has been reviewed by the judicial branch to deem its constitutionality
Unfeasible. Better for the people to challenge the law rather than to hear from an echo box.

This is already the case.

> *If being prosecuted, the Public Administration can't spend more money prosecuting you than you are in capable of spending in order to defend yourself
Unfeasible with the "free attorney" and "free interpreter" clauses.

The free attorney is only applicable to destitute people. The government pays the attorney to represent you. If the government chooses to throw a massive amount of money to try to destroy your life, then they'd be spending double the money because the attorney would have to be paid the same amount in order to defend you equally. The idea being that justice should not be determined by which side has more money, but which side is right. Thus, the government would be wasting its own money twice over.

> *If a judge is overturned more than 50% of the time by higher judges, they should be disbarred
Unfeasible. What if the higher judges are the corrupt ones?

The corrupt ones get recalled, the incompetent ones get disbarred.

> *Any time a citizen has to go out of his way to obtain money that rightfully belonged to them, then his time needs to be compensated and any reasonable interest too
How does this apply to government?

Civil asset forfeiture. The government takes your stuff, you have to pay a lawyer to try to get it back for you.

**Comment by Jean-LouisMesic** [comment]
*Any newly passed law shall not go into effect until it has been reviewed by the judicial branch to deem its constitutionality
Unfeasible. Better for the people to challenge the law rather than to hear from an echo box.
"This is already the case."

Not really. Anything that goes before the court results from a case brought up by a citizen. It doesn't go directly to the court from the assembly. Additionally, having bills go directly from the Assembly to the Court means even blatantly unconstitutional bills could get the "Constitutional" stamp of approval before the public even has a chance to state its case and defend its own rights.

**Comment by terrorist96** [comment]
@Jean-LouisMesic 

> §IV.21. A Bill shall become ‘under consideration’ once it is passed by the Assembly in accordance with the provisions of this Article, and either 90 days have passed and no referendum was called in accordance with §IV.17, or on the day the Bill obtained the assent of the Citizens in referendum under §IV.18 or §IV.19.
§IV.22. A Bill shall become the law of the Free Republic of Liberland, and shall be known as “Act” once it became ‘under consideration’ in accordance with the procedure provided for in §IV.21, and was declared constitutional by the Supreme Court of the Free Republic of Liberland, hereinafter, "the Supreme Court".
§IV.23. The law of the Free Republic of Liberland shall enter into force no sooner than on the 31st day after it is signed by the Chief Justice of the Supreme Court, or if unable, by any other Justice of the Supreme Court which must take place upon the declaration of constitutionality.

> §VI.10. The Supreme Court shall review prima facie constitutionality of every Bill passed by the Assembly and no Bill shall become the law of the Free Republic of Liberland unless the Supreme Court, unanimously, declares the Bill to be constitutional.
§VI.10(1) Nothing in this paragraph precludes the Supreme Court from striking down any provision of any Act passed by the Assembly as unconstitutional at any later criminal or civil proceedings.

**Comment by terrorist96** [comment]
Also, I have an issue with this:

> The law of the Free Republic of Liberland shall enter into force no sooner than on the 31st day after it is signed 

What if there's an emergency and the law needs to take effect immediately following its approval by the Supreme Court?

**Comment by KacperZajc** [comment]
my experience tells me that Bills passed into law in rush make really bad laws (e.g. PATRIOT Act)

**Comment by terrorist96** [comment]
> my experience tells me that Bills passed into law in rush make really bad laws (e.g. PATRIOT Act)

That's true, but it's not to say there aren't legitimate laws that need to take effect ASAP. Maybe laws that are passed unanimously should have the option of taking effect immediately?

**Comment by KacperZajc** [comment]
We dont have army, we dont have laws allowing for state of war, so I dont see a point.
Only war could make a good case for immediate laws, since we will not be engaging in any war, because we are legally not allowed to do so, this is likely to be used only to infringe civil liberties etc.

**Comment by terrorist96** [comment]
I'm sure we could think of some laws (other than war) that would deserve immediate implementation, I just can't think of any right now. Can anyone else?

**Comment by Jean-LouisMesic** [comment]
@terrorist96 I must be once again looking at a different draft than you, because I'm not seeing half of those provisions. I think I'm looking at the old one, this time, though. : P

@KacperZajc @terrorist96 It is imperative that the people have time to adjust their lifestyles and to acquaint themselves with new legislation before they are at risk of being arrested for violating any law that they may or may not be in accordance with. Allowing an entire month for this is preferable.

The only laws I can conceive that would require immediate implementation will be a.) the obvious ones, which we have already enacted under the provisional government, or will enact under this Constitution, so the 31 day rule will not cause a 31-day riot of murder, rape, and thievery, or b.) something so important that an instantaneous Constitutional amendment would do the trick anyway.

**Comment by terrorist96** [comment]
Can you please keep this open? It's a good list of ideas that can be debated. I've updated the OP

**Comment by terrorist96** [comment]
@KacperZajc

**Comment by KacperZajc** [comment]
ok reopening

**Comment by terrorist96** [comment]
What are your thoughts on 
- Recall process for elected representatives (Currently only limited to Judicial branch; should be expanded to include executive/legislative branch members too)

**Comment by KacperZajc** [comment]
#281
