### ISSUE TITLE
Points for further debate

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#111]
1.   Abolish the free of charge service of an interpreter and legal counselling in III.14.
2.   Oblige the Cabinet to consider a bill proposal put forward by 5 Assembly Representatives (no obligation to actually submit such a bill) .
3.   Make the Justices of the Supreme Court who are to replace the ones removed in a referendum directly elected.
4.   Securing freedom of the Internet

**Comment by Jean-LouisMesic** [comment]
Yea to 2., 3.

Absolute Nay to 1. Amend to require an agreement to be reached between advocate and client detailing compensation period and amount.

**Comment by terrorist96** [comment]
1. Nay

My state offers free legal representation (for crimes which the punishment includes the possibility of prison time) to those who can't afford it. However, if you are found guilty, you are required to pay for your representation after the fact. The theory being that an innocent person who can't afford an attorney shouldn't have their liberty stripped from them (by denying them representation, thus tipping the scales of justice against them) because of their economic status.

2. No strong opinion
3. Yea
4. Yea; just say that the cannot regulate the Internet and any future iterations of it

**Comment by Jean-LouisMesic** [comment]
@terrorist96 4. is much more complicated than that, something is already to the tune of what you said. It leaves open a lot of victim crimes. There was a larger pull request with great discussion on there, but unfortunately, I'm unable to find it at the moment.

**Comment by liberlandcitizen** [comment]
Just to recap here my suggestions for these points:

1)  No socialized legal services
2)  Seems fair to add "competition" to bills being offered
3)  No political campaigns for judges.  Turns them into politicians.
4)  100% free and unregulated internet.  Prohibit child rape/molestation/porn eleswhere

**Comment by terrorist96** [comment]
@liberlandcitizen you're against socialized legal services but in favor of socialized (free) Internet?

**Comment by liberlandcitizen** [comment]
@terrorist96 ha no - not free as in "free" of charge/socialized.  Free as in no regulation - no laws pertaining to people sending zeros and ones to each other.  I think the government should keep its hands off.

**Comment by KacperZajc** [comment]
what if we approach the problem this way:

No law shall regulate radio, television, the Internet or any other medium of exchange of information; no rules shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration; nothing in this provision shall apply to the protection of sources rules, childhood pornography and protection of persons under age.

???

**Comment by liberlandcitizen** [comment]
"nothing in this provision shall apply to the protection of sources rules"  

Could you please explain what this means?

"childhood pornography"..."protection of persons under age."   redundant.  

"accessing information without consent of the rightful owner"   I beg of you to drop this.  The beauty of the internet is that you can access the world's information.  Edward Snowden would be in jail in Liberland :(

**Comment by KacperZajc** [comment]
1) this provision ban any rules, the first exception says that we can introduce rules concerning protection of sources (maybe we need different wording)
2) I removed "childhood pornography", "protection of persons under age" includes childhood pornography
3) I want to prevent hacking, this is what I meant

**Comment by liberlandcitizen** [comment]
1)  We should try to use different words, as I'm still unsure what this means.  Sources meaning.....source code?  Journalist sources?  

2)  Perfect

3)  Well if you must have something about hacking...maybe just use the word hacking instead of "accessing information without consent of the rightful owner"  ???

**Comment by KacperZajc** [comment]
hacking is a narrow term; 
we have provisions protecting whistle-blowers

**Comment by KacperZajc** [comment]
see #118
