### ISSUE TITLE
Monopolies 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#114]
Can we all agree that monopolies are bad? How can they be addressed?

**Comment by FellowTraveler** [comment]
Long-lasting monopolies are imposed by the State. (AT&T, water company, etc.)

Short-lasting monopolies are naturally destroyed over time by market forces.

**Comment by terrorist96** [comment]
What if market forces are towards conglomerating businesses, so in the end you only have one company for every product/service and if any new companies appear, they quickly get bought out and merged into the monopoly? From my experience, the tendency is towards centralization.

**Comment by liberlandcitizen** [comment]
Yes we are all in agreement that monopolies are bad.  Probably where we disagree is what causes monopolies.  Many of us believe that with a truly free market, monopolies will not exist.

**Comment by terrorist96** [comment]
How so? From my understanding, the USA was pretty laissez-faire in the early days but monopolies started becoming a problem, which required them to take action to break them up. Maybe I have my history wrong?

**Comment by Jean-LouisMesic** [comment]
Market forces don't drive towards single firm conglomerations.

If there is profit to be had in an industry, undoubtedly, some industrious fellow will exploit those opportunities and compete with established firms. Because of the mechanics of economies vs. diseconomies of scale, obscenely large scale firms like monopolies have to work harder to maintain lower costs than firms that produce at lower scales. Thus, the competition drives prices down, weakens larger firms, and empowers smaller firms.

Corporations pursue legislation to eliminate this competition so they can produce at unnaturally large scales, well beyond the threshold of economies/diseconomies of scale, without having to worry about the little man. Eliminating barriers to entry and other regulations eliminates monopolies. There is no need for further anti-trust legislation beyond what we already have outlined in the Constitution.

**Comment by Jean-LouisMesic** [comment]
USA was by no means laissez faire, even in the early days. There are famous tales of the national guard taking up arms to enforce regulations prohibiting the distilling of whiskey.

**Comment by FellowTraveler** [comment]
The USA has a long history of creating monopolies. AT&T is a great example. From Wikipedia:

_In parts of the United States, AT&T had a legal monopoly on the provision of local telephone service and in long distance until 1984 when local service was vertically divested. The divested local companies continued to be protected in lesser degree from competition in the local exchange market as a public utility._

This legal monopoly goes back to the early 20th century.

Notice that every monopoly corporation or monopoly cartel is heavily regulated.

Whereas in unregulated sectors, companies never have monopolies that last so long. Maybe 10 years, or 20, but not 50 or 100. See IBM for example.

**Comment by terrorist96** [comment]
Is the difference in regulation directly attributable to their tendency towards monopolies? Can we prove that? What other examples of "unregulated" sectors are there to compare to?

**Comment by Jean-LouisMesic** [comment]
Yes. No regulation has ever been posed without a firm expressing interest in it through lobbying.

Regulations benefit only established firms, and harm only potential entrepreneurs.

**Comment by FellowTraveler** [comment]
Regulatory compliance increases costs. This increases the barrier to entry. This necessarily benefits established players at the expense of competition from smaller businesses. See banks, taxis, etc. The most heavily regulated industries are always the ones with the highest prices and the worst service.

Regulated industries are regulated by the largest players on that industry. There is usually a revolving door between the corporate boards and the regulatory bodies that regulate them. See "Regulatory Capture" on Wikipedia:  https://en.wikipedia.org/wiki/Regulatory_capture

Remember, the longest-lasting monopolies are always the ones that are protected by government force. Remove that protection and make them compete on a free market.

**Comment by terrorist96** [comment]
>Regulatory compliance increases costs. This increases the barrier to entry. This necessarily benefits established players at the expense of competition from smaller businesses. See banks, taxis, etc. The most heavily regulated industries are always the ones with the highest prices and the worst service.

What if any regulation that exists cannot increase your cost? I don't disagree that high regulation = high prices/bad service. That's a given. But what about minimal regulation that isn't a burden? Basic shit like don't run a human sweatshop. 

> Remember, the longest-lasting monopolies are always the ones that are protected by government force. Remove that protection and make them compete on a free market.

I agree with this too.

**Comment by Jean-LouisMesic** [comment]
"Minimal regulation"

"Not a burden"

Choose.

Unless you want the regulation to be "Potato farmers will sell potatoes." Because that incurs no additional cost, until said potato farmer attempts to branch.

Regulation ONLY causes more problems. Just let the free market solve its own temporary problems. Tampering leaves the invisible hand tied, or even in some cases entirely severed.

**Comment by terrorist96** [comment]
This is an experiment after all, so ok why not? It'd be interesting to see how it turns out.
