### ISSUE TITLE
No law shall allow any body of any branch of the Public Administration to assign a number to any citizen

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#121]
> §II.18. No law shall allow any body of any branch of the Public Administration to assign a number to any citizen

How will voting be conducted? You need to limit voting to citizens only, and if it's done online, you need to have them registered and validated (ie assigned a number).
I know there's blockchain voting, but I don't think that avoids the assigning number issue either.

**Comment by Jean-LouisMesic** [comment]
We've had long discussions on this, it's still in debate.

@KacperZajc , what happened to that thread, did we just close it without making a decision?

**Comment by KacperZajc** [comment]
@Jean-LouisMesic it's already been added - §II.18
@terrorist96 if you want to vote you will have to register which is a voluntary act (see current wording)

**Comment by Jean-LouisMesic** [comment]
@KacperZajc Right, I was just confused because the referenced wording is literally the text we decided was horrible, and I was scratching my head as to why we were discussing it again in a new thread. I see that you committed the wording we all agreed upon.

@terrorist96 Just to be safe, I always look at the list of commits to see the most current version of the Constitution. Not sure how old the version was you looked at to see this. https://github.com/liberland/constitution/commits/master . I see @KacperZajc changed to the current wording 4 days ago. It's now under the new II.17, now.
