### ISSUE TITLE
New provisions for Draft 3.0

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#132]
1.   All persons shall have the right to exclude from their property any member of the law enforcement where acting without Warrant and any other person acting without an appropriate order of a court of law.

2.   All persons staying within the territory of the Free Republic of Liberland shall be bound to observe the Constitution and other laws passed by the Assembly in accordance with this Constitution.

3.   No special tribunals shall be instituted, nor any courts which are not recognised by this Constitution; no person shall be threatened with or subjected to penalties other than those provided by the law.

4.   One-fourth of all Assembly Representatives shall have a right to propose a resolution dissolving the Assembly; such resolution shall be passed with a majority of two-thirds of all Assembly Representatives; should the Assembly be dissolved, general election shall be held within six weeks.

5.   One-fourth of all Assembly Representatives shall have the right to propose a resolution instituting the Assembly Committee; the resolution shall be passed with a majority of two-thirds of all Assembly Representatives; such Committees shall be composed of five Assembly Representatives and shall monitor the functioning of other bodies of the Public Administration; Committees shall have the right to summon members and agents of the Public Administration to hear testimonies given under oath and prepare final conclusions; such conclusions shall not be binding; nor shall anyone be penalised by any Assembly Committee.

Please comment below.

**Comment by terrorist96** [comment]
> All persons shall have **the** right to exclude from their property any member of the law enforcement where acting without **a** Warrant and any other person acting without an appropriate order of a court of law.

Yea

> All persons staying within the territory of the Free Republic of Liberland shall be bound to observe the Constitution and other laws passed by the Assembly in accordance with this Constitution; **all laws passed by the Assembly shall apply to all persons within the jurisdiction of the Free Republic of Liberland.**

Yea

> No special tribunals shall be instituted, nor any courts which are not recognised by this Constitution; no person shall be threatened with or subjected to penalties other than those provided by the law.

Yea

> One-fifth of all Assembly Representatives shall have a right to propose a resolution dissolving the Assembly; such resolution shall be passed with a majority of two-thirds of all Assembly Representatives; should the Assembly be dissolved, **a** general election shall be held within six weeks.

Yea

> One-fifth of all Assembly Representatives shall have a right to propose a resolution instituting the Assembly Committee; the resolution shall be passed with a majority of two-thirds of all Assembly Representatives; such Committees shall be composed of five Assembly Representatives and shall monitor **the** functioning of other bodies of the Public Administration; Committees shall have the right to summon members and agents of the Public Administration to hear testimonies given under oath and prepare final conclusions; such conclusions shall not be binding~~;~~ nor shall anyone be penalised by any Assembly Committee.

Yea, though I am concerned about the final clause. The Assembly should be able to vote to hold members of the PA in contempt.

**Comment by Jean-LouisMesic** [comment]
* All persons shall have a right to exclude from their property any member of the law enforcement where acting without Warrant and any other person acting without an appropriate order of a court of law.

Yea.

* All persons staying within the territory of the Free Republic of Liberland shall be bound to observe the Constitution and other laws passed by the Assembly in accordance with this Constitution.

I like @terrorist96 's wording, as it applies to people passing-through and not necessarily "staying" in the Free Republic of Liberland. However, it doesn't apply to the Constitution in his wording either. It also makes laws absolute, which is wrong. For instance, you can't have laws that only apply to convicted felons or mental health patients (right to bear arms waiver) if all laws must apply to everyone. Should be "All persons within the jurisdiction of the Free Republic of Liberland shall be bound to observe the Constitution and other laws passed by the Assembly in accordance with this Constitution. No person shall be convicted of any crime that does not apply to his or her circumstances in relationship to the Free Republic of Liberland."

* No special tribunals shall be instituted, nor any courts which are not recognised by this Constitution; no person shall be threatened with or subjected to penalties other than those provided by the law.

Yea, though what about a volunteer military force? Should they not have their own court martial?

* One-fifth of all Assembly Representatives shall have a right to propose a resolution dissolving the Assembly; such resolution shall be passed with a majority of two-thirds of all Assembly Representatives; should the Assembly be dissolved, general election shall be held within six weeks.

Interesting. Though this could be used to hold the nation hostage, should a 1/5th nationalist minority refuse to allow the Assembly to function unless the rest of the country elects their way. Naturally, 1/5 nationalists would be re-elected every general election until enough people give in that they secure absolute control of the Assembly. I vote nay. The threshold should either be higher, or Assembly dissolution should be handed over to the people.

* One-fifth of all Assembly Representatives shall have a right to propose a resolution instituting the Assembly Committee; the resolution shall be passed with a majority of two-thirds of all Assembly Representatives; such Committees shall be composed of five Assembly Representatives and shall monitor functioning of other bodies of the Public Administration; Committees shall have the right to summon members and agents of the Public Administration to hear testimonies given under oath and prepare final conclusions; such conclusions shall not be binding; nor shall anyone be PENALIZED by any Assembly Committee.

Purpose/reasoning? This would also count as a special tribunal in direct conflict with (3), since it's not technically a court.

**Comment by terrorist96** [comment]
My intention is to make it unconstitutional for the Assembly to pass a law that applies to everyone in Liberland except for themselves (think Obamacare). 

> Interesting. Though this could be used to hold the nation hostage, should a 1/5th nationalist minority refuse to allow the Assembly to function unless the rest of the country elects their way. Naturally, 1/5 nationalists would be re-elected every general election until enough people give in that they secure absolute control of the Assembly. I vote nay. The threshold should either be higher, or Assembly dissolution should be handed over to the people.

It still needs 2/3 majority to pass.

**Comment by Jean-LouisMesic** [comment]
I thought we had that covered elsewhere, but just in case, a provision must be made.

I propose "No bill passed by the Assembly shall exclude any member of the Assembly from his or her rights as a legal person, nor shall any bill passed by the Assembly preclude nor exclude any current, future, and/or former member of the Assembly from the observance of the law and/or Constitution of the Free Republic of Liberland." be added.

**Comment by terrorist96** [comment]
I like that. Here would be my suggested edits:

> No law shall exclude any member of the Public Administration from his or her rights as a legal person, nor shall any law preclude or exclude any current, future, or former member of the Public Administration from the observance the Constitution of the Free Republic of Liberland and the laws thereof.

**Comment by Jean-LouisMesic** [comment]
I've become concerned that with Public Administration, Public Authority, and Court of Law floating around everywhere in the Constitution, it's ambiguous as to what parts of the government are in each part specifically. Does one of these terms concern all of the government, or are they all specific pieces?

**Comment by Jean-LouisMesic** [comment]
Also, @terrorist96 , if "Public Administration" is the entirety of government, then I approve of the edits.

**Comment by terrorist96** [comment]
I think public administration includes all three branches.

**Comment by KacperZajc** [comment]
Public Administration includes all 4 branches.

What you are proposing is already covered:

§I.5. No Assembly Representative shall be excluded from the operation of any law passed by the Assembly.

Dissolution still needs 2/3 to pass, no one will be hold hostage by a small majority :)

Committees are supposed to control members of other branches of government (e.g. Clinton or Nixon testifying) but they still would never punish anyone, just gather evidence that might trigger normal prosecution later. If someone lies under oath it would a court that punishes that person, not the Committee.

And it is penaliSed not penaliZed because we use British English here ^^

If we have voluntary military forces I see no reason why wouldnt they be subject to regular courts.

**Comment by terrorist96** [comment]
I feel like this version:

> No law shall exclude any member of the Public Administration from his or her rights as a legal person, nor shall any law preclude or exclude any current, future, or former member of the Public Administration from the observance the Constitution of the Free Republic of Liberland and the laws thereof.

..is stronger than the text of I.5 because that language only says laws are generally applicable to the Assembly too. However, my version disallows any law from doing such thing to begin with and includes the entire PA as opposed to the Assembly.

**Comment by terrorist96** [comment]
> but they still would never punish anyone, just gather evidence that might trigger normal prosecution later. If someone lies under oath it would a court that punishes that person, not the Committee.

What if they aren't prosecuted for political reasons?

**Comment by KacperZajc** [comment]
we could go with "Public Administration" instead of "Assembly" but I dont see why we should make it sound more complicated;
then the Chief Public Prosecutor would probably be impeached in a referendum, we already thought of that :)

**Comment by terrorist96** [comment]
I'd be fine with just replacing it with PA

**Comment by KacperZajc** [comment]
ok

**Comment by Jean-LouisMesic** [comment]
@KacperZajc The current wording excludes the observance of the Constitution. My proposed amendment also protects public servants, making it a more fair trade-off that is more likely to survive once we flip the Government switch on.

**Comment by Jean-LouisMesic** [comment]
@terrorist96 I agree, evidence could be gathered and ignored for political reasons.

Impeachment or dissolution of the Assembly would be warranted in that situation.

**Comment by KacperZajc** [comment]
@Jean-LouisMesic we changed the wording to any member or agent of the PA, does that satisfy you?

**Comment by Jean-LouisMesic** [comment]
Sounds good to me. Apologies for the delayed response.
