### ISSUE TITLE
Fruit of a poisonous tree

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#177]
Should we add a section stating that "any evidence gathered illegally is not admissible in a court of law and shall be grounds for dismissal of any charges thereof"?
Or this this already assumed?

**Comment by KacperZajc** [comment]
I thought of that.
At the moment it is not assumed.
It is radical but I am open to discussion :)

**Comment by yopdog** [comment]
I don't see why it shouldn't be admissible in court. If evidence is at first collected illegally but then proves a person guilty, it will also prove that the evidence was not collected illegally after all, since the guilty person did not have the right to keep that information private in the first place.

**Comment by terrorist96** [comment]
If illegally obtained evidence is allowed in court then it renders ALL the protections of the Constitution null and void. Why follow the Constitution when you're trying to catch bad guys? Because sometimes those people might actually be good and violating their rights is unacceptable. 
This is standard case law in the US. If any evidence has been found to have been obtained illegally/unconstitutionally, the defendant's lawyer can request a motion for suppression of the evidence, which the judge will more than likely grant (unless it was something that wasn't clearly established as being an illegal method). 

I strongly urge this to be added to the Constitution. Not to protect criminals, but to keep the police in check and for them to do their jobs LEGALLY, not by whatever means necessary to catch criminals. This in turn protects the innocent too from having their rights violated.

**Comment by KacperZajc** [comment]
I fully share your concerns, however, there might be situations in which people in power use petty violations of law to escape justice. Here is what I think:

No law shall allow for any evidence, which was obtained illegally, to be admitted in the Criminal Court unless the violation of law was merely incidental to the manner in which said evidence was obtained; in any event any person responsible for the breach of law shall be prosecuted.

**Comment by terrorist96** [comment]
Can you give an example of where illegally obtained evidence would be admissible?

**Comment by KacperZajc** [comment]
I cant think of anything right now but the point is that we guarantee that no petty breach of law is a grounds for dismissal (which could be use by people in power to protect themselves). It would be ascertained by a judge but we create a form of presumption of inadmissibility where obtained illegally.

**Comment by terrorist96** [comment]
Well we shouldn't have any petty laws. =) 
But I like that you thought about this. Corrupt politicians could get off free if the cops screwed up and didn't follow the Constitution when building their case against them.

**Comment by terrorist96** [comment]
Think of this: if the government illegally and unconstitutionally tapped someone's Internet connection and incidentally found out that this imaginary person was going on child porn websites. If the government is then able to arrest him and present that illegitimate evidence in a courtroom, then it allows for the government to casually and surreptitiously monitor any and all people's Internet traffic and emails, looking for child pornographers/pedophiles/terrorists/etc. Is it worth giving up your right to privacy? 

Side note, I would add "illegally and unconstitutionally" to the official wording of the provision.

**Comment by terrorist96** [comment]
"No law shall allow for any illegally and unconstitutionally obtained evidence to be admitted in the Criminal Court."

**Comment by yopdog** [comment]
The problem I see with the exclusionary rule is that it protects us from the truth. The rule can be seen as basically saying that if a law was broken then evidence has to be destroyed.
The law won't just protect corrupt politicians due to the way evidence was collected, but could also protect killers, rapists, child molesters etc. The question we should be asking is whether guilty people have the right to privacy. If they don't, then evidence collected against them, even if without a warrant should not be considered illegal. 

I understand the concern that this could lead to police to breaking the law, but I believe there are much better ways to prevent this then hiding the truth. One way, of course, is to not have hundreds of victimless crimes that could incentivize police to spy on every second of people's lives. The second way would be to hold police accountable for any illegal search that does not turn up with criminalizing evidence. If people are allowed to sue police for illegal searches that would incentivize them to be very careful if they ever want to conduct a search without a warrant.

I suggest the exclusionary rule should be outlawed in the constitution or in the very least not mentioned in it due to it being controversial.
I also suggest reading this article since it provides the libertarian defense against the exclusionary rule: https://www.lewrockwell.com/2003/11/stephan-kinsella/in-defense-of-evidence/

**Comment by terrorist96** [comment]
Who is to claim they're guilty prior to their trial concluding? Everyone is innocent until proven otherwise. You can't claim they're guilty first then decide to violate their privacy, then arrest them, then try to prove they're guilty. You're putting the cart before the horse, so to say. You can only have probable cause that a crime has been committed, go to a judge, present the evidence, get a warrant.. NOT act unilaterally and illegally conduct the search or wiretapping, hoping that you will find evidence. "It is better that ten guilty persons escape than that one innocent suffer" - William Blackstone 

Yes, cops being sued for illegally obtained evidence is a good deterrent, but the best deterrent, IMHO, is having their case thrown out because they did their job wrong, thus disallowing an inherently unfair trial for the defendant. What if they really wanna catch this one person and are willing to martyr one of their own in order to obtain the evidence? What'd be the point of suing the cop from a prison cell? You've already inherently lost. Anything you win from the lawsuit will be purely symbolic. 

I appreciate the intent on uncovering the truth, but we have laws and constitutional provisions in place for a reason. I weigh the right to privacy and to be left alone as higher than the truth. Want the truth? Obtain it legally or lose it forever. Best deterrent of having innocent people's rights violated. 

I think it's absurd that we allow for lethal self defense against a cop acting illegally, but would entertain the notion that just because one chose not to kill the cop who was violating his rights, to have any evidence that said cop obtained allowed in a trial against him. When I could have legally killed the cop to prevent his illegal trespasses (ie obtaining the evidence illegally), but still have that evidence admissible just because I didn't kill him to stop him, baffles me. 

The logic of guilty people don't have a right to privacy is the same logic used to "spy on terrorists". Well, who deems them terrorists? Just because the government says so? Calling them a terrorist is akin to passing judgement. You can't pass judgement prior to a trial. Only then can they be adjudicated as a terrorist.

**Comment by yopdog** [comment]
My point is that if a person is in truth guilty of a crime, then he has no right to keep that a secret. Therefore, if a police officer conducts a search on that person, even if he has no warrant, he is not actually violating the rights of anyone. The guilty individual doesn't have the right of self-defence since he is guilty and he has no right to keep that a secret. 

Having it be this way does not mean that the guilty person is not assumed innocent until proven otherwise. Both the person and the police officer will appear in court, and both of them will be assumed innocent.

You know what I think is absurd? having a law that destroyers evidence and protects criminals in order to incentivize police to obey the Constitution. Can we really not think of another way to achieve the same goal?

Furthermore, the exclusionary rule creates a victimless crime. If I search a someone's home and find a dead body there, can it seriously be considered that I have committed a crime because I had no search warrant? Could you explain to me who is supposed to be considered the victim in this case? Why should I be punished for revealing information that the owner of the home had no right to keep in the first place?

Addressing your point that police will continuously "martyr" their own in order to obtain evidence, I don't believe that will work. If police continuously violate people's rights eventually the head of the police force would be sued as well, and the police force will need to be rebuilt due to its corruption. No institution in Liberland will be able to get away with continuously breaking the law and not be dismantled. The police force will have every incentive to not use a policy of conducting searches without a warrant.

**Comment by terrorist96** [comment]
> My point is that if a person is in truth guilty of a crime, then he has no right to keep that a secret. 

So you are compelled to incriminate yourself; same logic, correct? This would do away with:

> §III.16(7) not to be compelled to be a witness against himself or herself...

;
> Therefore, if a police officer conducts a search on that person, even if he has no warrant, he is not actually violating the rights of anyone.

But we don't know if he's guilty or not yet, because there hasn't been a trial. The government isn't omniscient; it doesn't know whether it's ok to violate this one person's rights because some cop believes him to be guilty prior to any judicial proceedings.

Since we also have this: 

> §III.16(6) to be presumed innocent until proven guilty;

;
> The guilty individual doesn't have the right of self-defence since he is guilty

@KacperZajc please verify if this is true. My reading of the Constitution tells me that this protects 'suspects' of a crime (who haven't been proven guilty yet):

> §II.10. No law shall abridge the right of self-defence and/or defence of one's property... against initiators of aggression, including the agents of the Public Administration where acting unlawfully and/or in error.

;
> You know what I think is absurd? having a law that destroyers evidence and protects criminals in order to incentivize police to obey the Constitution. Can we really not think of another way to achieve the same goal?

A cop's only job is to get convictions in a court of law. The more criminals they put away, the higher they will rank. It's their bread and butter, so to say. You hit them where it hurts most. No one wants criminals locked up more than the police do. Thus, they have the highest of incentives to follow the law and constitution when pursuing a suspected criminal.
I'm not against suing cops when they DO violate your rights; I'm in favor of both suing and suppression of evidence.

> Furthermore, the exclusionary rule creates a victimless crime. If I search a someone's home and find a dead body there, can it seriously be considered that I have committed a crime because I had no search warrant?

Yes. Because you violated that person's rights. The victim is the owner of the home. Only adjudicated criminals don't have a right to privacy (and that's only during their sentence). At the time of the search, you invaded an innocent person's house, (cuz innocent until **proven** guilty). What if that dead body was there without his knowledge? Regardless of how heinous the evidence of a crime you find, it's still not proof that the person is guilty because, again, no trial has been conducted yet. 

> Why should I be punished for revealing information that the owner of the home had no right to keep secret in the first place?

This is assuming that you're an Agent of LE. If you're a civilian who had the owner's permission to be in his home, and incidentally you find a dead body, you can report that to the police. The cops go to a judge and say we have evidence that there's a dead body in this home. They get a warrant. They find the dead body. They arrest the owner of the home. Once they then prove their case, the homeowner is then, and only then, a convicted criminal. Their conviction isn't retroactive. That's absurd.

> The police force will have every incentive to not use a policy of conducting searches without a warrant.

I would like to turn your attention to something called "parallel construction". I don't know if you already know about it, but it's a process that the government uses to obtain evidence of a crime illegally. It then feeds that info to local LE and they zero in on the person and arrest him, but never reveal how they actually came across the evidence that lead to their arrest; they construct a falsified version in where they don't do anything illegal.

**Comment by KacperZajc** [comment]
I think my wording is a compromise between you two -
It excludes petty breaches of law and also doesn't stipulate that the charges must be dismissed - only the piece of evidence in question is inadmissible.

We can go with that now but definitely need some expert advice on that.

**Comment by terrorist96** [comment]
As a compromise, I'm ok with this for now (added unconstitutionally and removed unnecessary commas and added one in the second clause ):

> No law shall allow for any evidence which was obtained illegally **or unconstitutionally** to be admitted in the Criminal Court unless the violation of law was merely incidental to the manner in which said evidence was obtained; in any event**,** any person responsible for the breach of law or **Constitution** shall be prosecuted.

**Comment by KacperZajc** [comment]
I appreciate your linguistic skills :)

**Comment by terrorist96** [comment]
Glad to help. English is your second language, no? First is Czech? You do pretty well

**Comment by yopdog** [comment]
@terrorist96 Do you believe a guilty person has the right to privacy? In other words, if a person actually killed someone in his house and two policemen outside his door want to come in, and they have no warrant, do you believe the person has a moral right to refuse to let them in?

**Comment by KacperZajc** [comment]
@yopdog then they call a judge and get a warrant over the phone in 90s and they can come in. It's very simple :)

**Comment by terrorist96** [comment]
Yes, because even though they may be guilty in reality, their guilt hasn't been established yet, which is why we presume everyone to be innocent until proven otherwise. If we knew who was guilty and who isn't, then there'd be enough need for trials.

**Comment by terrorist96** [comment]
Let's not forget that in countries like America, the average person commits 3 felonies every day. Everyone is guilty of something to some degree.

**Comment by yopdog** [comment]
Ok, so you believe a guilty person has the right to hide his crimes from the public? Don't you think that if a person committed a crime he has an obligation to come clean on it?

I understand the person hasn't been proven guilty yet, but that shouldn't change his rights and obligations given his actions.

New evidence should be able to retroactively justify acts in the past  that may have at first appeared to have had no justification.

The exclusionary rule can even be seen as assuming guilt before proving it. By not allowing the police to present the evidence in court, the court assumes they are guilty while at same time not allowing the police to defend themselves with the only evidence they have, which proves retroactively, that the search was justified. 

This is, of course, true only if you agree with my first paragraph that a guilty person has an obligation to come clean on his crimes.

I'm just worried the exclusionary rule could prevent guilty and dangers  people from facing justice just because the police screwed up. Or in the words of Judge Benjamin Cardozo: "The criminal is to go free because the constable has blundered"

**Comment by terrorist96** [comment]
> Don't you think that if a person committed a crime he has an obligation to come clean on it?

The right not to incriminate yourself.

> New evidence should be able to retroactively justify acts in the past that may have at first appeared to have had no justification.

This logic allows for unchecked police power with the *possibility* of successfully suing the violator of your privacy (the cop). That also presumes that you have the capability to sue them (afford a lawyer, etc). 
This logic allows for ex post facto crimes.

> New evidence should be able to retroactively justify acts in the past that may have at first appeared to have had no justification.


New evidence should only be able to be used for exoneration of crimes, not pursue a charge that was already dismissed. This would violate no double jeopardy.

> By not allowing the police to present the evidence in court, the court assumes they are guilty while at same time not allowing the police to defend themselves with the only evidence they have, which proves retroactively, that the search was justified.

The police are able to petition to present the evidence. The judge looks at their reasoning. If he sees that there was an exigent circumstance in which getting a warrant would lead to destruction of evidence of a crime, then he can allow the evidence to be presented before the jury. If he sees the cop violated the person's right unnecessarily by not obtaining a warrant first, he throws out the evidence because it is tainted (remember: the evidence hasn't proven the person guilty of a crime yet, so the 'suspect' is still an individual (with all the rights thereof), not a criminal). The burden is on the police to try to explain why their evidence should be admissible when they failed to get a warrant prior.
The reasoning for the search cannot be justified by what the search bears. The reasoning for the search must be justified by outside or related factors that justify the search. If cops can search for evidence just because they might be able to find some, not because they have articulable reasons why to justify that search to begin with, then why even have the warrant requirement? No cop would waste their time getting a warrant.

> a guilty person has an obligation to come clean on his crimes.

This also scares me. So, what if he's guilty but refuses to come clean? Would torture be justified in order to make him meet his obligation?
No person is obligated to incriminate themselves. It's already in the constitution (and many other constitutions around the world).

**Comment by FellowTraveler** [comment]
I can't believe this is even a debate. The Fruit of the Poisonous Tree is such a vital protection of our rights that I shudder to think of the abuses that would ensue without it.

The argument *"but what if a criminal gets away?"* is disproved by the conviction and imprisonment rate in the U.S. The LE build their cases effectively -- and still abuses occur, but at least the exclusionary rule keeps them halfway honest.

**Comment by KacperZajc** [comment]
@FellowTraveler 

You think this is not strict enough?

No law shall allow for any evidence, which was obtained illegally, to be admitted in the Criminal Court unless the violation of law was merely incidental to the manner in which said evidence was obtained; in any event any person responsible for the breach of law shall be prosecuted.

**Comment by yopdog** [comment]
Having thought about it a bit, I think I may be seeing the problem with not having the exclusionary rule. If the court allowed illegally obtained evidence to be presented, it will make the court a participant to the violation of the defendant's privacy. In other words, The court is cooperating with the police to violate a person's constitutional right.  

Having said that, I can imagine a situation where it can get complicated. Suppose we have a company who claims to sell free range organic chickens. Then one day two animal rights activists sneak into the companies land (illegally) and find out to their horror that the chickens are being stuffed into tiny burns while being forced fed through pipes. Thay then go and publish videos online proving that the company has been committing a massive fraud against it's customers.

In a case like this, would a customer of the company (a third party) be able to sue the company based solely on the videos trending online? Should the court dismiss the case because the evidence was collected illegally despite the fact that everybody knows about it?

**Comment by terrorist96** [comment]
Those that trespassed can and should be prosecuted. However, since that
info is now public, a cop can go to a judge with that evidence, get a
warrant, etc. It'd be similar to an insider at the farm tipping off the
cops. They can get him to sign an affidavit, take that to a judge, get a
warrant, etc.
The only problem would be if the cops themselves trespassed onto the farm,
any evidence they found would be invalid.

**Comment by FellowTraveler** [comment]
@KacperZajc

_No law shall allow for any evidence, which was obtained illegally, to be admitted in the Criminal Court unless the violation of law was merely incidental to the manner in which said evidence was obtained; in any event any person responsible for the breach of law shall be prosecuted._

-- I think it's actually fine for illegally obtained evidence to be admitted, as long as the violation wasn't committed by the POLICE. For example, let's say a trespassing vagrant breaks into a cabin searching for food, and finds a body instead. Clearly the vagrant has broken the law. If he reports it to the police, the POLICE haven't broken any laws, and based on that report, they can go to a judge to obtain a warrant and go see the body.

-- (I also don't necessarily think the vagrant should be prosecuted in that case. It should be up to prosecutorial discretion -- a prosecutor shouldn't be mandated by the Constitution to prosecute that vagrant.)

-- But the police THEMSELVES should not be able to just break-and-enter while looking for evidence. They should have to go get a warrant first. If they fail to do so, the evidence should not be admitted into court. (Period.)

-- _"unless the violation of law was merely incidental to the manner in which said evidence was obtained"_  <== I don't even know what the hell this means. Sounds like an easy backdoor for courts to rule that the evidence was acquired "incidentally". Bottom line is, the police shouldn't be breaking the law in the first place. They should know, if they are doing so, that they will NEVER obtain any evidence they can use in court. I really don't like putting "unless" in the Constitution for the poisonous tree.

**Comment by KacperZajc** [comment]
@FellowTraveler thanks for your input, it will be considered :)

**Comment by FellowTraveler** [comment]
One more example @KacperZajc. If the water company is doing some systems maintenance and somehow accidentally discovers that one of their customers is breaking the law -- but they trespassed that customer's property in doing so -- they should still be able to report it to the police, and since the POLICE haven't broken any laws, the evidence should still be admissible in court. Whether or not the water company is prosecuted for trespassing should be up to prosecutorial discretion.

But if the water company trespasses at the BEHEST of the police (the police asked them to), then in that case, it was actually the POLICE acting, with the water company merely as their agent. In this case, the evidence should NOT be admissible, and the policeman and the water company should both be prosecuted for trespassing. *All they had to do was go get a warrant first.*

**Comment by KacperZajc** [comment]
You've convinced me.

No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent of the Public Administration to be admitted in the Criminal Court unless the violation of law was committed by a 3rd party who did not act under direction of said Agent; in any event, any Person responsible for the breach of law or Constitution shall be subject to potential prosecution.

???

**Comment by FellowTraveler** [comment]
@KacperZajc 

_ in any event, any Person responsible for the breach of law or Constitution shall be subject to potential prosecution._

I would change this to:  _in any event, any Agent responsible for the breach of law or Constitution shall be prosecuted._

As for regular people (such as the vagrant) they are already subject to potential prosecution if they break the law. The public prosecutor already makes those decisions -- that's his job. But _agents_ should know that if _they_ break the law, they will _definitely_ be prosecuted for it.

**Comment by KacperZajc** [comment]
but Persons include Agents of the PA

**Comment by FellowTraveler** [comment]
Yes but my point is, vagrants and water companies MAY be prosecuted for breaking the law -- we already know that. The public prosecutor makes that decision already even if this fruit clause wasn't even there. That's up to his discretion.

But AGENTS specifically WILL be prosecuted -- no discretion.

See what I mean?

**Comment by KacperZajc** [comment]
aaa makes sense, so:

No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent of the Public Administration to be admitted in the Criminal Court unless the violation of law was committed by a 3rd party who did not act under direction of said Agent; in any event, all Agents of the Public Administration responsible for a breach or law or the Constitution shall be prosecuted.

**Comment by FellowTraveler** [comment]
@KacperZajc:  **That looks a lot better.**

A couple tiny points we might also consider:

-- If the evidence was obtained _"illegally or unconstitutionally by any Agent of the Public Administration"_ then it seems that 3rd parties are already excluded. Seems it's already specific to Agents only. So maybe it's not necessary to mention the 3rd party. (But maybe still good just for clarity's sake. I don't know.)

-- _all Agents of the Public Administration responsible for a breach or law or the Constitution shall be prosecuted._ Might want to narrow this a bit. Reason is because law enforcement will argue that the nature of their job makes it nearly impossible to _never_ break the law through their entire career, and they are facing too much liability. So might want to narrow it to "intention" breaches of the law, or to "intentional breaches in search of evidence." (Keep in mind, the prosecutor still always has discretion to charge the cop with a crime -- so this narrowing would only apply to MANDATORY prosecution.)

**Comment by KacperZajc** [comment]
No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent of the Public Administration to be admitted in the Criminal Court unless the violation of law was committed by a 3rd party who did not act under direction of said Agent; in any event, all Agents of the Public Administration responsible for intentional breaches of the law of the Constitution in search of evidence shall be prosecuted.

**Comment by FellowTraveler** [comment]
@KacperZajc  Looks good.

Another typo: _all Agents of the Public Administration responsible for intentional breaches of the law of the Constitution_

Should be: _all Agents of the Public Administration responsible for intentional breaches of the law OR the Constitution_

Also curious about the first line: _No law shall allow for any evidence which was obtained illegally or unconstitutionally by any Agent of the Public Administration to be admitted in the Criminal Court_

Shouldn't it be?: _No evidence which was obtained illegally or unconstitutionally by any Agent of the Public Administration shall be admitted in the Criminal Court_

**Comment by KacperZajc** [comment]
we use "no law shall..." in every provision of the Bill of Rights to be consistent :)
