### ISSUE TITLE
gag orders restrictions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#182]
• §II.14. No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without the consent of the rightful owners, protection of minors and vulnerable parties to a trial in a court of law.

how to restrict gag orders?

**Comment by terrorist96** [comment]
I feel like

§II.7. No law shall abridge the freedom of thought, feeling, belief, opinion, and conscience, or their peaceful expression or dissemination, as in speech, press and other media, artistic depiction, or religious practice; nor shall any law promote or hinder any religion, artistic culture, gender or specific community.

is a more germane section to restrict gag orders in, since gag orders are essentially a restriction on speech.

**Comment by KacperZajc** [comment]
I feel II.7 is more about expression of one's opinion whereas II.14 is about publication of information and gag orders are designed to prevent such publications.

**Comment by terrorist96** [comment]
Gag orders prevent publication AND expressing one's opinion about it. (simply talking about its existence is illegal)

**Comment by terrorist96** [comment]
Did we come to a resolution for this?

**Comment by terrorist96** [comment]
Nvm, covered by II.14
