### ISSUE TITLE
rewording II. 2 and II 7

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#194]
§II.7. No law shall allow for the private property to be fully or partially taken for the public use without the express and informed consent of, and mutually agreeable compensation to, the owner; anything found in the ground under one’s land or growing naturally on it shall belong to oneself, and no law shall regulate its use .

§II.2. No law shall deprive any Individual of one’s right to exclude from their property any Person whatsoever including an Agent of the Law Enforcement where acting without a Warrant; owners shall have the right to regulate conduct of everyone on their property.

**Comment by terrorist96** [comment]
§II.7. No law shall allow for confiscation of private property, either fully or partially, for the public use

**Comment by KacperZajc** [comment]
§II.7. No law shall allow for confiscation of private property, either fully or partially, for the public use; anything found in the ground under one’s land or growing naturally on it shall belong to oneself, and no law shall regulate its use .

§II.2. No law shall deprive any Individual of one’s right to exclude from their property any Person whatsoever including an Agent of the Law Enforcement where acting without a Warrant; owners shall have the right to regulate conduct of everyone on their property.

**Comment by yopdog** [comment]
I think there should be a limit on how deep underground, land property can go. There is a lot of space underground and I don't think it's fair to allow people to homestead tens of thousands of cubic meters of space because they laid claim to a few square meters of land.

>anything found in the ground under one’s land or growing naturally on
>it shall belong to oneself

I have a small problem with the wording here since not everything on a person's property automatically belongs to him. Interpreted literally it could allow an owner of an underground parking lot to lay claim to all the cars who entered his property. 

My suggestion would therefore be the following:
 
§II.7. No law shall allow for confiscation of private property, either fully or partially, for the public use; nor shall it limit one's use and control of their property, so long as no negative rights of others are infringed.

**Comment by KacperZajc** [comment]
cars dont grow naturally on the ground xD

**Comment by terrorist96** [comment]
We should keep this:
> without the express and informed consent of, and mutually agreeable compensation to, the owner;

**Comment by KacperZajc** [comment]
ok, changing
