### ISSUE TITLE
List of new changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#204]
1) §I.9: Add "including the Law Enforcement" in the "Agent of the Public Administration" part of the provision.

2) add §I.10: All Rights listed in this Constitution shall be exercisable only where no negative rights of others are infringed by force, fraud, of threat thereof, or unbeknownst to them.

3) add §I.11: All Members of the Public Administration shall hold the citizenship of the Free Republic of Liberland. 

4) add §I.12: All Individuals holding the citizenship of the Free Republic of Liberland shall have the right to participate in any elections and referendums in the Free Republic of Liberland. 

5) add to the Bill of Rights preamble "and its Members and Agents both within and outside the territory of the Free Republic of Liberland."

6) §II.1: change 2/3 to "two-thirds"

7) §II.6: remove " within the Free Republic of Liberland or in any place subject to its jurisdiction.

8) §II.8: remove "so long as no negative rights of others are infringed by force, fraud or threat thereof, or unbeknownst to them"

9) §II.9: "remove "so long as no negative rights of others are infringed"

10) §II.10 remove "where no negative rights of others are infringed"

11) §II.12 remove "and the Law Enforcement"

12) §II.14: remove "nothing in this provision shall prevent the Assembly from regulating the rules concerning protection of sources used by journalists, accessing information without the consent of the rightful owners, protection of minors and vulnerable parties to a trial in a court of law."

13) §II.14: add "nothing in this provision shall prevent the Assembly from regulating the rules concerning accessing of private information without consent of the rightful owner, protection of journalists'sources and minors; no order preventing sharing any information shall be served unless sanctioned by a court of law and for the protection of vulnerable parties to a civil or criminal trial or Agents of the Law Enforcement while acting undercover pursuant to a Warrant only; the fact that an order has been served shall not be a subject matter of another order."

14) §II.15: remove "or Agent of the Law Enforcement"

15) §II.21: add "absent exigent circumstances where an Individual is incapable of consenting or refusing."

16) §II.36: substitute "Public Administration" for "Law Enforcement"

17) §II.39(5): add "beyond reasonable doubt" at the end

18) §III.9(1): remove the whole subsection 

19) §III.19: change 3 to "three"

20) §III.20: change 90 to "ninety"

21) §IV.5(4): change "simple majority" to "two-thirds"

22) §V.6: change "him or her" to "the Chief Justice"

23) §V.6(6): change "unanimously" to "with a simple majority"

24) §V.8(1): change 6 to "six"

**Comment by liberlandcitizen** [comment]
"All Individuals holding the citizenship of the Free Republic of Liberland shall have the right to participate in any elections and referendums in the Free Republic of Liberland."

What about citizens who are say....5 years old?

**Comment by KacperZajc** [comment]
Individual means a person of age, see the General Provisions Article

**Comment by terrorist96** [comment]
> §I.10: All Rights ~~listed~~ **enumerated** in this Constitution shall be exercisable only where no negative rights of others are infringed by force, fraud, of threat thereof, or unbeknownst to them.

;
> §I.12: All Individuals holding the citizenship of the Free Republic of Liberland shall have the right to participate in ~~any~~ **all** elections and referendums in the Free Republic of Liberland.

;
> 5) add to the Bill of Rights preamble "and its Members and Agents both within and outside the territory of the Free Republic of Liberland."

I feel like Member should be encompassed by Agent. An Agent of the PA is anyone that works for the PA. Members (elected reps) work for the PA. They are all Agents. This should be reflected in I.9 along with law enforcement.

>  §II.1... with the permission of 2/3 of all Assembly Representatives

Should also be changed to say `express and informed consent` instead of `permission`

> 13) §II.14: add "nothing in this provision shall prevent the Assembly from regulating the rules concerning accessing of private information without **the** consent of the rightful owner, protection of **journalists' sources** and minors; no order preventing sharing any information shall be served unless sanctioned by a court of law ~~and~~ for the **sole purposes of** protection of vulnerable parties to a civil or criminal trial or Agents of the Law Enforcement while acting undercover pursuant to a Warrant ~~only~~; the fact that an order has been served shall not be a subject matter of another order."

So we're going to leave consent ambiguous here? I'm in favor of implied consent for this. Because for example, if you publish something online or otherwise make it available, to the public, you have given implied consent for people to access it.

> 23) §V.6(6): change "unanimously" to "with a simple majority"

Can we debate this?

**Comment by KacperZajc** [comment]
13) I dont understand?
23) sure we can; the problem is that declaration of constitutionality required an unanimous vote but at the same time the SC was able to overrule its previous decision by a simple majority in the course of civil/criminal proceedings.

It just doesnt make sense.

**Comment by terrorist96** [comment]
It says consent of the rightful owner. What kind of consent? Implied? Express? Or informed? 

We should start with the presumption that every law passed is unconstitutional until proven otherwise. If we require a unanimous declaration that it's constitutional, it's very safe to assume that it is. But if later on someone challenges its constitutionality, there is doubt that it could be unconditional and a simple majority could rule as such based on the evidence presented (that wasn't considered during its initial review). It will allow for more laws to be declared unconditional more easily. First by setting the bar very high and then beyond able to easily go back and fix an  error of judgement and declare it unconstitutional.

**Comment by KacperZajc** [comment]
I understand the logic here but it doesnt make sense when 3 Justices of the Supreme Court can overrule a verdict given by 5 Justices. We have to think how to go around that.

**Comment by terrorist96** [comment]
I understand. However, in my view, laws being declared unconstitutional is a good thing and it should be as easy as possible to do that. One, by making it hard for a law to be declared constitutional and two, by making it easy to declare unconstitutional those that may have slipped through the cracks due to newly presented evidence. I'd be interested in other's opinion on this.

**Comment by terrorist96** [comment]
I feel like it's analogous to requiring a unanimous jury to declare guilt, but only one juror to hang the jury. And if one does end up getting a guilty verdict and they appeal, a simple majority can overturn the conviction.

**Comment by KacperZajc** [comment]
OK Im not changing it now.
