### ISSUE TITLE
Patents, trademarks, copyright

### ISSUE THREAD

**Issue by tinkyholloway** [liberland/constitution#21]
You can be sure selling out to the MPAA will be an early trade for some treaty.

It does seem to be a big objectivist vs anarchist point of difference (beyond the obvious). What are the main views held here on this topic?

**Comment by KacperZajc** [comment]
My team is currently working on intellectual property laws, please I am open to your suggestions what those laws should look like?

**Comment by cpacia** [comment]
I'm pretty solidly against intellectual property laws there's both a pretty strong philosophical case and economic case against such laws. And I'm under the impression that a majority of professional economists would not enact intellectual property laws if the could do it over. 

Some reading:
[Against Intellectual Property](https://mises.org/library/against-intellectual-property-0) Makes a strong philosophical case based on libertarian principles. 

[Against Intellectual Monopoly](http://levine.sscnet.ucla.edu/general/intellectual/against.htm) book by a couple economists that makes a comprehensive economic case against such laws.

**Comment by cpacia** [comment]
To the extend such laws exist, they definitely should not be enshrined in the constitution, but rather should be a normal bill subject to a vote.

**Comment by KacperZajc** [comment]
of course I am now talking about ordinary laws

**Comment by burningtree** [comment]
It would be nice if the discussion of the ordinary law moved into the repository designated for that purpose:
https://github.com/liberland/laws , issues - https://github.com/liberland/laws/issues

**Comment by Carlos-Libertad** [comment]
I'm libertarian and am in favor of respect for Intellectual Property in Liberland laws. I believe, as Ayn Rand, that respect for private property must be both, physical things and the intellectuals creations. Some of the arguments that Stephan Kinsella proposes against IP, are wrong. The problem of IP is not a matter of scarcity, as he says. The subject of intellectual property is a moral issue. Men who dedicate their lives to research and artistic creation need to receive a fair compensation for their work in order to survive. Society, morally, should give them money according with the benefits that their creative ideas are bringing to others. If not, they will not be able to continue researching and creating art.

Another important point in favor of IP is the fact that (as the Austrian Economics explains) without private property, there are no prices, and without prices, economic calculation is impossible; so the economy goes into chaos. Without IP, you can not know which are the more necessary investigations for the development of human productivity, because you can not make a correct calculation of cost-benefit-losses. All Austrian price theory is fully applicable to the issue of IP.

It seems to me clear that a libertarian community that does not respect the IP has no future at all. I bet they will want to participate in it very few researchers, inventors, designers, novelists, composers, filmmakers, etc... And how many countries will want to have diplomatic relations with a country that does not respect international copyright laws? I bet very few.

**Comment by terrorist96** [comment]
Saying that without copyright, no one will innovate is wrong. If it were true, how do you explain things like Wikipedia? The first copyright law in the US was enacted in 1790. How do you explain all the innovations that occurred prior to that?
I do see your point in that some countries may not wish to associate with Liberland because of intellectual property issues though, but I'm sure that can be worked out.

Check out the link @cpacia posted:
https://mises.org/library/against-intellectual-property-0
I haven't read/listened to it myself since I don't need persuading in the matter. But I'd be interested in your perspective after having read/listened to that book. :smiley:

**Comment by Carlos-Libertad** [comment]
@terrorist96 
And how do you explain that until 1790, for thousands of years, man has produced so few, few technological innovations compared to the incredible achievements that have been made since then, in just 200 years? How do you explain the explosion of technology, industry, engineering, medicine, communications, computers etc.. that has occurred in the few years after 1790?

And on the other hand, you must not forget that a country needs to have diplomatic relations with others. If not, that country will soon be full of criminals who will steal and will run away, so you'll never catch them. A nation needs to have legal relationships with others to ask extraditions of criminals and to sign free trade treaties etc ... You can not live on an isolated island without collaborating with others, this is one of the most important ideas of liberalism.

**Comment by terrorist96** [comment]
The answer to that would be the industrial revolution, not government protectionism.

**Comment by Carlos-Libertad** [comment]
@terrorist96
It is obvious that the cause was the Industrial Revolution, but I believe that patents have contributed positively in this revolution. Many people have been able to devote their entire lives to the scientific and technical research because patents have given them economic benefits. If they had not earned that money, those people should have dedicated their lives to other paid jobs in order to survive.

**Comment by cpacia** [comment]
@Carlos-Libertad There is actual scientific work by economists who have produced numerous empirical studies. You don't need to rely on your gut feelings for figure out if patents contribute economic benefits. 

I linked to one such study above and will do it again [here](http://levine.sscnet.ucla.edu/general/intellectual/against.htm).
