### ISSUE TITLE
waiting for suggestions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#238]
1) How to guarantee the right to film and take photos in public?
2) How to prevent the government from using private companies to avoid constitutional protection?

**Comment by terrorist96** [comment]
You already know my position on these; I'll let someone else chime in.

**Comment by yopdog** [comment]
1) We can just have a provision that guarantees the right to film on  government property. As for private property, that's entirely up to the owner since he has the right to regulate conduct on his property as guaranteed in provision §II.2.   

2) I disagree with the idea that companies can be used to infringe on people's rights. The Constitution is binding upon everyone and no company can infringe on someone's rights any more than the government can.

**Comment by terrorist96** [comment]
I agree that we should make the Constitution applicable to the government and legal persons because your right to not have your rights infringed upon is guaranteed in the Constitution, so private companies cannot infringe upon your rights either (ie no slavery, recklessly losing control of your private info, etc)

**Comment by terrorist96** [comment]
Then the argument can be made for 'don't do business with that company, they'll go out of business' isn't realistic in Liberland solely because of its limited real estate, there's physically not enough room for sufficient competition to drive out a bad company.

**Comment by yopdog** [comment]
Companies in Liberland will have competition from outside as well. I wouldn't worry about it. Secondly, Losing private info isn't necessarily a violation of someone's rights unless there was a promise to keep the data safe.

**Comment by terrorist96** [comment]
> Losing private info isn't necessarily a violation of someone's rights unless there was a promise to keep the data safe.

I think it should be because the right to privacy is guaranteed in many of the provisions.

**Comment by yopdog** [comment]
Yes, but that doesn't mean you can't voluntarily give away your privacy. If you walk up to a random guy on the street and give him your private info, then that's your choice. You can't later claim damages if he exposes your info to others unless you had an agreement with him. The same is true for websites. it all depends on what was agreed upon.

**Comment by KacperZajc** [comment]
see #245
