### ISSUE TITLE
proposed provisions

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#245]
New provisions:

No law shall allow any branch of the Public Administration to contract with any legal and/or natural Person for the purposes of acquiring data it itself is not entitled to acquire under this Constitution; nor shall any branch of the Public Administration be allowed to procure any legal and/or natural person to commit what it itself is not entitled to commit under this Constitution. 

No law shall award protection to any Person due to any legal personality one is contractually linked to against any claims for losses suffered due to civil wrongs committed by said Person other than flowing from contractual liability; no Person shall be immune to criminal prosecution due to any legal personality if one is personally liable for the alleged commitment of an offence.

does it make sense?

Restated: 

No law shall prevent any Person from video and/or audio recording landscapes and other Persons in public spaces for private use; nor shall it prohibit video and/or audio recording of any Agent of the Public Administration in all areas where there is no reasonable expectation of privacy and whilst on duty.

§II.14. No law shall regulate any printed materials, radio, television, the Internet or any other medium of exchange of information; no law shall regulate the rules concerning uploading, transmitting, displaying, accessing and/or publishing such information; nor shall any law introduce licensing and/or registration to infringe upon these rights; nothing in this provision shall prevent the Assembly from regulating the rules concerning accessing and/or publishing of private information without the consent of the rightful owner, protection of journalists' sources and minors; no order preventing sharing any information shall be served unless sanctioned by a court of law for the sole purposes of protection of vulnerable parties to a civil or criminal trial or Agents of the Law Enforcement while acting undercover pursuant to a Warrant; the fact that an order has been served shall not be a subject matter of another order.

§II.17. No law shall allow for any branch of the Public Administration to require any Individual to register and/or inform about one's whereabouts, being it permanent or temporary unless pursuant to a Warrant; nor shall any branch of the Public Administration be allowed to require any Individual to register and/or share information about one’s medical condition, religion, political affiliation and/or any permanent attributes unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland.

**Comment by yopdog** [comment]
>No law shall award protection to any Person due to **any legal personality one is contractually linked to against any claims for losses suffered due to civil wrongs committed by said Person other than flowing from contractual liability;** no Person shall be immune to criminal prosecution due to any legal personality if one is personally liable for the alleged commitment of an offence.

I find this wording to be very confusing, especially the part I highlighted. I think my wording was much clearer and easier to understand.  

§II.41. No law shall deprive any Individual of the right to collect damages of any kind from those who have harmed him and are responsible for his losses **(Individual's have the right to collect damages)**; nor shall it diminish the amount of money paid to a victim to below the cost of damages he has incurred **(Individual's have the right to collect 'all' damages they incurred)**; no special protection against liability shall be created for any individual or group regardless of their position. **(No law can lower an Individual's responsibility for his actions)** 

What was the problem with this?

**Comment by terrorist96** [comment]
> No law shall award protection to any Person due to any legal personality one is contractually linked to against any claims for losses suffered due to civil wrongs committed by said Person other than flowing from contractual liability; no Person shall be immune to criminal prosecution due to any legal personality if one is personally liable for the alleged commitment of an offence.

does it make sense?

No, not really. I do prefer yopdog's version (with some minor clean up).

> No law shall prevent any Person from video and/or audio recording landscapes and other Persons in public spaces for private use;

So it can't be broadcast on the news? What's the definition of landscape? Does it include public buildings, et cetera?

> §II.17.... nor shall any branch of the Public Administration be allowed to require any Individual to register and/or share information about one’s medical condition, religion, political affiliation and/or any permanent attributes such as **fingerprints** or DNA unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland.

I don't like listing the things that are protected from registration/disclosure because there will always be something that's missed (like the government could make you register your sexual orientation, for example, since that's not enumerated). I'd say change it to "...about one's personal attributes unless pursuant to a Warrant"

**Comment by yopdog** [comment]
>No law shall prevent any Person from video and/or audio recording landscapes and other Persons in public spaces for private use

Why do we need this? isn't this a victimless crime?

**Comment by terrorist96** [comment]
> Why do we need this? Isn't this already covered by the victimless crime provision?

Potentially, yes, but people could try to declare a right to privacy when out in public.

**Comment by KacperZajc** [comment]
I am really struggling with this 'damages' provision, not sure whether we actually need it (at least in the Constitution).

Regarding personal attributes - you are right @terrorist96 

What about this version:

No law shall prevent any Person from video and/or audio recording landscapes and other Persons in public spaces for private use or for publication with consent of the Persons who can be identified in the material; nor shall it prohibit video and/or audio recording of any Agent of the Public Administration in all areas where there is no reasonable expectation of privacy and whilst on duty.

???

**Comment by terrorist96** [comment]
> damages
What's mainly holding you back from adopting @yopdog's proposed text?

> attributes
Change it from `permanent` to `personal` since there are non-permanent things about you that are personal to you, like your age, height, weight, etc.

> No law shall prevent any Person from video and/or audio recording landscapes and other Persons in public spaces for private use or for publication with consent of the Persons who can be identified in the material; nor shall it prohibit video and/or audio recording of any Agent of the Public Administration in all areas where there is no reasonable expectation of privacy and whilst on duty.

This is better, we're getting closer. However, you'd have situations where cops harrass people, asking them if they intend on publishing the video/audio recording. Anything people do/say in public is public. If I can see it being done/said, I should be able to record it without interference. Now, if I choose to upload that recording to YouTube, I have to jump through hoops and get permission from everyone in the recording?
It also allows for recording of police and publishing it without their permission but not being able to record a police interaction with a suspect and publishing it, because then you'd need the permission of the suspect? There's too many caveats to this.

**Comment by yopdog** [comment]
I agree with @terrorist96, There should be no expectation of privacy in public spaces. If you are allowed to look at something, then you should also be allowed to film it. Secondly, I don't believe there is a need to protect the right to film in unowned public spaces since it is basically a victimless crime. If someone wants to claim that it violates their privacy somehow, then they can bring that up in Court and it will be settled there.       

That said here is my suggestion:

>No law shall prevent the filming and recording of Government property that is open to the public; nor shall it prohibit video and/or audio recording of any Agent of the Public Administration in all areas where there is no reasonable expectation of privacy and whilst on duty.

**Comment by terrorist96** [comment]
Using your logic of victimless crimes, we don't need to adopt any part of your suggestion because that could all fall under victimless crimes (who is the victim when you record government property? who is the victim when you record agents of the PA?)

My suggestion:

No law shall prevent any Person from video and/or audio recording in public spaces for non-governmental use.

This will prevent government surveillance, but protect all other recordings.

**Comment by KacperZajc** [comment]
@terrorist96 If the footage of passer-bys was to be published, faces can be blurred and no consent is required anymore.

**Comment by terrorist96** [comment]
That's extra work that amounts to unnecessary bureaucratic regulation. How would it be enforced?

**Comment by yopdog** [comment]
@KacperZajc Your ideas of needing to have the consent of everybody you film in public are more restrictive than what we have in most countries. I really don't think this is a matter for the Constitution. Rather, It's simply about good manners and social norms.

**Comment by KacperZajc** [comment]
I am not in favour of putting it in the Constitution. @terrorist96 is. I only meant of people who can be identified (if faces are blurred, it does not apply).

**Comment by terrorist96** [comment]
This is the extra hurdle blurring faces requires:
Instead of taking a video with your phone and uploading it directly to YouTube via the app, you have to transfer that video file to a computer, purchase video editing software, blur any and all visible faces, then upload it to YouTube, hoping that you didn't miss anyone's face lest you be in contravention of the law

**Comment by KacperZajc** [comment]
I cant think of any wording that would sounds good to me.
I want to deal with recording in public and damages later.
