### ISSUE TITLE
Copyright law

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#251]
What kind of copyright/IP laws will Liberland have? What does the constitution have to say on it? Public domain? Creative Commons? GPLv3?
And patents, trademarks, etc?

**Comment by KacperZajc** [comment]
as far as I know, none or virtually none, hard to say now

**Comment by yopdog** [comment]
This is a complex issue, I'm personally against intellectual property. I believe once information has been made public it should have no owner. Intellectual property can bring with it many problems such as patent trolls, vague limits on what can actually be owned and for how long, and limits on the ideas you can come up with (since someone else may have already thought about it). There are many libertarians who are opposed to IP for varies reasons. On the other hand, there are also libertarians who support it. I think if we can't come to an agreement on this we should just leave it out of the Constitution.

**Comment by KacperZajc** [comment]
@yopdog agree
