### ISSUE TITLE
A "yes" vote for a law shall include reading the law in its entirety

### ISSUE THREAD

**Issue by fare** [liberland/constitution#26]
All yes-men can read together in choir during the ballot.

This ensures that laws can't be too long, and that legislators can't vote on something they haven't read.

If everyone must know the law, the law better be readable by everyone. If it's not even readable by legislators, it's obviously not worth to be a law.

**Comment by fare** [comment]
(This issue is spilt from #20)

**Comment by KacperZajc** [comment]
I agree with this one, although I wouldnt put it in the constitution, mere provision in public law would suffice

**Comment by cpacia** [comment]
@KacperZajc i'll keep harping on this. If it's optional (which is what making it an ordinary law mean) they wont do it.

In the US there was a massive public outrage when people found out that politicians were insider trading and profiting from knowledge of not-yet-introduced bills. For example, they would buy up land that was very cheap, then pass a law to re-zone it, and sell it for a huge profit. 

The politicians grudgingly passed a bill making it illegal, then once people forgot about it, they repeal the bill and made it legal again. 

If you want the constitution to stand long term, you need to structural limits on what the politicians can do. Maybe the constitution wont fall overnight, but within a few decades it will. 

During the US constitution convention in Philadelphia, they debated giving the government the power to create a central bank and ultimately decided against it. So what did the very first congress do? ... Create a central bank. 

It will fail very quickly if strong limits are not put in place using very strong language. Even then I don't think it will limit government long term... which is why my original draft used a polycentric legal system with the hope that competition would be able to do what strong language cannot.

**Comment by KacperZajc** [comment]
I dont see why it is so important but I agree with the idea so OK let's put it in along with the requirement to include rationale for the Bill:

No Bill proposed to the Assembly shall be passed unless it has been read aloud by the Assembly Speaker and includes rationale behind it.

???

**Comment by cpacia** [comment]
Yeah I would agree with that. 

The reason all these little things are important, however, is because politicians notoriously don't follow the constitution. And they appoint judges who think like them and wont require them to follow the constitution.

**Comment by KacperZajc** [comment]
make it a pull then and add the sentence somewhere in the Legislative Restrictions part of the Bill of Rights
