### ISSUE TITLE
business and politics 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#264]
No Member of any branch of the Public Administration shall possess any shares of any legal Person; 
the size of personal assets as well as personal income and all its sources of all Members, and candidates for Members, of the Public Administration shall be considered public information.

Anyone wants to add anything?

**Comment by terrorist96** [comment]
What about Agents?

**Comment by yopdog** [comment]
I'm not 100%  sure about this. What about pensions and long-term saving? Do members have to give all that up in order to keep their job? Furthermore, I don't think it's entirely possible to get rid of all interests a member can have. For instance, what about land and property ownership? It could be argued that any member who owns a house has an interest in the price of property going up, thus incentivising him to support restrictions on building. 

That said, maybe we make it so they can't hold more than a certain percentage of any company. That would allow them at least to keep long-term saving and pensions that are built from diversified holdings of many companies: 

>No Member of any branch of the Public Administration shall possess more than **x%** shares of any legal Person; 
the size of personal assets as well as personal income and all its sources of all Members, and candidates for Members, of the Public Administration shall be considered public information.

**Comment by KacperZajc** [comment]
#281
