### ISSUE TITLE
up for discussion 

### ISSUE THREAD

**Issue by ghost** [liberland/constitution#281]
1. Citizens' right to repeal legislation
2. Minority's right to veto bills
3. The right not to appear in court
4. Judicial election.
5. Religious neutrality
6. Expiration of 'Special Powers' Clause
7. Supreme Court vote 
8. Expiration of laws
9. Polycentric republic philosophy 
10. Jury acquittal expressly based on morality
11. Fair Representation

**Comment by terrorist96** [comment]
> Assembly one-off projects

Private contractors are sufficient.

> Ban/restriction on possession of shares in companies by Members of the PA

The language needs to be crafted very carefully. Also, I'm in favor of requiring candidates/members to disclose the identity of large donors to their campaigns.

> Recall process for Assembly Representatives

Yes plz. And perhaps - *maybe* - for the Chancellor too?

**Comment by jasonmullins** [comment]
I very much favor specifying the right of citizens' to repeal acts.

**Comment by terrorist96** [comment]
> Citizens' right to repeal legislation

Jury nullification is already allowed. 

> Minority's right to veto bills

It'd be nice in concept, but I think it'd cripple the system too much to the point that nothing would ever get accomplished.

**Comment by jasonmullins** [comment]
> Citizens' right to repeal legislation
I don't think jury nullification is the same thing as repealing a bad law.  Are you saying a single jury can decide on nullification and then nobody else will ever be charged using the same law?  In modern government, it is nearly impossible to get rid of an old law because of the vocal minority and apathy.  I just think we need a way to repeal bad laws that doesn't involve elected politicians having to take on the political risk to do it.
> Minority's right to veto bills
I disagree.  I don't think just laws will even make it to this point in the process.  Also, it's not a stretch to think that if you can't get 3/5 to support a law then it's probably an unjust law.  A good law should be non-controversial imo.

**Comment by terrorist96** [comment]
> Are you saying a single jury can decide on nullification and then nobody else will ever be charged using the same law?

No, but a prosecutor would have trouble obtaining a conviction if no Jury would be willing to convict under that law. The law would naturally be repealed itself.
I'm not opposed to allowing referendums for repealing laws; I just don't think it's super necessary because of all the other checks and balances we have in place.

**Comment by jasonmullins** [comment]
That's a good point.  It might not be the most pressing issue - I've just always found it frustrating that there's no good way to get rid of laws.  Also - even if they can't get a conviction, a not-so-noble government could still use the law as a type of harassment as a way to get warrants and stuff.

**Comment by terrorist96** [comment]
I've proposed legislatively neutral sessions. Every now and then, there will be a time period where no new laws would be allowed to be passed unless an old and antiquated law were to be repealed.
This is more appropriate for states that have been in existence for a long time, not a brand new nation though.

**Comment by terrorist96** [comment]
What about Citizen's right to propose legislation?

**Comment by KacperZajc** [comment]
Im opposed, I want to restrict the flow of legislation as much as possible.
They can lobby 1/5 of the Assembly Reps to propose a draft to the Cabinet which can submit as a Bill.

**Comment by terrorist96** [comment]
In other words, it'd never happen. Since only one law can be proposed a year, it doesn't seem likely that the Cabinet would be willing to propose a law that the citizens want. They'd use their one chance a year to pass something **they** really want enacted.

**Comment by KacperZajc** [comment]
there is no limit on number of Bills that the Cabinet can submit
if there were, they would just put everything into 1 bill

**Comment by terrorist96** [comment]
> there is no limit on number of Bills that the Cabinet can submit

Then what does this provision accomplish?
> §III.10. The power to initiate a legislative procedure shall lie with the Cabinet only which shall be exercised only once a year upon the State of the Republic Address.

-
> if there were, they would just put everything into 1 bill

They can't, since:
> §III.6. Any Bill proposed to the Assembly shall pertain to one matter only as expressed in its title.

**Comment by terrorist96** [comment]
@KacperZajc why did you close this? These weren't resolved as far as I can tell.

**Comment by terrorist96** [comment]
@KacperZajc can you tell me what you decided to do with these?

**Comment by terrorist96** [comment]
I still stand by my proposed wording for the religious practice:

> The Public Administration shall neither promote nor disparage any religion; nor shall any law hinder the reasonable practising thereof.

**Comment by jasonmullins** [comment]
I still like the idea of providing a way for citizens to repeal legislation - that way, I could get my name added to the contributor's list for posterity.  :smiley:

**Comment by Auahi** [comment]
We need to change

> no religious symbols shall be displayed on any premises belonging to any body of the Public Administration

I know you said before it's nit picking, but I'd say otherwise. This is really vague and can mean anything from: a person can't wear a religious article of clothing on public property, to the Assembly cannot put up a poster with a religious symbol. In law you cannot have a vague concept and this needs to be reworded. I'd also argue that the you should be able to put up a poster on public property with a religious symbol on it; I think this should be removed entirely.

**Comment by KacperZajc** [comment]
Summary of different voting systems: #516

**Comment by KacperZajc** [comment]
Expiration of the 'Special Powers Clause': #482

**Comment by KacperZajc** [comment]
Supreme Court vote: #403

**Comment by KacperZajc** [comment]
Expiration of laws: #382

**Comment by KacperZajc** [comment]
Polycentric Republic idea: #58 & #357

**Comment by KacperZajc** [comment]
Acquittal expressly based on morality: #344

**Comment by KacperZajc** [comment]
Fair representation: #78

**Comment by grantmor** [comment]
As far as voting systems go, has <a href='https://en.wikipedia.org/wiki/Approval_voting#Other_issues_and_comparisons'>Approval Voting</a> been looked at?

It seems to offer a healthy balance between FPTP and something like STV in that it's a very simple system that also helps prevent the slide toward a two party system.

The ballot is just like a normal FPTP ballot, except you select as many candidates as you like. The candidate with the most votes wins.

**Comment by michalptacnik** [comment]
Closing due to long term inactivity. 

We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit
