### ISSUE TITLE
Light arms

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#289]
What is the exact definition of light arms? Does this include machine guns, flamethrowers, etc? (these should be protected)
What about grenades, mines, and C4? 
Obviously it doesn't include nuclear weapons, right? (shouldn't be protected)

**Comment by TWalls** [comment]
My personal opinion is that light arms would go all the way up to automatic
firearms. Private citizens are able to own automatic firearms under certain
conditions in some European countries (Switzerland, Luxembourg, and a few
others) so this is not completely out of the ordinary.

http://www.thefirearmblog.com/blog/2014/10/06/potd-swiss-like-machine-guns/

Grenades, mines and large cannon could be viewed as "destructive devices"
(as they are under most legal systems) and thus not protected.

Devices such as nuclear weapons are theoretical and I do not believe we
need to concern ourselves with that here.

Tom Walls

**Comment by KacperZajc** [comment]
Wikipedia:

Small Arms and Light Weapons (SALW) is a term used in arms control protocols to refer to two main classes of weapons:

Small arms: hand-held small caliber firearms, usually consisting of handguns, rifles, shotguns, manual, semi-automatic, and full automatic weapons and man-portable machineguns.
Light weapons: Includes a wide range of medium-caliber and explosive ordnance, including man-portable and vehicle-mounted antipersonnel, antitank and antiaircraft rockets, missiles, grenade launchers, rocket launchers, landmines, antiaircraft guns, mortars, hand grenades and rocket-propelled grenades (RPGs), and so on.
The U.S. Army defines small arms/light weapons (SA/LW) as: "Handguns, shoulder-fired weapons, light automatic weapons up to and including 50 caliber machine guns, recoilless rifles up to and including 106mm, mortars up to and including 81mm, man-portable rocket launchers, rifle-/shoulder-fired grenade launchers, and individually operated weapons that are portable or can be fired without special mounts or firing devices and that have potential use in civil disturbances and are vulnerable to theft."

**Comment by terrorist96** [comment]
So are `small arms` and `light weapons` synonymous? If not, should we include both?

**Comment by TWalls** [comment]
Small arms would probably be the preferred nomenclature if "small arms" and
"light weapons" are the choices.

Tom

**Comment by qm3ster** [comment]
As per the very first line of the wikipedia Small_arms article, these terms are separate and don't overlap, `light weapons` being significantly more serious, including stationary machine guns as well as greater calibers (up to 100 mm), and self-propelling or explosive ordnances.
Together with `small arms` they comprise the internationally acknowledged `UN Small Arms and Light Weapons` term, which we can reasonably expect to be updated and arbitrated for the foreseeable future.
Notably, all these are still 'offensive' projectile weapons, and do not include armaments such as mines or even handheld grenades.
Since as we all know:
1. Criminals don't follow laws.
2. Employing even unmodified civilian ground vehicles in an attack can fairly consistently make the attacker nigh invincible to `small arms` fire, even if we don't consider the threat of reinforced or autonomous vehicles, or aerial vehicles including unmanned drones.
3. It is not unimaginable that an isolated incident of a Territorial Defence Force agent going rogue in domestic territory or a TDF vehicle being hijacked would occur.
I vote that at the very least the full `UN SALW` class of weapons be put under constitutional protection.
