### ISSUE TITLE
recall and other minor changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#297]
§II.10. No law shall allow for any Person to be detained without trial for more than twenty-four hours unless pursuant to a Warrant where it is absolutely necessary for the protection of others or where an accused is likely to escape justice or interfere with the investigation; no detention pursuant to such a Warrant shall be longer than absolutely necessary to bring the accused to trial.

§II.5. No law shall allow for any branch of the Public Administration to require any Individual to register and/or share information about one's whereabouts, being it permanent or temporary, assets, being it tangible or intangible, and/or signed contracts, being it employment, commercial or otherwise, unless pursuant to a Warrant; nor shall any Person be required to register and/or share information about any personal attributes such as medical conditions, fingerprints, DNA, religion, political affiliation or others unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of owners of land within the Free Republic of Liberland.

§II.6. No law shall allow for any Individual to be prosecuted for any victimless and/or consensual crimes; no Person shall be prosecuted for any offence against society or any part thereof; no Individual shall be considered a victim of one’s actions or omissions; interfering with the work of the criminal justice system, attempting a criminal offence or knowingly giving any form of direct aid to a Person committing an offence shall not be construed as a victimless crime; nothing in this provision shall prevent the Assembly from creating offences which have their roots in this Constitution. 

§III.1(8) Any Assembly Representative may be recalled by the Citizens with a simple majority vote in a referendum called by 5% of all Citizens.

§III.1(5) Should any Assembly Representative step down, the Supplementary Election shall be held within 90 days and no vote whatsoever shall take place until a new Assembly Representative is sworn in.

**Comment by edwardtjgerety** [comment]
§III.1(5) Should any Assembly Representative step down, the Supplementary Election shall be held within 90 days and no vote, whatsoever, shall take place until a new Assembly Representative is sworn in. 

 

This is a dangerous item… and could bring government to a halt.  If an opposing view is had in the government and they know they are going to lose one member of the party simply keep resigning.    In business, this would be equal  to giving minority shareholders the right to hold everyone hostage.

**Comment by terrorist96** [comment]
> §II.10. No law shall allow for any Person to be detained without trial for more than twenty-four hours unless pursuant to a Warrant where it is absolutely necessary for the protection of others or where an accused is likely to escape justice or interfere with the investigation; no detention pursuant to such ~~a~~~ Warrant shall be longer than ~~it is~~ absolutely necessary to bring the accused to trial.

-
> nothing in this provision shall prevent the Assembly from creating offences which have their roots in this Constitution.

explain please

Rest is good

> This is a dangerous item… and could bring government to a halt.  If an opposing view is had in the government and they know they are going to lose one member of the party simply keep resigning.    In business, this would be equal  to giving minority shareholders the right to hold everyone hostage.

We need it because we require all 20 members to be present in order to vote on legislation. This prevents those sketchy votes conducted with only a few members present and no one requests a quorum call. The more realistic event would be unlimited filibusters:
"§III.8. Every Assembly Representative shall have the right to express one's opinion on the proposed Bill at least once before the vote takes place, without any time limit."

Even that has its limits though

**Comment by KacperZajc** [comment]
This allows creating offences where there is no victim such as intentional breach of constitution, possessing a tan (exceeding limitation such as small arms) etc.
Maybe we could use more precise wording if that isnt clear.

**Comment by yopdog** [comment]
If there is no victim maybe we should reconsider those parts of the constitution. After all, it's a bit hypocritical to not hold ourselves by the same standards we put into the bill of rights.

**Comment by edwardtjgerety** [comment]
May I inquire one side point, the emails that come have a header of "Terrorist96" is this a system glitch?The reason I ask is that to an outsider it could be seen as bad form. There were several terrorist attacks globally in 1996 particularly in Serbia and Russia. I'm not passing judgement but rather pointing out a media nightmare if someone takes the use of the word and the writing of the constitution as being one in the same. Little things destroy great ideas.                                                                                                                                                                                                                                                                                                                                         All the best,Edward John 'Tj' George Gerety, III                                                                                                                                                                                                                 From: terrorist96Sent: Tuesday, August 18, 2015 22:16To: liberland/constitutionReply To: liberland/constitutionSubject: Re: [constitution] free elections and other minor changes (#291)@KacperZajc I'd argue that it's necessary because it gives the Assembly permission to make laws in regards to privacy rights, etc. The way it is now, they wouldn't be able to do so. 

And can you please explain the collection of personal assets provision I inquired about above? And did you change your mind about I.1?

Thanks!  

—Reply to this email directly or view it on GitHub.

**Comment by terrorist96** [comment]
It's just an old username that I use everywhere. No connections to what you're mentioning.
