### ISSUE TITLE
Private prosecution 

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#305]
§V.10. The Victim(s) of a criminal offence shall have the inherent right to institute the Private Prosecution of alleged offenders. 
§V.10(1) The right shall be exercisable before the Office of the Public Prosecution institutes any Public Prosecution.
§V.10(2) The Victim(s) may expressly waive the right to institute the Private Prosecution.
§V.10(3) The Victim(s) shall be deemed to have waived the right to institute the Private Prosecution should it not be brought within three months since an alleged offence took place.
§V.10(4) The Private Prosecution may be instituted by the Victim(s) in person or by Proxy on its behalf.
§V.10(5) Both the Victim(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.
§V.10(6) Should some, but not all of the, Victims waived their right to institute the Private Prosecution, the accused shall be prosecuted by the Office of the Public Prosecutor in cooperation with the Victims willing to participate in the prosecution. 

§V.11. The Public Prosecution of alleged offenders shall be instituted by the Office of the Public Prosecutor.
§V.11(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution.
§V.11(2) Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the inherent right to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.
§V.11(3) Should there be a Victim capable of consenting, the Public Prosecution shall be instituted with the express and informed consent of the Victim and on its behalf. 
§V.11(4) Should the right to the Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.
§V.11(5) Should the Public Prosecution be instituted, the Victim(s) shall have the right:
§V.11(5)(a) to be notified about the schedule of the judicial proceedings; 
§V.11(5)(b) to address the Criminal Court before the sentence is determined; 
§V.11(5)(c) to be advised of release from custody or escape of the accused offender.

§V.12. The Office of the Chief Public Prosecutor shall be independent and shall be headed by the Chief Public Prosecutor.
§V.12(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term not exceeding six years.
§V.12(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of all Citizens.
§V.12(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.

Renumbering the rest of the provisions...

Rephrasing: 

§V.11. The criminal offences in the Free Republic of Liberland, whether prosecuted privately or publically, shall be tried in the Criminal Court before a Judge with a panel of Jury to give a verdict of ‘Guilty’ or ‘Not guilty'.

§II.17. No law shall allow for any Person to be prosecuted for more than one criminal offence for one act or omission they are accused of; nor shall one be put twice in jeopardy of a penalty for the same offence, whether by the Private or Public Prosecution.

**Comment by yopdog** [comment]
I have a few issues with this. I will deal with them when I have time.

**Comment by terrorist96** [comment]
I'm assuming V.10/11/12 intended to be new provisions, not replacing the current V.10/11/12 provisions.

> §V.10(6) Should some, but not all**,** of the~~,~~ Victims waive~~d~~ their right to institute the Private Prosecution, **the** alleged offenders shall be prosecuted by the Office of the Public Prosecutor in cooperation with the Victims willing to participate in the prosecution.

Moved comma, etc. Also, let's standardize the wording. `Alleged offenders` or `accused`? (are there any other variations of this in the constitution already?)

> §V.11(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution should the Victim(s) waive~~d~~, either expressly or impliedly, the right to the Private Prosecution.

Side note: if private prosecution is deemed a "right", shouldn't it be moved to the Bill of Rights sections?

> §V.11(3) Should there be ~~the~~ **a** Victim~~(s)~~ capable of consenting, the Public Prosecution shall be instituted with the express and informed consent of the Victim and on its behalf. 

> §V.11(4) Should evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.

This conflicts with 11(3)..

> V.11(5)

Need to change to (a), (b), (c), not (a), (a), (a).

**Comment by KacperZajc** [comment]
Id go for 'accused' everywhere.

§V.11(4) Should the right to the Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.

**Comment by terrorist96** [comment]
:+1:

**Comment by yopdog** [comment]
>§V.10(5) Both the Victim(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.

Could you explain this please?

>§V.10(3) The Victim(s) shall be deemed to have waived the right to institute the Private Prosecution should it not be brought within three months since an alleged offence took place.

Why has he waved his right? Maybe he is just not interested in prosecuting. It's his right to decide. 

>§V.10(4) The Private Prosecution may be instituted by the Victim(s) in person or by Proxy on its behalf.

This is completely unnecessary, if there is a right to prosecute privately then a person can obviously use any arrangement he wants. 

>§V.10(6) Should some, but not all of the, Victims waived their right to institute the Private Prosecution, the accused shall be prosecuted by the Office of the Public Prosecutor in cooperation with the Victims willing to participate in the prosecution.

Again, this is unnecessary. I think it's already clear that if one victim waves his right to public prosecution it's for that victim alone and not for any other victims involved. 

>~~§V.10(2) The Victim(s) may expressly waive the right to institute the Private Prosecution.~~

>§V.11(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution **should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution.**

Isn't it a bit repetitive to have this and §V.11(1)? I believe §V.11(1) should be enough.  

>§V.11(2) Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the inherent right to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.

What about the families of victims? Don't they have the right to Prosecute privately? 

>§V.11(4) Should the right to the Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.

What if the victim doesn't want to prosecute at all? Does that count as waving the right to private prosecution?

>§V.11. The criminal offences in the Free Republic of Liberland, **whether prosecuted privately or publically**, shall be tried in the Criminal Court before a Judge with a panel of Jury to give a verdict of ‘Guilty’ or ‘Not guilty'.

>§II.17. No law shall allow for any Person to be prosecuted for more than one criminal offence for one act or omission they are accused of; nor shall one be put twice in jeopardy of a penalty for the same offence, **whether by the Private or Public Prosecution.**

Why is it necassery to add "whether by the Private or Public Prosecution"? What point does it serve?

**Comment by KacperZajc** [comment]
§V.10(5): Victims cannot apply for Warrants, arrest etc.
§V.10(3): Waving the right is necessary for the Public Prosecution to begin. If Victims do not feel like doing it on their own, they waive their right to prosecute as first and then the Chief Public Prosecutor can deal with the issue.
§V.10(4): I want only victims to be able to prosecute, not family members or anything else because then it makes it impossible to determine who has and who has not this right to private prosecution. The only exception is the proxy, and that is why I articulate it.
§V.10(6): It is necessary because otherwise it's impossible to tell who prosecutes if one victims waives his or her right and the other one does not.
§V.10(2): Maybe yes, maybe not, I want to make sure everything is clear.
§V.11(2): see §V.10(4) answer
§V.11(4): read §V.11(4) in conjunction with §V.11(3), it makes sense together. The point is to make sure the Public Prosecution takes place if the victim wants it no matter who might be the accused (e.g. Prosecutor might not be eager to prosecute a politician etc.)
§II.11 and 17: I just want to make everything clear.

**Comment by yopdog** [comment]
>§V.10(5): Victims cannot apply for Warrants, arrest etc.

§I.10. All Warrants in the Free Republic of Liberland, other than the Supreme Warrant, shall be issued by a Judge of the Criminal Court **upon request by an Agent of the Law Enforcement** and shall be supported by evidence of probable cause; such Warrants shall be as detailed as possible and shall refer to one Person only; every Warrant granted for a continuous action shall expire no later than after one year and shall be renewed by another Judge in accordance with ordinary procedure.

Does prosecuting privately make you a law enforcement agent? I just don't see the connection between prosecuting privately and the right to apply to a warrant. 

>§V.10(3): Waving the right is necessary for the Public Prosecution to begin. If Victims do not feel like doing it on their own, they waive their right to prosecute as first and then the Chief Public Prosecutor can deal with the issue.

But what if he doesn't want to prosecute at all? Will the public prosecutor come in and prosecute on his behalf even if he doesn't want them to? 

>§V.10(4): I want only victims to be able to prosecute, not family members or anything else because then it makes it impossible to determine who has and who has not this right to private prosecution. The only exception is the proxy, and that is why I articulate it.

The right to prosecute privately should be for citizens in general and not for 'victims' specifically. Furthermore, you can't always determine who is a victim before a trial, can you? 

>§V.10(6): It is necessary because otherwise it's impossible to tell who prosecutes if one victims waives his or her right and the other one does not.

I think it's pretty clear that that if a victim 'waves his right' to private prosecution, it's for that victim alone and that in no way prevents the other victims from prosecuting privately.    

>§II.11 and 17: I just want to make everything clear.

Believe me, It's clear enough. Those parts are just unnecessary and can be removed.

**Comment by KacperZajc** [comment]
§V.10(5): I dont want to see any claims for special treatment, Id rather keep it.
§V.10(3): if the victim doesnt want to prosecute at all, the Public Prosecutor will not do it either, he need consent

§V.10(4): when you consider the double jeopardy rule, you dont want any random person to be able to prosecute, Im sticking with Victims
If the Public prosecution is launched because a person was not considered a victim, then it is a decision of the public body and as such subject to the judicial review in the civil court, no problem here

§V.10(6): you're on this one
§II.11: you're probably right
§II.17: Id rather keep this to be safe

**Comment by yopdog** [comment]
To be honest, I think this whole thing can be implemented better. A much simpler and cleaner implementation would be to just define the powers the public prosecutor has in relation to the citizens. Here is how I would like to see it implemented:   

>§V.10. The Office of the Public Prosecutor shall be the main body in charge of prosecuting on behalf of the Public Administration, and shall be headed by the Chief Public Prosecutor.

>§V.10(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term not exceeding six years.
§V.10(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of all Citizens.
§V.10(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.
§V.10(4) The Public Prosecutor shall retain the power to prosecute on behalf of citizens who choose to have their case prosecuted by the Public Prosecutor. 
§V.10(5) Should a criminal offence leave no Victim(s) capable of Prosecuting and no private prosecution has taken place since the alleged offence the Public Prosecutor shall have the power to institute a Public Prosecution on behalf of the victim 
§V.10(6) Should a Public Prosecution be instituted, the Victim(s) shall have the right:
§V.10(6)(a) to be notified about the schedule of the judicial proceedings; 
§V.10(6)(b) to address the Criminal Court before the sentence is determined; 
§V.10(6)(c) to be advised of release from custody or escape of the accused offender.

I think this would be a much cleaner implementation. Why do we need so many provisions just to explain when and how a victim can choose to have his case prosecuted publicly? isn't §V.10(4) enough? Another thing is getting rid of the term 'waving away a right'. Rights aren't waved away just because you don't exercise them. it's like saying you wave away your right to not be stabbed when you go and have an operation by a doctor. Clearly that's not the case.  

Any objections?

**Comment by KacperZajc** [comment]
I think this isnt clear at all.
It would require a series of judicial verdicts to determine what you mean by this provision.

here is my amended proposal: 

§V.11. The Victim(s) of a criminal offence shall have the inherent right to institute the Private Prosecution of the accused. 
§V.11(1) The Victim(s) may expressly waive the right to institute the Private Prosecution.
§V.11(2) The Victim(s) shall be deemed to have waived the right to institute the Private Prosecution should it not be brought within three months since an alleged offence took place.
§V.11(3) The Private Prosecution may be instituted by the Victim(s) in person or by Proxy on its behalf.
§V.11(4) Both the Victim(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.

§V.12. The Public Prosecution of alleged offenders shall be instituted by the Office of the Public Prosecutor.
§V.12(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution and give its informed and express consent.
§V.12(2) Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the inherent right to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.
§V.12(3) Should the right to the Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.
§V.12(4) Should the Public Prosecution be instituted, the Victim(s) shall have the right:
§V.12(4)(a) to be notified about the schedule of the judicial proceedings; 
§V.12(4)(b) to address the Criminal Court before the sentence is determined; 
§V.12(4)(c) to be advised of release from custody or escape of the accused offender.

§V.13. The Office of the Chief Public Prosecutor shall be independent and shall be headed by the Chief Public Prosecutor.
§V.13(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term of six years.
§V.13(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of all Citizens.
§V.13(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.

§II.17. No law shall allow for any Person to be prosecuted for more than one criminal offence for one act or omission they are accused of; nor shall one be put twice in jeopardy of a penalty for the same offence, whether by the Private or Public Prosecution.

BTW thank you for raising this issue in the first place.

**Comment by yopdog** [comment]
>§V.10(3): if the victim doesn't want to prosecute at all, the Public Prosecutor will not do it either, he need consent

Answering to your earlier comment, §V.10(3) clearly states the if three months have passed and the victim has not prosecuted, then he would be deemed to have given consent. How can you deem that someone has consented when he hasn't actually consented??

**Comment by KacperZajc** [comment]
as amended:

§V.12(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution and give its informed and express consent.

(it was in two separate provision earlier)

**Comment by yopdog** [comment]
@KacperZajc could you explain what exactly is missing from my suggestion?

**Comment by KacperZajc** [comment]
you fail to mention private prosecution, you fail you say how it is done, by whom and when;
under your suggestion, the right to private prosecution can be render meaningless by ordinary law because you fail to articulate what this right even means

the whole point of this constitution is to make sure the gov can diminish your rights via ordinary law and your proposal fails to comply with this requirement 

Im grateful you pressured me into securing the right to private prosecution but your wording fails to achieve it

**Comment by yopdog** [comment]
>§V.10. The citizens of the Free Republic of Liberland shall have the inherent right to institute Private Prosecution. 
§V.10(1) Private Prosecution may be instituted by Individual(s) in person or by Proxy on its behalf.
§V.10(2) Both the Individual(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.

>§V.10. The Office of the Public Prosecutor shall be the main body in charge of prosecuting on behalf of the Public Administration, and shall be headed by the Chief Public Prosecutor.
§V.11(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term not exceeding six years.
§V.11(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of all Citizens.
§V.11(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.
§V.11(4) The Public Prosecutor shall retain the power to prosecute on behalf of Individuals who choose to have their case prosecuted by the Public Prosecutor. 
§V.11(5) Should a criminal offence leave no Victim(s) capable of Prosecuting and no private prosecution has taken place since the alleged offence the Public Prosecutor shall have the power to institute a Public Prosecution on behalf of the victim 
§V.11(6) Should a Public Prosecution be instituted, the Victim(s) shall have the right:
§V.11(6)(a) to be notified about the schedule of the judicial proceedings; 
§V.11(6)(b) to address the Criminal Court before the sentence is determined; 
§V.11(6)(c) to be advised of release from custody or escape of the accused offender.

??

**Comment by KacperZajc** [comment]
Sorry but I really dont think it is a good idea to allow any person to prosecute.
This person's intention could be to unsuccessfully attempt prosecution thereby make sure no guilty verdict will be given. Since we have double jeopardy rule, this allows criminals escape justice.
Not to mention how would you reconcile the wish to prosecute of many random people.

**Comment by yopdog** [comment]
On second thought, I think I may be ok with using 'Victim' in the wording. Families of victims will still be able to prosecute on behalf of the victims as a proxy if they are mentioned in a will. 

As for the double jeopardy, maybe we should add certain exceptions like they have in the 'European convention on human rights' such as: 

>Nothing in this provision shall prevent the reopening of a case in, if there is evidence of new or newly discovered facts, or if there has been a fundamental defect in the previous proceedings, which could affect the outcome of the case.

>source - https://en.wikipedia.org/wiki/Double_jeopardy#European_Convention_on_Human_Rights

**Comment by KacperZajc** [comment]
Good.

I thought of that but I decided common law tradition is more libertarian.
It's open to abuse,
But Im open to discussion (preferable in a separate issue).

**Comment by yopdog** [comment]
>§V.10. The citizens of the Free Republic of Liberland shall have the inherent right to institute Private Prosecution. 
§V.10(1) Private Prosecution may be instituted by **Victim(s)** in person or by Proxy on its behalf.
§V.10(2) Both the **Victim(s)** or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.

>§V.11. The Office of the Public Prosecutor shall be the main body in charge of prosecuting on behalf of the Public Administration, and shall be headed by the Chief Public Prosecutor.
§V.11(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term not exceeding six years.
§V.11(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of all Citizens.
§V.11(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.
§V.11(4) The Public Prosecutor shall retain the power to prosecute on behalf of Individuals who choose to have their case prosecuted by the Public Prosecutor. 
§V.11(5) Should a criminal offence leave no Victim(s) capable of Prosecuting and no private prosecution has taken place since the alleged offence the Public Prosecutor shall have the power to institute a Public Prosecution on behalf of the victim 
§V.11(6) Should a Public Prosecution be instituted, the Victim(s) shall have the right:
§V.11(6)(a) to be notified about the schedule of the judicial proceedings; 
§V.11(6)(b) to address the Criminal Court before the sentence is determined; 
§V.11(6)(c) to be advised of release from custody or escape of the accused offender.

Any other objections/missing parts ??

**Comment by Auahi** [comment]
Why is the Chief Public Prosecutor in office for six years not four? shouldn't he be in place for a time which correlates to the general election?

**Comment by KacperZajc** [comment]
@Auahi Definitely not, the fact that the terms dont correlate ensures independence. 
@yopdog Im glad we have come to the agreement as to the substance of the provision but Id rather stick to my version.

§V.11. The Victim(s) of a criminal offence shall have the inherent right to institute the Private Prosecution of the accused. 

§V.11(1) The Private Prosecution may be instituted by the Victim(s) in person or by Proxy on its behalf.
§V.11(2) Both the Victim(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.
§V.11(3) The Victim(s) may expressly waive the right to institute the Private Prosecution.
§V.11(4) The Victim(s) shall be deemed to have waived the right to institute the Private Prosecution should it not be brought within three months since an alleged offence took place.

§V.12. The Public Prosecution of alleged offenders shall be instituted by the Office of the Public Prosecutor.
§V.12(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution and give its informed and express consent.
§V.12(2) Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the inherent right to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.
§V.12(3) Should the right to the Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.
§V.12(4) Should the Public Prosecution be instituted, the Victim(s) shall have the right:
§V.12(4)(a) to be notified about the schedule of the judicial proceedings; 
§V.12(4)(b) to address the Criminal Court before the sentence is determined; 
§V.12(4)(c) to be advised of release from custody or escape of the accused offender.

§V.13. The Office of the Chief Public Prosecutor shall be independent and shall be headed by the Chief Public Prosecutor.
§V.13(1) The Chief Public Prosecutor shall be appointed by the Chancellor for a term of six years.
§V.13(2) The Chief Public Prosecutor shall be removable from the office by the Citizens with a majority of two-thirds vote in a referendum called by 10% of the overall number of Citizens registered with the Electoral Register at the time of the last General Election.
§V.13(3) The Chief Public Prosecutor shall appoint, and be responsible for the work of, Public Prosecutors.

§II.17. No law shall allow for any Person to be prosecuted for more than one criminal offence for one act or omission they are accused of; nor shall one be put twice in jeopardy of a penalty for the same offence, whether by the Private or Public Prosecution.

**Comment by yopdog** [comment]
@KacperZajc Why do you keep closing discussions without asking? Yes, sometimes it can take a while to come to a consensus, I would also like to close this as soon as possible, but there are still a few things we have to address. So please keep this open. 

In contrast to what you said there are still some differences in the substance of the provision between your implementation and mine. I will go over them one by one:      

1)
>§V.11(3) **The Victim(s) may expressly waive the right** to institute the Private Prosecution.
§V.12(1) The Office of the Public Prosecutor shall retain the right to institute the Public Prosecution **should the Victim(s) waive, either expressly or impliedly, the right to the Private Prosecution** and give its informed and express consent.

As I said earlier, not exercising a right does NOT equal waving away a right. I would prefer if we just said that that the victim **chooses** to have his case prosecuted by the public prosecutor. This can be done in ONE provision. We don't need two provisions to say the same thing:

>The Public Prosecutor shall retain the power to prosecute on behalf of Individuals who choose to have their case prosecuted by the Public Prosecutor. 

2)
>§V.11(4) The Victim(s) shall be **deemed** to have waived the right to institute the Private Prosecution should it not be brought within **three months** since an alleged offence took place.

I still don't understand what exactly is the point of this. But I will list two problems I have with it:

 1. It takes away from the victim the right to choose whether to prosecute or not. I know §V.12(1) says that it has to be done with the victims consent, but §V.12(3) negates that by saying that all that has to happen is that the 'evidence be sufficient' AND 'the right to the Private Prosecution be waived' and the public prosecutor will be obliged to act.  

 2. Why should a right be taken away simply due to the passage of time? Imagine a case where a rape victim only manages to get the courage to sue months after the offence happened because she was too ashamed to go public about it. Why should this victim lose his/her right to private prosecution?

3)
§V.12(2) Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the inherent right to institute the Public Prosecution **on behalf of the state of the Free Republic of Liberland.**

Shouldn't it be on behalf of the victim? Secondly we should also add the proxy in this provision. My wording will be:   

>§V.12(2) Should a criminal offence leave no Victim(s) or **proxy** capable of instituting **a** Private Prosecution, the Office of the Public Prosecutor shall have the power to institute **a** Public Prosecution **on behalf of the victim**

4)
Some wording issues: 

 1. I noticed you tend to put '**the**' before private Prosecution or public prosecution. For example: "capable of instituting **the** private Prosecution" it should be "capable of instituting **a**private Prosecution"

2. I think we should use the word 'power' whenever we are talking about a government body and the word 'right' whenever it's about individuals. So for example, instede of saying the following:

>the Public Prosecutor shall have the **inherent right** to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland. 

It should be the following:

>the Public Prosecutor shall have the **power** to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.

That's it. Please address the point's I made so we can finish this topic. and move on to other things :)

**Comment by KacperZajc** [comment]
@yopdog You're right about using the word 'power' rather than 'right' here.

I dont mind using 'choose' instead of 'weaving the right' if you insist.

We need time limitation because most evidence becomes inaccessible over time (e.g. people's memory fades).

I dont see any inconsistency regarding victim's consent for prosecution - no consent, no prosecution, it's clear here.

The provision expressly states ' Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution...' so how do you want to prosecute on behalf of the victim? If we take e.g. cruelty to animals, you want to prosecute on behalf of a dog?

I substituted 'a' for all 'the'.

**Comment by yopdog** [comment]
Ok, great, thanks for reopening this :)

>We need time limitation because most evidence becomes inaccessible over time (e.g. people's memory fades).

That should be up to the courts to decide. If private prosecution is truly a right it should not have any time limit. Secondly how does substituting it with public prosecution make it any different?    

>I dont see any inconsistency regarding victim's consent for prosecution - no consent, no prosecution, it's clear here.

Try reading §V.11(4), imagine that three months have passed and then read V.12(3)

§V.11(4): After three months =  right to private prosecution waived **without consent**
V.12(3): private prosecution waived + sufficient evidence = public prosecutor under obligation to act =  Public Prosecution acts **without consent** of the victim   

As you can see there is some ambiguity (at least to me) as to whether provisions §V.11(4) and V.12(3) allow the public prosecutor to act without consent.

>The provision expressly states ' Should a criminal offence leave no Victim(s) capable of instituting the Private Prosecution...' so how do you want to prosecute on behalf of the victim? If we take e.g. cruelty to animals, you want to prosecute on behalf of a dog?

Why shouldn't you be able to do that? When the public prosecutor prosecutes, he is doing it for the victim, not for the state. It therefore makes sense to say that he is prosecuting on **behalf** of the victim. This can be done even if the victim in not alive anymore.

**Comment by Auahi** [comment]
I'm see what yopdog's saying with how the Public Prosecutor could act without consent, there should be some clause limiting this.

V.12(5) The Public Prosecutor may only act without consent in cases involving felonies.

**Comment by terrorist96** [comment]
This has spiraled way too much. It's so detailed that it belongs in a law, not in the constitution. I'm all for having public and private prosecutions, but the amount of detail is just excessive, IMO.

**Comment by terrorist96** [comment]
> §V.13(3) Should the right to Private Prosecution be waived and evidence be sufficient, the Office of the Public Prosecutor shall be under obligation to institute the Public Prosecution.

Do we want to remove the option for discretion? What if the prosecutor believes it's not in the best interest to bring the prosecution and wants to drop the charges. This language prevents that.

**Comment by KacperZajc** [comment]
•	§V.12. The Victim(s) of a criminal offence shall have the inherent right to institute the Private Prosecution of the accused.
o	§V.12(1) The Private Prosecution may be instituted by the Victim(s) in person or by Proxy on its behalf.
o	§V.12(2) Both the Victim(s) or the Proxy shall not enjoy the privileges of the Law Enforcement by virtue of pursuing prosecution.
o	§V.12(3) The Victim(s) may request the Office of the Public Prosecution to institute free-of-charge Public Prosecution on its behalf. 

•	§V.13. The Public Prosecution of the accused shall be instituted by the Office of the Public Prosecutor.
o	§V.13(1) The Office of the Public Prosecutor shall retain the power to institute the Public Prosecution should the Victim(s) expressly requested so.
o	§V.13(2) Should an alleged criminal offence leave no Victim(s) capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the power to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.
o	§V.13(3) Should the Victim(s) requested the Office of the Public Prosecution to institute the Public Prosecution and evidence be sufficient, it shall be under obligation to act.
o	§V.13(4) Should the Public Prosecution be instituted, the Victim(s) shall have the right:
o	§V.13(4)(a) to be notified about the schedule of the judicial proceedings;
o	§V.13(4)(b) to address the Criminal Court before the sentence is determined;
o	§V.13(4)(c) to be advised of release from custody or escape of the accused.

There should be no discretion regarding public prosecution where there is a victim.

**Comment by yopdog** [comment]
>o §V.13(2) Should an alleged criminal offence leave no Victim(s) or **proxy** capable of instituting the Private Prosecution, the Office of the Public Prosecutor shall have the power to institute the Public Prosecution on behalf of the state of the Free Republic of Liberland.

You should add 'proxy' into this part in case the victim has left a will specifying a proxy that would prosecute on his behalf in case he dies. This will allow the families (if mentioned in the will) to institute private prosecution on behalf of the victims should they die.  

Other than that, I have no more objections. You can close this discussion after making this last change.

**Comment by KacperZajc** [comment]
Im not 100% convinced this is a good idea but let's finish this discussion.
