### ISSUE TITLE
Chancellor unable to act

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#335]
§IV.4. The Members of the Cabinet shall among themselves elect the Vice-Chancellor with a simple majority, should the Chancellor become unable to perform one’s duties.
§IV.4(1) The inability of the Chancellor to perform one’s duties shall be declared by the Supreme Court upon the request submitted by a simple majority of all Members of the Cabinet.
§IV.4(2) The Vice-Chancellor shall perform the duties of the Chancellor until one’s return.
§IV.4(3) Should the Vice-Chancellor have doubts whether the Chancellor is able to return to one’s duties, the Chancellor shall request the Supreme Court to rule on the issue. 
§IV.4(4) Should the Chancellor be not able to return within thirty days, the Vice-Chancellor shall request the Assembly to pass the Motion of Confidence.
§IV.4(5) Should the Assembly fail to pass the Motion of Confidence with a simple majority of the overall number of Assembly Representatives, the Vice-Chancellor along with all Members of the Cabinet shall resign and the Assembly shall elect the new Chancellor in accordance with Article III.

Renumbering...

§V.10(7) The Supreme Court shall rule on the ability and inability of the Chancellor to perform one’s duties in accordance with Article IV.

**Comment by terrorist96** [comment]
> §IV.4. The Members of the Cabinet shall**,** among**st** themselves**,** elect the Vice-Chancellor with a simple majority, should the Chancellor become unable to perform one’s duties.
§IV.4(1) The inability of the Chancellor to perform one’s duties shall be declared by the Supreme Court upon ~~the~~ request ~~submitted~~ by a simple majority of all Members of the Cabinet.
§IV.4(2) The Vice-Chancellor shall perform the duties of the Chancellor until one’s return.

Unless he can't return.

> §IV.4(3) Should the ~~Vice-Chancellor have doubts whether the~~ Chancellor**'s return be in question** ~~is able to return to one’s duties~~, the **Vice-**Chancellor shall request the Supreme Court to rule on the issue.
§IV.4(4) Should the Chancellor be not able to return within thirty days, the Vice-Chancellor shall request the Assembly to pass the Motion of Confidence.
§IV.4(5) Should the Assembly fail to pass the Motion of Confidence with a simple majority of the overall number of Assembly Representatives, the Vice-Chancellor along with all Members of the Cabinet shall resign and the Assembly shall elect the new Chancellor in accordance with Article III.

I don't really like these provisions. What if the Chancellor dies? Does the Supreme Court still need to review his competency?

**Comment by KacperZajc** [comment]
what do you propose then?

**Comment by terrorist96** [comment]
Let's cover everything:

> §III.8(1) Should no Chancellor be elected for more than thirty days, the General Election shall be held within sixty days.

Does this mean the Assembly Reps will be replaced? What if the all 20 win re-election, and they still can't agree to a Chancellor? Would the ARs be replaced again?
Or does it mean the citizens voting will get to select the Chancellor?

> §III.8(2) The Assembly shall have the power to impeach the Chancellor along with the Cabinet by passing the Constructive Motion of No Confidence with a simple majority vote of the overall number of Assembly Representatives provided there is a majority for a prospective successor.
§III.8(3) On the first meeting after the General Election, the ~~Chancellor along with the Cabinet shall request the~~ Assembly **shall** ~~to~~ vote on the Motion of Confidence.
§III.8(4) Should the Assembly fail to pass the Motion of Confidence with a simple majority vote of the overall number of Assembly Representatives, the Chancellor along with the Cabinet shall resign.

There should be only one vote. If choosing/keeping the Chancellor and impeaching the Chancellor both require only 51% vote, then there's no sense in calling it two names. We should change it so that there's a general vote for Chancellor at the beginning of every Assembly (every 4 years). If no candidate obtains 51%, then there can be a runoff election between the top two candidates.

If the Assembly wants to impeach, it should require more than simple majority (60% or 66% or 75%) since the Chancellor can simply be replaced with a simple majority next election cycle if needed. This helps keep the government more stable and running instead of uncertain and shoddy. When the Chancellor is impeached, the Vice-Chancellor should be put into power until the next Election, where a new one can be picked again. Or not. I'm just throwing out ideas.

III.8 and IV.4 should be merged into one section.

**Comment by KacperZajc** [comment]
§III.4. Should the Chancellor become unable to perform one’s duties, the Members of the Cabinet shall amongst themselves elect the Vice-Chancellor with a simple majority.
§III.4(1) The inability of the Chancellor to perform one’s duties shall be declared by the Supreme Court upon request by a simple majority of all Members of the Cabinet.
§III.4(2) The Vice-Chancellor shall perform the duties of the Chancellor until one’s return or the resignation upon the Assembly’s failure to pass a Motion of Confidence. 
§III.4(3) Should the Chancellor's ability to return be in question, the Vice-Chancellor shall request the Supreme Court to rule on the issue.
§III.4(4) Should the Chancellor be not able to return within thirty days, the Vice-Chancellor shall request the Assembly to pass the Motion of Confidence.
§III.4(5) Should the Assembly fail to pass the Motion of Confidence with a simple majority of the overall number of Assembly Representatives, the Vice-Chancellor along with all Members of the Cabinet shall cease to hold their office and the Assembly shall elect the new Chancellor in accordance with Article II.

The death of the Chancellor should also be confirmed by the Supreme Court.
If no new Chancellor is elected then a General Election will be held so that the new majority of the Assembly can elect the new Chancellor.
A Motion of Confidence on the first meeting approves the current Chancellor but if the Vice Chancellor replaces him or her for a longer period there should be another vote to confirm the that the approval for that Cabinet is still there.
Electing a Chancellor should be done with a simple majority because otherwise it might be too difficult for the Assembly to do so and no Cabinet would be formed for a long time.

requires renumbering of #345

**Comment by terrorist96** [comment]
> §III.4. Should the Chancellor become unable to perform one’s duties, the Members of the Cabinet shall**,** amongst themselves**,** elect the Vice-Chancellor with a simple majority.

Added commas.

> §III.4(2) The Vice-Chancellor shall perform the duties of the Chancellor until one’s return or ~~the~~ resignation upon the Assembly’s failure to pass a Motion of Confidence. 

Delete extra space after period too.

> §III.4(4) Should the Chancellor ~~be~~ not **be** able to return within thirty days, the Vice-Chancellor shall request the Assembly to pass the Motion of Confidence.

**Comment by KacperZajc** [comment]
OK
I am also adding §IV.10(8) see above

**Comment by terrorist96** [comment]
> §IV.10(8) The Supreme Court shall have inherent jurisdiction to declare the Chancellor**'s ability (or competence)** ~~able or unable~~ to perform his or her duties upon request by a simple majority of all Members of the Cabinet or the Vice-Chancellor.
