### ISSUE TITLE
unpleasant changes

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#351]
Those are not up to me, nor am I in favour of their implementation.
The President decided he wants to go with national currency (Merits) with the right to use any currency in private transactions.
The need for export/import limitation we discussed earlier. 

Feel free to propose different wording but those provisions will be added at the end.

§I.65. The borders of the Free Republic of Liberland shall not constitute a part of the territory of the Free Republic of Liberland thereby nothing in this Constitution shall prevent the Assembly from regulating the passage of Persons and goods entering or leaving the Free Republic of Liberland.

§I.47. No law shall abridge the right to issue and/or use any commodity or item as currency in transactions not involving any body of the Public Administration unless either party to the transaction is legally prohibited to possess such item or commodity.

**Comment by yopdog** [comment]
Could you please explain the reasons behind these changes?

**Comment by KacperZajc** [comment]
As we have already discussed, due to certain international treaties (both on international cooperation as to security and potential membership in any economic area) the flow of goods and people must be subject to the control of the government.

As to a currency, it's just a decision made by the President.

I have no further information and Im not defending these changes. 
It's just we have to do.

**Comment by yopdog** [comment]
Well, in that case, I really think you should get more information. How do you expect me to support these changes if you are unable to provide the basic information and reasons behind them?

For one, you are not giving any information about what is it specifically that we need to limit from being imported or exported. What if international treaties only have limits on exports? In that case why would we need to give the assembly power to regulate imports?  Furthermore, maybe, instead of giving the assembly broad powers to regulate exports, we could just give it the power to specifically ban exporting goods to countries where they are deemed illegal. Regardless, we need more information in order to make a provision regarding imports/exports.  

As for a national currency, would this entail that the land fee must be paid for with the national currency? If that's the case, it won't be a voluntary currency, but something everyone has to use if they wish to live in the country. Furthermore, a national currency would not work in the early stages of Liberland since the currency would be worthless. In short, it would complicate things and I just don't see any reason for the state to be involved in this. Maybe there is a good reason, but I have no way of knowing since it's 'just a decision made by the President' so I'm left with no reason to support it.

**Comment by KacperZajc** [comment]
@yopdog Let's get something straight here. Do not try to convince me a national currency is a bad idea. I was asked to change this provision and I will do so. Please respect that.

**Comment by yopdog** [comment]
Listen, you can go ahead with these changes, I can't stop you. it's just that I was under the impression that we debate things before we implement new changes. At the very least, changes should be supported by some type of argument and relevant information. If your approach to the constitution is 'what the president says goes no questions asked' then no, I can't respect that. I understand Vít Jedlička is the central figure representing the whole project, but that doesn't mean we need to accept every change he wants to make without question. it's not his own private country!

My suggestion would be that you put all this in the "To be dealt with later" until you can get some information and basic arguments for these changes. Again, just a suggestion.

**Comment by KacperZajc** [comment]
I talked to the President, we can go with this version:

§I.47. No law shall abridge the right to issue and/or use any commodity or item as currency in any transaction unless any party to the transaction in legally prohibited from possessing such commodity or currency.

Consequently, even payments to the PA can be made in any currency.

We'll deal with the borders restrictions later.

**Comment by terrorist96** [comment]
> §I.47. No law shall abridge the right to issue and/or use any commodity or item as currency in any transaction unless any party to the transaction ~~in~~ **is** legally prohibited from possessing such commodity or item.

**Comment by yopdog** [comment]
>Consequently, even payments to the PA can be made in any currency.

I don't see how that necessarily follows. You should find a way to make that point more clear in the provision.

**Comment by yopdog** [comment]
§I.47. No law shall abridge the right to issue and/or use any commodity or item as currency **or provide any incentive in that respect** unless any party to the transaction is legally prohibited from possessing such commodity or item. 

??

**Comment by KacperZajc** [comment]
sounds good to me :)
