### ISSUE TITLE
Polycentric Republic - An alternative and better path to a free society

### ISSUE THREAD

**Issue by yopdog** [liberland/constitution#357]
For a long time, I've had mixed feelings about the current approach we are taking with the constitution and the government structure in general. I don't believe the system we are currently building will be effective at limiting government power since at its core the government in Liberland is structured like most modern governments today and is heavily based on the US constitution, which looking back, wasn't very successful at keeping the government limited to its proper role. Furthermore, the constitution has gotten way to long and messy. Instead of it being about the core and basic values, it has become a document of laws that goes into specifics that should really be left to the citizens to decide. Ultimately I believe our approach is flawed. 

I know this may sound crazy, but I'm going to suggest that we change the structure of the government to a polycentric one similar to the libertarian constitution draft written by @cpacia (http://tinyurl.com/q9agztt). I think his idea of having the government consist of separate Cantons is superior to any system we have today and will be much more effective at limiting government power. Before I go into everything in more detail, I would like to clarify more on what I think is wrong with our current approach: 

**1) The supreme court is too powerful -** In an attempt to limit the power of the majority over the rights on the individual we have given the  supreme court too much power by letting them declare what's constitutional and what isn't. This immense power the supreme court has can just as easily be used to manufacture phony interpretations of the constitution as the US supreme court did with the Commerce Clause. We are not going to ensure a free country by relying on five individuals to decide what's right and what isn't. The supreme court is not going to be run by angels.       

**2) We rely too much on what's written -** We are focusing too much on trying to limit the government through words alone, but we have to remember that the constitution is simply a piece of paper that those in power are supposed to follow. If the government chooses not to follow the constitution there will be nothing to stop it since the government is also its own enforcer. In other words, it acts as their OWN police! We therefore can't put all our faith in the constitution since it has no power of enforcement on its own. If we are serious about preserving the values of the constitution, we can't rely on self-policing. We need to decentralize!

**3) A centralized government cannot be fully libertarian -** There is no other way of putting it. A centralized government is a monopoly, and it's a monopoly on the most essential services in society. In order to maintain it's monopoly a centralized government must use force against the individual in the form of taxes, or in our case a "Land fee". In a centralized government, there is no freedom of association. you must support the government even if it's not following the constitution. The polycentric model solves this problem quite well by giving people the option to choose who they support. It removes the necessity of taxes and opens up the option to competition in essential services.           

**4) We don't trust the government we are creating! -** All the time, we trying to think of new ways to limit and control the Public Administration as if it's some type of vicious monster that given the slightest chance would become totalitarian and oppressive. Our current strategy is to put as many laws as we can into the constitution so we can 'lock' the country into those laws for as long as possible. If we trust the government and the people so little, why even give them a voice? Why not just have a constitutional dictatorship? As I hope you can see, we need to change our whole approach. Instead of creating a government we don't trust and have it be severely restricted by our constitution, we need to create a government that we believe will defend and preserve the constitution and be structured in such a way as to prevent abuses of power.                  

It is for those reasons that I believe we should be focusing much more on the structure of the government than simply writing on a piece of paper what the government can and cannot do. If all that was needed to limit a government was a well-written piece of paper, we could just have a monarch ruling over Liberland. As I'm sure you can see, a constitution isn't enough. The structure is important!

I therefore suggest we rethink our approach to government and implement a system of decentralized power. A polycentric system is something that has been brought up here before and has been popular among other contributors here. The fact the "**polycentric law**" discussion has been left open, suggests to me that @KacperZajc might have found something interesting in it. 

What I'm hoping to bring here is a framework for a polycentric system of law should we choose to go down this path. I have put together a slideshow in google docs that goes into detail on how such a system may work and summarizes the basic idea behind the polycentric approach. It can be viewed here: https://docs.google.com/presentation/d/1BjTAWv98xOhRME-Wr77b0-P7Rxa3Bj4A3CuYDIex7mw/edit?usp=sharing 
![polycentric republic](https://cloud.githubusercontent.com/assets/5955538/10710713/05a78a9e-7a6e-11e5-8495-27d04234fd36.png)

The polycentric system has many advantages over a centralized government. It solves the problem of trying to control a monopoly that has been given ultimate power. It creates better protection for individual rights and most importantly it has no single point of failure as a centralized government has. The existence of multiple Cantons each having their own power will be considerably more effective at protecting the constitution for the simple reason that the Cantons will be able to police one another.    

Having said that, If we choose NOT to go with this approach It should be because we believe that the polycentric system is flawed and not because it's too late or too big of a change. As far as I can tell Liberland is still a long time away from being recognized. If we want to make big changes now is a good time. 

Any thoughts? :)

**Comment by terrorist96** [comment]
Everything mentioned here is good and all, but my issue is with space constraints. How small would the cantons be? Would there be cities and towns within the cantons? Would they be incorporated and independent or unincorporated? How well defined would the boundaries between cantons be? Would each Canton have its own legislative/judicial/executive body?

**Comment by yopdog** [comment]
Sorry, I guess I didn't explain that part too well. My idea is that the cantons will operate in the same area and decision making concerning laws will be made in the United Cantons Assembly, a bit like like the assembly we have now. In a nutshell, what I'm proposing is centralized decision-making and decentralized enforcement of laws. In the slideshow, I go into everything in detail, so I suggest you take a look at it if you want to know more.

**Comment by terrorist96** [comment]
Wouldn't decentralized enforcement actually lead to a larger government overall? Because there'd be more people performing the same functions. I'm not opposed to your suggestion, but it's a big change from where we are right now. I'm guessing @KacperZajc would have to show this to Vit and for him to approve of it.

**Comment by yopdog** [comment]
A big government as I have always understood it, is a government that is constantly intruding into people's lives and is over-regulating the economy, not necessarily one that is run by many people. If your concern is that this new system would mean more bureaucracy, then rest assured that will not be the case. We are not talking about a single institution, but about many institutions which will compete with one another. Just like in the free market, more competition will not equal bureaucracy.

**Comment by KacperZajc** [comment]
I find the idea of polycentric laws very interesting but mainly for academic purposes (and for these reasons I left this issue open).

I do not think, however, it would be suitable for Liberland for following reasons:

1) It creates extensive bureaucracy - the canton system creates 2 separate tiers of government, one of which can multiply indefinitely. This will result in more politicians, more civil servants and more administrative expenses. It is not desirable especially for such a small state as Liberland.

2) It requires extremely complex legal system - constitutional law of the canton system would be more complicated than law of a federal republic. The basic advantage of a unitary state is the idea that any person can comprehend the nature of the government on the basis of one simple document.

3) It multiplies laws - there would be 2 sets of laws with complicated relationship between them. The less laws the better. The canton system entails more, not less, laws. Any person should be able to understand what rights she or he has and the canton system makes it definitely more difficult as there would be 2 sources to search for those rights.

4) The Supreme Court of FRL has a safety valve that SCOUT lacks - the possibility to impeach Justices in a referendum. It is true its position is powerful but nevertheless it is subject to control of citizens therefore not omnipotent. 

5) If you assume the government will not follow the law, then there is no good legal system to be introduced at all. This is a clear fallacy. What is more, we expressly provide for the possibility of revolution if this happens. There is no other way you can deal with that.

6) Of course we should not trust the government we are creating! Moreover, we should not trust ourselves in our capacity as authors of this Constitution! What we are creating is a monster and there is no way you can create a government which will not be one. This is a very naive belief. We should be cautious and we should include safeguards wherever possible. It might be the first time I see a libertarian who wants to trust the government. It is an inherent characteristic of every person in power that he or she will seek ways to expand that power.

Finally, I think it is offensive to every person here to say that we based our Constitution on the US Constitution. Certainly, we were inspired, however, what we have created encompasses various legal concepts, and the US Constitution is only one of them.

Nevertheless I appreciate your involvement and passion here. I think it is a very interesting concept and worth discussing. However, I really do not believe it is something 'better' than the current draft.

**Comment by yopdog** [comment]
1,2,3) It seems to me you didn't completely understand my proposal. Most of my vision is layed out in the slideshow, not on my post. 

In the slideshow, I explain that there would be ONE system of laws which will be decided on in the United Cantons Assembly. The cantons will be akin to political parties, except for the fact that they would also act as law enforcement. So as you can see, it will not make things more complicated. In the constitution, we would only have to deal with the  workings of the United Cantons Assembly. The cantons, on the other hand, are completely independent and would organize their own internal affairs, so we don't need to worry about. This system of cantons will not be more bureaucratic just like the 'system' of supermarkets near you isn't making the food business more bureaucratic. Competition ≠ Bureaucracy.

4) You are still relying on a centralized institution to defend the constitution. The fact that you can impeach Justices might have its benefits, but it is not ideal. In democracy, you can choose who runs the government, has that stopped governments from becoming big and intrusive? Again, I'm not saying impeaching won't work, I just think cantons will provide better protection.   

5) You cannot look at revolutions as a solution to controlling the government. Revolutions will happen whether they are legal or not, and when they happen they will be extremely costly and cause a huge amount of disorder. We should avoid them as much as possible. What I think is so good with my proposal is that you don't have to start a revolution. you could just switch a canton. it's like doing a mini revolution minus the destroying the economy. 

6) What I'm trying to say here is that a constitution isn't enough. The government, as we have seen in the United States, can always find a way to grow. It can start interpreting the constitution in ways that give it more power and it can be very hard to stop it. The average citizen will find it very difficult to do anything about it. Of course, he can try voting or start a referendum, but those things either lead to very little change or are extremely time-consuming and expensive. Most people would choose to do nothing. This is not theory, it's what we see today happening all the time. With cantons, people could just switch to another canton like they switch their phone provider. This is why I believe it will work much better than what we have now. This is what I mean by making a government we can trust.      

>Finally, I think it is offensive to every person here to say that we based our Constitution on the US Constitution. Certainly, we were inspired, however, what we have created encompasses various legal concepts, and the US Constitution is only one of them.     

What I meant is that the Constitution is based on the way modern government function which includes the US Constitution. I agree 'inspired' would have been a better word to use :)

**Comment by cpacia** [comment]
> 1) It creates extensive bureaucracy - the canton system creates 2 separate tiers of government, one of which can multiply indefinitely. This will result in more politicians, more civil servants and more administrative expenses. It is not desirable especially for such a small state as Liberland.

That's kind of like saying we can't have a market in shoes because it's too wasteful to have duplicate shoe factories producing different styles. We need to have a single shoe manufacture to cut down on overhead. Of course the problem with that reasoning is easy to spot, but it also assumes centralized governments behave more efficiently and have less bureaucracy than competitive markets. Which isn't true.

> 2) It requires extremely complex legal system - constitutional law of the canton system would be more complicated than law of a federal republic. The basic advantage of a unitary state is the idea that any person can comprehend the nature of the government on the basis of one simple document.

That again assumes a centralized government is capable of producing concise, intelligible laws. History has proven that to not be the case. In fact we don't have a single example of that ever happening. Also, the common law (on which any inter-canton disputes would have to be adjudicated) is as close to common sense as you can get. Most people already know the common law even if they have never studied it.

> 3) It multiplies laws - there would be 2 sets of laws with complicated relationship between them. The less laws the better. The canton system entails more, not less, laws. Any person should be able to understand what rights she or he has and the canton system makes it definitely more difficult as there would be 2 sources to search for those rights.

The rights would be the same for everyone and enumerated in the constitution. The only way you could end up with complicated-to-understand canton laws is if you voluntarily chose that canton. Presumable people will chose a canton will few, easy-to-understand laws if that's what they prefer. 

> 4) The Supreme Court of FRL has a safety valve that SCOUT lacks - the possibility to impeach Justices in a referendum. It is true its position is powerful but nevertheless it is subject to control of citizens therefore not omnipotent.

That's a very weak safety valve. In some states here in the US, citizens have the ability to recall a governor or elected representatives and they almost never do it. It's a tyranny of the majority problem.

> 5) If you assume the government will not follow the law, then there is no good legal system to be introduced at all. This is a clear fallacy. What is more, we expressly provide for the possibility of revolution if this happens. There is no other way you can deal with that.

Competition can provide a check and balance that monopoly cannot. The reason a monopoly government can get away with not following the law (the constitution in this case) is because there is no one people can turn to when it isn't followed. 

Also, we have a right of revolution in the New Hampshire state constitution and yet nobody has even remote suggested overthrowing the state government. 

6) Of course we should not trust the government we are creating! Moreover, we should not trust ourselves in our capacity as authors of this Constitution! What we are creating is a monster and there is no way you can create a government which will not be one. This is a very naive belief. We should be cautious and we should include safeguards wherever possible. It might be the first time I see a libertarian who wants to trust the government. It is an inherent characteristic of every person in power that he or she will seek ways to expand that power.

That's why you need competition to keep that inherent characteristic of each person in check.

7) The canton system does not necessarily mean more limited government - by subjecting all state power to one document we can ensure we limited its powers as much as possible whereas if we allow double legal system, we cannot control what direction one of its tiers might develop.

Centralize for liberty!

**Comment by saintego** [comment]
I really like the idea of Polycentric Republic. It's simple idea and I think it can also simplify constitution. It is at the border of minarchism and anarchism, because once you can have your own canton, you don't need the rest of state. 
Btw, you don't need "Members of the UCA will be comprised of representatives sent by each Canton. The number of representatives sent by each Canton will be determined by its own membership size relative to the other Cantons." It is enough to have different weight of vote for every representative.
What I'm missing there is possibility for citizen to be part of different cantons for different purposes and also to mention possibility of outsourcing some services of cantons to other one, or have some temporary alliances in the of respecting some law by majority of cantons, but not to enforce it at the rest. 
I just don't know if it is not too free for being able to be ever accepted internationally, because canton don't need to respect some internationally enforced laws. But that can be solved with bit crippling Polycentric Republic idea.
I think there will be at least some decentralisation at Liberland at the end, with some private security and some set of private rules besides the official one. The more space left by state the bigger natural decentralization will be crated by private sector. But I think we are throwing out probably most important security valve from Swiss Constitution and it is veto right of Cantons. Why not to have at least some legal right to veto the law from Cantons that are big enough or at least some kind of contracted representatives(to have some kind of fast way of referendum). I know Vit is telling that Liberland is small enough to have cantons, but why not to take at least that security valve from it. 
I think that Liberland constitution can be at least inspired from Polycentric Republic in variety of ways. Few examples
1. To base constitution on polycentric idea with some initial law set and "force" them by law to respect it. 
2. We can have elected members of assembly and right to execute law also by government(if cantons failed). Cantons will have right to execute law either(if state is not doing it) and will have veto right(if they are big enough).  
3. To have representatives with actual contract with citizens that will have veto right if they represent for example at least 10% of population. Representatives will work as some big government insurance company, or some quick referendum.

**Comment by KacperZajc** [comment]
“The cantons, on the other hand, are completely independent and would organize their own internal affairs, so we don't need to worry about them."

That is exactly what worries me. Organising internal affairs means producing laws and regulations, every canton on its own. More laws, less freedom.

"This system of cantons will not be more bureaucratic just like the 'system' of supermarkets near you isn't making the food business more bureaucratic. Competition ≠ Bureaucracy.”

I don’t think so. Governmental agencies compete with one another only in attempt to grab more power and get even bigger. The comparison is unjustified. 

“The government, as we have seen in the United States, can always find a way to grow.”

If the central government is able to find a way to grow, multiple governments will only grow more quickly.

“That again assumes a centralized government is capable of producing concise, intelligible laws. History has proven that to not be the case. In fact we don't have a single example of that ever happening. Also, the common law (on which any inter-canton disputes would have to be adjudicated) is as close to common sense as you can get. Most people already know the common law even if they have never studied it.”

Oh no, no, no. Common law has many merits but trust me, average person does NO know it on the basis on the instinct alone. Anyway, common law is not the issue here. Of course the central government might produce unintelligible laws, but the point is that with two sets of laws (at central and canton level) what becomes important are matters of jurisdiction, interrelation and conflict of laws etc. This immensely complicates the law and makes it impossible for a layman to comprehend it even if those laws separately are simple.

Creating multiple governments in a such a small state as Liberland is just madness.

**Comment by yopdog** [comment]
You still don't seem to understand what it is I am proposing. Seriously, have you read the slideshow??

My proposal does NOT have a two-tier system of laws. The cantons will NOT have their own separate laws since they are non-geographical. I agree with you that it would be a mess if every Canton had it's own laws. In fact, it wouldn't even work since you can't have multiple systems of law in the same place! It's for this reason that we have the *United Cantons Assembly* so the Cantons can reach a consensus on the laws of the country. As you should be able to see, It's not a complicated system. It will have one set of laws for the entire country. The only difference would be that the *power* of the government to enforce those laws would be decentralized through the Cantons. 

>I don’t think so. Governmental agencies compete with one another only in attempt to grab more power and get even bigger. The comparison is unjustified. 

Cantons are not like governments. Thay can't tax and they don't have a monopoly on anything. In fact, Cantons won't have any more power then a private business would. Thay can even go bankrupt if they become unpopular. So the comparison is unjustified :)

**Comment by KacperZajc** [comment]
In that case, Im afraid you have to elaborate on this slideshow :)
Also, I get the feeling that @cpacia has multiple legal systems in mind.

**Comment by yopdog** [comment]
Ok, fair enough. I can't speak for what exactly @cpacia wants, but my idea is that we have a government consisting of *Cantons*. The *Cantons* will be non-geographical and would basically act as the law enforcement in the country. Each *Canton* will be comprised out of it's members (citizens) and its job will be first and foremost be to protect the individual rights of it's members. This is very different than what we have now where you have no choice as to which institution will protect your rights. In a polycentric system, You always have this choice. 

One thing you need to understand about *Cantons* is that they will be absolutely and completely independent, just like a sovereign country. There is no institutional body above them which can 'regulate' them or impose laws on them. The *Cantons* will also raise their revenue voluntarily just like any private company would.

The question we should now ask is what happens when *Cantons* disagree with each other about the law? After all, they operate in the same area so they can't each follow their own rules without running into each other, right? This is where the *United Cantons Assembly* comes in. The UCA will exist in order to achieve consensus between the *Cantons*. This way we can have ONE set of laws in Liberland. The UCA will be a bit like the United Nations. In the UN, countries can vote about different issues concerning international laws, but those laws can only be enforced by other countries, not by the UN itself. This is precisely how I envision the UCA working. I believe that by taking the power from the top and distributing it among different institutions we can have a system that avoids the many problems we see in governments today. Those problems arising from the fact that governments are a monopoly.

And now we have the courts. My idea is that the courts under a polycentric system will be completely independent, Just like a private company. They will be in charge of their own financing and functioning. The courts will not enforce their own verdicts since that is the job of the *Cantons*. Therefore, the courts can only have their verdicts enforced if the *Cantons* are willing to recognize their legitimacy. This way we can have both a free and flexible judicial system that ensures that only good courts have their verdicts enforced as well as ensuring that there will always be an adequate supply of judicial services thanks to the market (very important!).  

So this is it basically. I believe this system will be superior and will have many advantages (which I listed in the slideshow). I know those ideas are very different than what we have now, but there seems to be quite a lot a lot of support them among the contributors here. Hopefully this makes it more clear.

**Comment by saintego** [comment]
I don't think you can have one legal system and various enforcers of law.Probably most of Cantons will have similar legal system with some small differences. You can have various legal systems even in one Canton, same as car producer is producing different cars. 
I even don't think that you need United Cantons Assembly and constitution, because problems between Cantons will be solved by courts. And this is going to be ancap ideal, which I like but... 
I think we need to have some democratic government to represent Liberland outside and to enforce some internationally needed laws inside just to look less foolish in front of other states. I think it is evil that we cannot avoid. Government can have right to punish cantons(for example removing veto right) for not enforcing some common or international law and government power can be limited by supreme court, veto right of cantons and referendum.

**Comment by KacperZajc** [comment]
Sorry but this system seems too complicated for an average citizen. It would require everyone to make a conscious choice as to the potential canton.

What is more, the system of independent cantons might be problematic at the international level.

I think my reluctance here flows from the philosophical differences between us. Your idea seems more suitable for a semi-anarcho-capitalist society whereas I consider myself a minarchist and as far as I know the President is one as well. I just dont see the superiority you keep talking about :)

**Comment by saintego** [comment]
You can limit central government to have power to enforce only law that are needed to be internationally recognized and that limit can be control by referendum, main court and veto of important cantons. There can be no canton(or state owned canton) option for people that don't want to make a conscious choice. For others there can be private cantons that must enforce state law and can enforce some private law.
More important is that even without central government, conscious choice(same as you are doing when you are buying medical care, insurance, new shoes) of canton will be done only for first generation of citizens. First cantons for kids will be probably chosen by their parents.
I understand that this is bit minarchism vs ancap discussion, but that border is not sharp and even you cannot build state based on ancap ideas, you can use some ideas to limit government.

**Comment by yopdog** [comment]
>Sorry but this system seems too complicated for an average citizen. It would require everyone to make a conscious choice as to the potential canton.

Why would choosing a canton be a complicated thing?? Don't we all make decisions in our lives such as choosing where to live and who we vote for? You are going to have to explain this one better. As far as I can tell, there is nothing too complicated about this system. You have the Cantons which act as law enforcement, and the UCA which is an institution that the Cantons use to reach a consensus on the law.  

>What is more, the system of independent cantons might be problematic at the international level 

Agreed, that's why the UCA exists. The UCA will allow the Cantons to be represented as one entity on the international stage. 

>I think my reluctance here flows from the philosophical differences between us. Your idea seems more suitable for a semi-anarcho-capitalist society whereas I consider myself a minarchist and as far as I know the President is one as well. 

I will admit that this system is inspired by the anarcho-capitalist ideal,   and so is @cpacia's constitution, but please understand that I'm not advocating anarchy here. The polycentric system is about decentralizing the institution we call the government, not getting rid of it. Yes, we need order and a way to interact with other countries and my proposal takes that into account. This system is just another way of running a society and yes, I believe it's a much better way. 

>I just dont see the superiority you keep talking about :)

Please read the "Advantages of a polycentric system" part of the slideshow. If you already have, then address the points I made there so we can have something to talk about.

**Comment by Auahi** [comment]
I'm a little late to the game, but I really like the concept. Now you said that Cantons would act as political parties or basically internally-sovereign entities... the way you put it is that these "Cantons" don't hold territory unlike that of Switzerland, is this what your going for? If so how would they police people? Police wouldn't know who's registered with which canton etc. How would they know which laws apply to which people?

**Comment by cpacia** [comment]
> the way you put it is that these "Cantons" don't hold territory unlike that of Switzerland, is this what your going for?

Yes

> If so how would they police people? Police wouldn't know who's registered with which canton etc.

Policing aught to be more about protection honestly. It's essentially a service, which you can restrict only to members of your canton. 

> How would they know which laws apply to which people?

Ideally there wouldn't be police going around arresting people or prosecutors issuing arrest warrants. Instead the victim of any crime could bring a criminal complaint against the accused (very similar to civil law suits now but expanded to criminal cases). If both are member of the same canton, the dispute could just be adjudicated in a canton court. And if there are any canton-specific laws/rules, they could be applied by the judge. If they are both members of different cantons, the two cantons could jointly decide (mostly like before disputes happen) what court will hear the case and apply what rules. Almost certainly it would be best to just default to the common law as there's really nothing wrong with it. 

But we did allow for the possibility of inter-canton disputes to be taking to a national court as a fall back.

**Comment by yopdog** [comment]
>Police wouldn't know who's registered with which canton etc. How would they know which laws apply to which people?

@Auahi, In the system that I'm proposing, there would be one system of laws for the entire country. The police will know very well which people belong to which cantons since the cantons *are* the police. 

The idea is that the Cantons will reach a consensus among themselves about the law and they would each be independent in enforcing it. 

If you want, you can read the extra slide I add following you comment :)

**Comment by Auahi** [comment]
@yopdog @cpacia I like the Idea of this system but I think without cantons having some form of jurisdiction would make things very complicated. Depending on which canton a police officer is affiliated to depends what he can enforce. I doubt that every cop would know every member of their canton.

Now Liberland could easily have upwards of 10 cantons roughly the size of vatican city this would make it far easier since laws would have a specified boundary etc...

**Comment by saintego** [comment]
I don't think that fragmentation of cantons will be so huge at the end. Same as you have one major OS, you'll have one major canton(or some common set of rules) and few others that will not differ so much. Also police don't need to be per canton. It can be outsourced to some local security service, which will respect their law. I don't think there will be any problem to tell police before they do something, which canton are you part of. Maybe It'll be common to have some signs(stickers, flags) on the border of private properties of different cantons to show you are changing jurisdiction. But this is same as choosing smoking and non-smoking bar.
Quite interesting question is who will protect foreigners or persons that are somehow without any canton.

**Comment by Auahi** [comment]
@saintego You're right that sounds more probable, with the cantons... I'd assume with the way that'd be set up that there would be "common law" like federal law, and that's what'd be applied to foreigners. Or maybe foreigners could get some type of pardon on certain things etc.

**Comment by qm3ster** [comment]
Personally, I'd prefer completely private, free-market lawmaking and law enforcement, such as [this](https://youtu.be/jTYkdEU_B4o) and [this](https://youtu.be/8kPyrq6SEL0). I believe it would be both more performant and more resilient.
However I do agree that the current area (and initial population) of Liberland is simply too small to implement any kind of competing law enforcement, and there needs to be law enforcement from the very start.
I do think the constitution is locked down tightly enough as to not create perverse incentives among the government, and so a transition to private lawmaking can realistically take place through due democratic process once there is industry, population, and stability.
