### ISSUE TITLE
"living being"

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#360]
§I.19. No Person shall be convicted of any criminal offence which has not been expressly created by an Act of the Assembly or flow from this Constitution as deemed by the Courts; all criminal offences created by Acts of the Assembly shall specify the maximum penalty they carry; no law shall criminalise any act or omission which does not directly harm any living being...

I think we need to qualify the term "living being" so that it wont be used to criminalise anything that is capable of killing flies etc.

Any ideas?

**Comment by terrorist96** [comment]
Define it so as to encompass any intelligent creature or those with the ability to feel pain (central nervous system).

**Comment by yopdog** [comment]
Good luck with that! This is the reason I am against animal rights. The moment you decide that animals have rights, you start running into these kinds of problems. Here is another one: What about growing livestock for meat? That involves a good degree of torture and that's even before they are eventually killed for our enjoyment (since we don't need meat to survive). You are not going to find a consistent philosophy as to why you can torture some animals i.e livestock, but not others i.e dogs, cats, and as to why animals have partial rights that so conveniently fit our cultural norms and economic needs.  

When it comes to animal rights you either go full on 'PETA' or accept the fact that animals have no rights. the middle ground is logically inconsistent and full of double standards. My opinion is we have rights because of the existence of a social contract between us that states that we cannot hurt one another. Since animals can't participate in a social contract with us, it makes no sense to say they have rights. So please, let's stop pretending and embrace the truth. Drop 'living being' and put 'human', it's the only thing that makes sense!

**Comment by yopdog** [comment]
@terrorist96 What about cows? Can we slaughter them? What about all the torture thay go through before?

**Comment by terrorist96** [comment]
I was dreading this debate. I'm all for slaughtering a cow for food, etc. But I have a problem with a sadist who enjoys torturing animals for no reason other than schadenfreude. I know it's logically inconsistent; I have no real principles backing it up. I think it's best if I sit this one out. 😁

**Comment by KacperZajc** [comment]
I agree with @yopdog - it is a complicated legal issue
But I also agree with @terrorist96 - I dont want to live in a country where anyone can torture his dog with impunity

We have to agree on some sensible formula here. Here is what I propose:

§I.19. No Person shall be convicted of any criminal offence which has not been expressly created by an Act of the Assembly or flow from this Constitution as deemed by the Courts; all criminal offences created by Acts of the Assembly shall specify the maximum penalty they carry; no law shall criminalise any act or omission which does not directly harm any other human being or cause unwarranted suffering to an animal capable of conscious behaviour; or gravely poisoning natural water resources, soil or air; nor shall any law criminalise any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s actions or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the work of the criminal justice system, bribery, attempting or participating in committing a criminal offence.

feel free to comment

**Comment by terrorist96** [comment]
I like the wording.

**Comment by yopdog** [comment]
>cause unwarranted suffering to an animal capable of conscious behaviour

Who is going to decide what constitutes 'unwarranted suffering'? What does that even mean?

>or gravely poisoning natural water resources, soil or air

Last I checked, water, soil, and plants don't have rights. It shouldn't be a crime *in and of it self* to pollute natural resources. The crime of polluting the environment should be derived from the fact that damages occur to people as a *result* of pollution. 

My opinion is that you should leave out any provisions which explicitly bans pollution since it could lead to victimless crimes (i.e polluting your own property). Crimes should always be based on victims!

**Comment by terrorist96** [comment]
> Who is going to decide what constitutes 'unwarranted suffering'?

The Judge presiding over the case, I presume.

**Comment by KacperZajc** [comment]
It is a point of law so it would be up to a trial judge and subject to the right of appeal to the Supreme Court.

We can drop environmental issues for now but I dont think we can deal with those solely on the basis of property rights. How do treat releasing poisonous substance to the Danube river (which is international waterway)?

**Comment by terrorist96** [comment]
> How do treat releasing poisonous substance to the Danube river (which is international waterway)?

That is probably covered by some international treaties, I'd imagine.

**Comment by KacperZajc** [comment]
but international treaties do not create criminal offences (are not directly enforceable) under our Constitution unless separate Act of Assembly is passed in this respect, that's the point

**Comment by yopdog** [comment]
>"It is a point of law so it would be up to a trial judge and subject to the right of appeal to the Supreme Court."

>"The Judge presiding over the case, I presume."

You cannot leave these types of decisions for judges to make! How do you think a judge would go about deciding whether a certain treatment of animals is 'unwarranted suffering'? Based on what?? you would just be turning the judges into lawmakers. What's more, different judges would probably reach different conclusions based on their own private views on ethics, so the supreme court would probably be needed to make the final decision, in which case we would have an oligarchy of five making the law.      

>How do treat releasing poisonous substance to the Danube river (which is international waterway)?

That's a good question. One solution is for the courts in Liberland to recognize other countries as legal personalities capable of engaging in tort law. So if someone pollutes the Danube, other countries can directly sue that individual through the legal system in Liberland.

**Comment by KacperZajc** [comment]
Point I

As far as I understand you are a big fan of common law and this is EXACTLY how the doctrine of precedent and common law in general works. Higher courts determine what 'unwarranted suffering' is and there is no possibility of interpreting it differently by every judge. The Supreme Court's interpretation will be binding. This is how it works in all legal systems.

Point II

Interesting idea. It might as well be the state of Liberland bringing a claim before a domestic court. However, Im not sure whether mere tortuous liability is sufficient in that case. Anyway let's drop the environmental issues for now.
