### ISSUE TITLE
Insider trading 

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#363]
How could this be handled? Will we adopt a hands off approach like for monopolies or have laws against insider trading? If so, under what enumerated power could it be legislated?

**Comment by KacperZajc** [comment]
That's a good question. Shouldnt insider trading be a civil wrong rather than a criminal offence?

**Comment by terrorist96** [comment]
I don't know. How do we define civil wrongs? The legislature doesn't seem to have the power to create 'civil wrongs', does it? I think it could be encompassed in any laws against fraud.

**Comment by KacperZajc** [comment]
§II.7(6) to establish rules regarding peaceful coexistence of Persons and security of their Property and Rights;

**Comment by yopdog** [comment]
This entirely depends on the contract! Insider trading in and of itself does not violate any rights *unless* it constitutes a violation of a contract. This shouldn't be complicated to understand. If companies want to make their stock appealing to investors they can declare that those who have access to insider information would not be allowed to trade that stock. This would make them legally bound to their word. Regardless, it depends on what has been agreed between consenting individuals. 

Food for thought, straight out of Wikipedia:   
>**Arguments for legalizing insider trading**
Some economists and legal scholars (such as Henry Manne, Milton Friedman, Thomas Sowell, Daniel Fischel, and Frank H. Easterbrook) have argued that laws against insider trading should be repealed. They claim that insider trading based on material nonpublic information benefits investors, in general, by more quickly introducing new information into the market.[33]
Friedman, laureate of the Nobel Memorial Prize in Economics, said: "You want more insider trading, not less. You want to give the people most likely to have knowledge about deficiencies of the company an incentive to make the public aware of that." Friedman did not believe that the trader should be required to make his trade known to the public, because the buying or selling pressure itself is information for the market.[5]:591–7
Other critics argue that insider trading is a victimless act: a willing buyer and a willing seller agree to trade property which the seller rightfully owns, with no prior contract (according to this view) having been made between the parties to refrain from trading if there is asymmetric information. The Atlantic has described the process as "arguably the closest thing that modern finance has to a victimless crime".[34]
Legalization advocates also question why "trading" where one party has more information than the other is legal in other markets, such as real estate, but not in the stock market. For example, if a geologist knows there is a high likelihood of the discovery of petroleum under Farmer Smith's land, he may be entitled to make Smith an offer for the land, and buy it, without first telling Farmer Smith of the geological data.[2] Nevertheless, circumstances can occur when the geologist would be committing fraud if, because he owes a duty to the farmer, he did not disclose the information; for example, if he had been hired by Farmer Smith to assess the geology of the farm.
Advocates of legalization make free speech arguments. Punishment for communicating about a development pertinent to the next day's stock price might seem an act of censorship.[35] If the information being conveyed is proprietary information and the corporate insider has contracted to not expose it, he has no more right to communicate it than he would to tell others about the company's confidential new product designs, formulas, or bank account passwords.
Some authors have used these arguments to propose legalizing insider trading on negative information (but not on positive information). Since negative information is often withheld from the market, trading on such information has a higher value for the market than trading on positive information.[36][37]
There are very limited laws against "insider trading" in the commodities markets if, for no other reason than that the concept of an "insider" is not immediately analogous to commodities themselves (corn, wheat, steel, etc.). However, analogous activities such as front running are illegal under US commodity and futures trading laws. For example, a commodity broker can be charged with fraud by receiving a large purchase order from a client (one likely to affect the price of that commodity) and then purchasing that commodity before executing the client's order to benefit from the anticipated price increase.

**Comment by KacperZajc** [comment]
Yeah I agree with @yopdog. It is a matter of contract, potentially tort but not criminal law.
