### ISSUE TITLE
Consent of the governed

### ISSUE THREAD

**Issue by joshmh** [liberland/constitution#40]
This, for me, is the heart of the constitution. The [latest draft](https://github.com/liberland/constitution/pull/39) reads:

> We ... do ordain and establish the Constitution of the Free Republic of Liberland, as its supreme law, deriving its just authority **from the consent of the governed and nothing else**.

That's a very powerful statement *if* it means that the government only has power over an individual if that person has explicitly consented to the authority. If it doesn't mean that, it strikes me as empty rhetoric of the kind that makes existing constitution nearly worthless.

So let's talk about this, the whole exercise rests upon the answer.

1. Does *consent* mean that the government can only coerce me if I have explicitly become a citizen of my own free will? 

2. If so, can I withdraw my consent at any time? Can I live in Liberland while withholding consent to be ruled by the government?

3. If, on the other hand, *consent* doesn't mean explicit consent, then what does it mean? Does it mean that by living in Liberland I am implicitly consenting to everything the people in government want to do? That's essentially how it seems to be viewed today.  

4. If this means explicit consent, but I can live in Liberland without consenting, then what if I don't consent to the government and then rob someone's home. Is the government allowed to do anything to me? It would appear that any coercion against me would violate this interpretation of the constitution.

I'd love to hear others' thoughts on this.

**Comment by KacperZajc** [comment]
As I wrote it I assumed that it meant that everyone who lived within the territory of Liberland consented - if you do not consent move out. I dont see any other way to put this sentence into practice,

Btw, what do you think about the whole preamble as it sounds now?

**Comment by cpacia** [comment]
Your answer still suffers from one of the major philosophical problems that everyone else has encountered with that statement. If liberland (or any country) was in fact private property owned by a single individual, then it would be appropriate to say move or get out, because the owner has a right to determine the rules of his property. 

Modern states (either implicitly or explicitly) claim ownership of their territories despite the fact that they haven't done anything that most people would agree is needed to confer ownership. They did not 'homestead' the land in the Lockean sense nor was it purchased from any legitimate owner. They either arbitrarily claim the right to rule over a preexisting population or declare large swaths of empty land their property without having done any actual homesteading. 

Maybe we could say Vit is owner of the the 3 sq miles of Liberland and that's why he can say, "if you don't like the rules, [you can always leave](https://www.youtube.com/watch?v=fasTSY-dB-s)." But it's hard to see how he has any just claim over the land either. No actual homesteading has taken place. 

What Josh is getting at above is should the government of liberland be treated like a club, with it only  being binding on members? If we take the view that liberland is not anyone's private property (which I think is correct), this would be the most appropriate way to think about the government. 

That does not mean that people who have not consented can get away with criminal activity. Crimes against person and property aught to be punished regardless of whether the criminal consents to the punishment. It would, however, imply that those who have not consented could not be forced to do things with their property (such as pay taxes) if the legislature passes a law since that law would only be binding on actual members. 

Several years ago I wrote a draft of a libertarian constitution... found (here)[https://chrispacia.wordpress.com/2013/09/16/a-new-libertarian-constitution/] based on the amount of text from my constitution that was copied and pasted into this one (not sure by whom) I don't think it's a stretch to say that it was, at least part of, the inspiration for this one. 

The phrase:
> We ... do ordain and establish the Constitution of the Free Republic of Liberland, as its supreme law, deriving its just authority from the consent of the governed and nothing else.
was taken from the preamble of my constitution. They were put there because the constitution was to be a valid social contract (as opposed to the hypothetical social contract that socialist like to take out). As a valid contract, it would only be binding on those who have actually signed it. Only signers (the citizens) would be liable for taxes and would be requires to follow any laws that go above and beyond respecting other people's person and property.

**Comment by joshmh** [comment]
I commented separately in the other issue: https://github.com/liberland/constitution/pull/39

I think it's disingenuous to use *consent* in that way, even though it has a tradition in political philosophy. According to the dictionary, consent means, "to give permission for something to happen." Since when does living somewhere mean you're giving permission for something to happen? What if I live in Liberland and explicitly proclaim that I do not give my consent?

Who are we, just ordinary people writing down some words, to claim that all people, for all time, who choose to live in that swath of land, must agree with everything we say or move from their homes? What possible philosophy could give us that authority? We would never go to our neighbors right now and tell them that, so what's special about this situation?

This brilliant video sums it up nicely: https://www.youtube.com/watch?v=ngpsJKQR_ZE

I know I originally asked for the consent change, but after thinking about it more, it no longer makes sense to me, unless the government truly has no coercive authority over non-consenters.

I see two possible resolutions to this problem:

1. Reconsider the polycentric cantons framework of @cpacia's [constitition](https://chrispacia.wordpress.com/2013/09/16/a-new-libertarian-constitution/comment-page-1/). Then, each individual would be explicitly consenting to a canton. Those who do not consent to any canton are not guaranteed any rights, and may be coerced if they interfere with individuals who are members of a canton.

2. Change the wording:

> We ... do ordain and establish the Constitution of the Free Republic of Liberland, attempting a harmonious consensus for the benefit of all those seeking their home in this place.

**Comment by KacperZajc** [comment]
Inasmuch as I like your theoretical approach @cpacia I dont see how would it be possible to distinguish between people consenting and having rights and those who dont consent and have neither rights nor duties.

We cant produce an instrument which would be overcomplicated - quite the opposite. From the start I meant to write as simple as it gets so that ordinary people will be able to understand the rights they have against the Government.  

I think the only real solution here is to change the wording as proposed by @joshmh.
I changed it in the first place upon his request, we can change to what he proposes now.

**Comment by joshmh** [comment]
> From the start I meant to write as simple as it gets so that ordinary people will be able to understand the rights they have against the Government.

Very well put, I'm in complete agreement.

I don't agree that @cpacia's cantons idea is more complex than the current version. Stated simply, it just means that citizens are free to choose their own canton, much like citizens in the US are free to choose their own state. There are three key differences, all easy to comprehend:

1. You have to move to another place to change your state, you can change your canton without having to move.

2. The federal government has vast powers, the Public Authority would have limited powers. In fact, the Public Authority would have no powers over individuals, thus this truly is a system in which authority is granted by explicit consent.

3. It is very easy to found a new canton.

**Comment by tinkyholloway** [comment]
I like the idea of the polycentic cantons. Some questions:

1) why wouldn't they each just turn into social utopian paradises as they each try to out bid each other for members by providing 'free stuff'? That may be abhorrent to founding members, but our kids and their kids will forget about freedom and be tempted by tne dark side of social progressivism.

2) how might disputes involving parties of different cantons (and different rules) be handled. Would disputes organisations be outside of cantons? What rules will they apply?

**Comment by joshmh** [comment]
1. Cantons have to raise their own taxes. Since one can move so freely between cantons and since it's easy to start a new one, these are more like membership dues. The more services a canton supplies, the higher the taxes will have to be. This is analogous to insurance companies.

2. Good question. There's a whole section on that in @cpacia's [constitution](https://chrispacia.files.wordpress.com/2013/09/newlibertarianconstitution.pdf) (**PDF**). Cantons will likely be highly incentivized to settle their disputes first by mutual agreement, then by arbitration. As a last resort they may be able to refer the matter to the Public Authority Supreme Court.

Cantons are very similar to David Friedman's private protection agencies, which he wrote about in the section "Police, Courts, and Laws -- On the Market", in his book [Machinery of Freedom](http://daviddfriedman.com/The_Machinery_of_Freedom_.pdf). (Formatting isn't the best, but it's free.)

**Comment by KacperZajc** [comment]
so what's the decision here guys?
we go with 'consent of the governed' or we go with 'attempting a harmonious consensus for the benefit of all those seeking their home in this place'
or sth completely different?

**Comment by joshmh** [comment]
Let's take a few more days to consider this. I encourage anybody reading this to weigh in with their thoughts. I'm going to think about it some more, as well.

**Comment by KacperZajc** [comment]
any one wants to contribute?

**Comment by NateBrune** [comment]
I'm confused. What is the issue with all citizens and residents of liberland implicitly concenting to its laws? If they it is wrong to imply concent because residents are living in liberland than 

We ... do ordain and establish the Constitution of the Free Republic of Liberland, attempting a harmonious consensus for the benefit of all those seeking their home in this place.

seems to be negated. I am not a lawyer, but they seem to be similar ideas.

**Comment by joshmh** [comment]
@NateBrune, my argument is that implicit consent doesn't make sense, all the more so if a citizen *explicitly* declares that he's not consenting. It still makes sense to claim that we're attempting a harmonious consensus. I believe we're all trying our best to affect the best consensus we can. We're not claiming anything stronger than that.

**Comment by KacperZajc** [comment]
ok guys we are asked to hurry up with updating the Constitution, we need a decision here on the Preamble

**Comment by NateBrune** [comment]
In my opinion, if a citizen *explicitly* declares that they are not consenting, it means nothing. In my county, if I explicitly declare that and then rob a house, I am still going to jail. I understand the *who are we to do such a thing* argument, but I dont think its so. If you wish to become a citizen in liberland, than you must follow its rules. I dont think that they should be evicted, just subject to the laws.

**Comment by joshmh** [comment]
There's a difference between subjecting someone to your rules, and claiming that he's consenting to being subject to your rules. Which is why I don't think we should claim people are consenting to these rules, when they themselves say they aren't. If someone robs a house, they will be dealt with whether they've consented or not.

**Comment by KacperZajc** [comment]
see #39 for conclusions
