### ISSUE TITLE
Equal protection under the law

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#409]
Do we have a provision that guarantees equal protection under the law (see US 14th amendment)?

**Comment by KacperZajc** [comment]
§I.6. No Person shall be excluded from the operation of, or granted any privilege under, any law passed by the Assembly; nor shall any Person be treated differently by law due to his or her origins, religious beliefs, sexual orientation, gender, cultural background and/or any other personal attribute; nothing in this provision shall prevent the Members of the Public Administration from enjoying certain immunities as described in this Constitution and no others; nor shall the Assembly be prevented from granting certain immunities to all legal Persons by virtue of possessing a separate legal personality or from establishing general rules governing liability of vicarious nature.

**Comment by terrorist96** [comment]
:smiley:

**Comment by KacperZajc** [comment]
I think we have covered all basic points, if there is anything left, it's small issues :)
