### ISSUE TITLE
Bill of Rights should be written positively

### ISSUE THREAD

**Issue by JesseKPhillips** [liberland/constitution#41]
Currently the Bill of Rights is written in a negative tone, thus never establishing rights of the People.

As an example, "No ex post facto law shall be passed." can be rewritten as, "A right of the people to know that laws will not change once enacted."

**Comment by hazzik** [comment]
Not related to the issue itself, but "No ex post facto law shall be passed." is not equal to "A right of the people to know that laws will not change once enacted."

**Comment by JesseKPhillips** [comment]
@hazzik I think you'll find that the difference is minor and if you think about it irrelivant and undesirable. The value of this exersise is to think about what is being protected. I hope to find time to draft a more appropriate foundation, but expect rejection and only hope to bring forward considerations.

**Comment by hazzik** [comment]
>I think you'll find that the difference is minor and if you think about it irrelivant and undesirable. 

The sentences are completely orthogonal to each other. "No ex post facto law shall be passed." says that laws shall not change [retroactively](https://en.wikipedia.org/wiki/Ex_post_facto_law), eg. you can not make a law and judge something what happened before that law has made up. 

Yours "A right of the people to know that laws will not change once enacted." says that laws will never change, and this is just completely mess, because laws change, they adapt to the situation.

Also, even your sentence was close to the original, "positiveness" will still change the sense of it.

**Comment by KacperZajc** [comment]
"No ex post facto law shall be passed."  is English for 'lex retro non agit' (latin for 'the law does not work back').
"A right of the people to know that laws will not change once enacted." is something completely different and tbh ridiculous. 
Bill of Rights should be in negative tone, because it says what the government cannot in terms of legislation. When it talks about individual rights, it is written in positively as you call it.

**Comment by tinkyholloway** [comment]
I agree with @KacperZajc, inverting the negative sense changes the meaning. I think leaving the sense as they are is much less ambiguous.

**Comment by Zephram-C** [comment]
I agree that negative sense is more precise and specific.

**Comment by JesseKPhillips** [comment]
You're correct, I did misunderstand what I was reading. I do find it interesting that you all gave up claiming it isn't possible to write down what right is being protected. Have you considered something to the affect of, "The right of the people to have their crime and punishment determined at the time of conviction; new crimes and increased punishments will not be retroactively applied." You'll note that in this case I'm allowing for ex post facto laws which reduce sentences or eliminate crimes (different from eliminating laws).
