### ISSUE TITLE
Land fee discrepancies 

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#413]
§II.18(6) The overall Fee revenue shall be calculated not to exceed 5% of the Gross Domestic Product of the Free Republic of Liberland of the preceding year.

GDP isn't the best way to calculate taxes, there are so many factors that can change GDP, it doesn't accurately portray wealth. GDP varies widely depending on the source used to calculate it as well. 

Does anyone have any ideas for a new way to calculate the land fee?

**Comment by KacperZajc** [comment]
I agree that GDP is not ideal but as far as I know there is no better yardstick.
I would be happy to hear your ideas.

**Comment by bjoelf** [comment]
How is GDP to be calculated if taxes are voulantary and no public administration to gather data and to do the acctual calculation? In Sweden there is a separate autority to just that (among other things). https://en.wikipedia.org/wiki/Statistics_Sweden.

Just my two cents. :) /Björn

**Comment by mherzl** [comment]
I suggest we get rid of the land fee and require gov to not violate the rights its supposed to be protecting.

Ideas for how to pursue revenue without violating rights include court/citizenship/voting fees, the canton system suggested in other posts, and voluntary taxation.

**Comment by bjoelf** [comment]
The state needs continius and predictible income so in my opinion the Land Fee is not the problem. It's how to create a rational method of calculating it's size that is the core of my consern. Anyone suggesting land fee is not a good alternative can come up with a better proposal. It's voluentary to buy land so charging a yearly fee is not to violate rights it's about to organise a country.  Just another two cents :) /B

**Comment by Auahi** [comment]
@mherzl Im not overly fond of the land fee but I understand why they have it. I'd much rather have a land fee than voting fees though; that could go wrong so many ways. I suggest you make another thread if you want to propose a new system, this one is about fixing the way to calculate the land fee.

**Comment by mherzl** [comment]
@Auahi I was thinking the presence of the land fee is the underlying cause of this thread's concerns, but as you suggest here I'll write my ideas on the more specific topic of determining tax limits.

Yes, without forcing businesses to report their official economic activity it may be impossible to calculate gdp to a meaningful degree of accuracy, and as a result the tax limit may not be meaningful.

But more importantly, the tax limit is not based on a characteristic of the taxed item. Instead there is an implicit assumption that land area is a legitimate measure of the taxes its owner deserves/can pay. What if, as seems to be the case in existing civilizations, land use is actually a horrible determiner of that? In cities most economic activity seems to occur on a very small fraction of all the land; perhaps 99% of the economy occurs on less than 1% of land area. Should a 1-acre tech or finance company with $100M revenue be liable for the same tax as a 1-acre park / playground / landfill / farm?

It would make more sense to follow existing governments and tax the item. The limit for a property tax should be based on e.g. that property's market value. For a tax limit based on gdp it makes more sense to tax the transactions that constitute gdp. If we want to be fundamentally different from existing governments then I suggest we get rid of forced taxation. :)

**Comment by liberlandcitizen** [comment]
This is a bit long, but please hear me out.

When I dream of Liberland, I dream of a very bold experiment. I dream of
taking things to the extreme (in a good way). If low taxes work best, how
well would no taxes work? I want one tiny plot on Earth where we can find
an answer to that question.

When President Jedlička was being interviewed by the great Tom Woods about
taxation, he mentioned crowdfunding the government. Woods, a truly
brilliant mind, was absolutely fascinated with the idea. Perhaps we are
backing down from this a little because Liberland is running on volunteer
contributions/crowdfunding right now and the crowd isn't always there, is
it?

Let's not be afraid. There are ways of going about Government sanctioned
crowdfunding. Most vital services can work with fees coming directly from
those who *choose* to use them.

Example: passports. The government charges for it only according to the
cost of the paper it's printed on, the machines that make it, the labor
that goes into issuing them, etc.

For any parts of the government for which direct fees don't make sense, a
form should be mailed (emailed?) to all citizens/residents once a year
detailing the finances of those things. I suggest a line item form where
the cost, per citizen, of each government program/service is explained.
Next to it, you can choose how much you wish to contribute. 100% voluntary.
You can pay more, less or exactly your share. Or you could pay nothing if
you so choose. You will write your contribution for each service, one by
one.

Any government service which is vital and well appreciated by the populace
will be funded. Lots of crime? The police will be well funded that year.
Low crime and the police are abusing the people? They are going to take a
huge cut in funding. In all other systems, waste, fraud and abuse exist
because the money flows freely up to the powerful by way of force. Let's
put the purse strings directly in the hands of the citizenry and let's be
an example to the world!

Taxation is theft. Every man, woman and child has to live on land.
Therefore land fees are passed on to everybody forcibly: property owners,
renters and even hotel guests. Why do we want to hand a huge pile of money
to yet another government so that they, in all of their wisdom, may decide
how to spend it? I say no. In Liberland, no money should be taken from your
pocket by the government unless by your own choice and for a service you
use or support. Surely we can figure out a way!

**Comment by Auahi** [comment]
@liberlandcitizen I agree with the fact that the Land Fee is wrong, there are other taxes that I greatly prefer. The only thing I don't like about that idea is that your essentially filling out a tax return.

**Comment by terrorist96** [comment]
I'm in favor of allowing people to pay for services they support and not fund services they disagree with. I mentioned it as a suggestion some time ago here:

https://github.com/liberland/constitution/issues/107

**Comment by liberlandcitizen** [comment]
Filling out the "return" would be a civil duty, but not a legal obligation.
It's not a tax return, it's a donation form.

**Comment by michalptacnik** [comment]
We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit
Land fee is set up differently, as a consensual/market instrument. Please comment in the new draft Constitution if interested.
