### ISSUE TITLE
Citizen's right to submit legislation

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#420]
I know this has been commented on before, but I'd like to have an actual discussion about this.

What are you're opinions, why should we or why shouldn't citizens be able to submit legislation?

**Comment by terrorist96** [comment]
I think we should allow for this. Relying solely on the legislature to pass a law that the people want is not a very promising prospect.

**Comment by liberlandcitizen** [comment]
Do we want more government? Then we want more bills and we should allow
citizens to submit bills so that we'll have more of them, and likely more
laws and more government.

Do we want less government? Then make it difficult for bills to exist and
even more difficult for them to pass.

I suggest less government. There is enough government in the hundreds of
other countries.

**Comment by KacperZajc** [comment]
more law = more government 
by restricting bodies that can propose legislation we limit the number of laws
this has been discussed in the past

**Comment by Auahi** [comment]
IMO citizens should be able to directly institute and vote on legislation, but what if we had a system in which citizens can repeal any legislation or law instead of being able to institute new legislation. Or we could always limit citizens to only be able to institute ordinary bills....

**Comment by terrorist96** [comment]
We already allow for citizen veto of legislation, but a separate repeal option doesn't exist after a bill has become law.

**Comment by KacperZajc** [comment]
Citizens' veto power is a tool for further restriction of the flow of legislation.
It's the exact opposite of the idea to allow Citizens to propose legislation.

**Comment by Auahi** [comment]
What I was saying before would be seperate from citizens veto, it would for legislation already in place like a law on cannabis, the citizens could repeal the legislation and make it fully legal. So it's as if you extended citizens veto to legislation already put in place. I think terrorist knows what I'm saying...

**Comment by liberlandcitizen** [comment]
​Direct democracy can be great when the populace votes in favor of rights
and freedoms (legalizing cannabis) but it can also be a tool for the
majority to take away rights and freedoms from the minority (making
same-sex marriage illegal).

We should aim to limit government, and especially the ability for
government to grow.

**Comment by Auahi** [comment]
I agree with limiting government but why if 51% of a populace agrees with something then why can't it be that way? Of course it'll have to be deemed constitutional etc.

**Comment by mherzl** [comment]
Should legislators also be prevented from proposing legislation? It would result in less legislation.

The claim -- preventing citizens from proposing legislation will result in less legislation -- does not apply to the context of this issue.

The amount of proposals that can be adequately considered is limited, and we want the best ideas brought to the table. Do legislators really have all the best proposals? Doubtful. What mechanism can we define for an ordinary citizen to get hers considered? x% on a petition?

**Comment by mherzl** [comment]
For limiting the amount of legislation I like the idea of requiring each law to have an expiration date as someone suggested somewhere.

**Comment by liberlandcitizen** [comment]
​Yes, legislators probably should be prevented from proposing legislation
too - but I know that's too extreme for most of you :)

I think what some of us are saying is that more bodies proposing
legislation = more laws passing. The more legislation that gets passed, the
bigger government will become. Maybe citizen legislation would be better
than representatives, but I'd caution to keep the number of bodies to a
minimum and making proposals difficult.

And while any legislation must be within the framework of our constitution,
don't forget that our constitution allows for amendments. And who knows
what kind of amendments will pass in the future. Income tax? Universal
healthcare? Sharia law? All it takes is a majority (or a supermajority) and
the minority will have to live with those things.

The experiment of Liberland requires as few laws as possible, now and in
the future. So let's not think of ways for the "best ideas" to be brought
to the table. We have the best ideas on the table right now: freedom and
limited government. Let's figure out how to preserve those things forever
in our nation.

**Comment by mherzl** [comment]
If the goal was to achieve the fewest number of laws then we could just delete them all and be done with it. :)

If the citizenry cannot be trusted to propose just laws, then how can they be trusted to elect representatives to propose just laws? There is no reason to believe that a representative will advocate for individual rights any more than his electorate will.

One main purpose of having representatives is actually to speed up the legislative process, to centralize power in order to make decisions more quickly and with less involvement by citizens. If the goal is to slow down the legislative process, shouldn't the approach be to decentralize power?

The "more bodies able to propose law = more laws" argument is almost as shallow and invalid as the "more freedom to use drugs = more drug problems", the "more freedom to use guns = more gun violence", the "more economic freedom = more economic instability", and generally speaking the "more freedom to do x = more x problems" that we aren't fooled by. Precisely, it is based on a false ideal and only seems to have meaning due to being taken out of that context.

But beyond that, we should assume that the populace we are writing for understands and advocates for individual rights. Understanding and protecting rights is not an easy task, we don't have all the best ideas now, and new problems will always come up. We should hope and expect that future Liberlanders will have some better ideas than we do, and set up government to both protect rights as best we can and enable them to improve on what we give them.

Besides, if our goal were to create a government capable of protecting rights even of a populace which does not understand their value, then we should stop writing the constitution and instead try to build an invincible robot dictator to enforce liberty for all of eternity, because that's the most realistic option. :)

**Comment by KacperZajc** [comment]
Read the Constitution guys, legislators ARE prevented from submitting Bills.
Only the Cabinet can initiate the legislative process, and only once a year.

**Comment by Auahi** [comment]
It'd be enormously hard to enact something like sharia, an income tax, universal healthcare since they are unconstitutional. If we only allow citizens to submit and repeal ordinary bills I don't see the problem. This would essentially bar any bad constitutional bill that everyone is worried about.

**Comment by liberlandcitizen** [comment]
*<<If the goal was to achieve the fewest number of laws then we could just
delete them all and be done with it. :)>>*

That would be anarchy and some favor that, but I personally believe in a
minimum number of laws (like not being allowed to violently harm somebody).
Plus for international recognition we need a constitution and government
of some kind. But we must keep it to a minimum.

<<we should assume that the populace we are writing for understands and
advocates for individual rights>>

With all due respect, I think that is a very bad assumption. It is hoped
the first generation of Liberland will understand freedom, but what about
ten generations from now? The allure of government handouts is very strong.
Politicians promise things, and offer to hand out social programs like
candy. Just look at the government size and power has creeped into other
nations over the years. It will happen to Liberland eventually as well,
unless we prevent it.

<< then we should stop writing the constitution and instead try to build an
invincible robot dictator to enforce liberty for all of eternity>>

Maybe I'm the extremist of this group, but we kinda *should* dictate
liberty for all of eternity! We need one tiny lot of land in this world
that's free, I think that's important for humanity. And right now we are
fighting so hard for it, I don't want to see us win it only to lose it to
democracy, bad future governments and an ignorant populace.

We should lock in freedom and liberty and make it extremely hard to change
the constitution. In my opinion, as currently written, it's too easy. We
should make it so that 90% or more of the population has to agree to a
constitutional change.

We will probably have universal healthcare and high taxes within 100 years
if we leave it as-is.
