### ISSUE TITLE
rights of defendants review

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#427]
We remove §V.24.

We amend those provisions:

§V.20. All defendants in criminal proceedings shall have the right to a speedy trial; in any event, no Person shall be convicted of a criminal offence later than a year after a Warrant permitting the detention of such Person was executed in connection with that offence; should said Person escape or commit any subsequent criminal offence, a new Warrant for custody may be issued.

§V.25. All defendants in criminal proceedings, and all Persons under arrest, shall have the right to be assisted by effective legal counsel and an interpreter, should they not speak the language of interrogation or court proceedings, and in case of trial, to have reasonable time for the preparation of their case; services of a counsel and an interpretor shall be contracted personally or, should one not be able to afford it, they shall be provided by the Secretariat of the Judiciary with the possibility to subsequently recover reasonable expenses should a defendant be convicted and the verdict not be overturned by the Supreme Court.

We add those provisions:

All defendants in criminal proceedings shall have the right to attend Court proceedings, to be informed of criminal charges and of his or her rights, to compel witnesses to appear in Court for examination, and to examine all evidence gathered against him or her, including any information which has been classified as a state secret should the Prosecution wish to employ such evidence; in such cases the proceedings shall take place in camera and the Defendant shall take an oath of secrecy for the period relevant information remains classified as a state secret.

All defendants in criminal proceedings shall have the right to be presumed innocent until proven guilty and to not be compelled to be a witness against himself or herself, or such other Persons as may be prescribed by law, without any negative inference In all criminal proceedings; the Prosecution shall always carry the legal burden of proof, discharged beyond reasonable doubt, in relation to the defendant's guilt, including disproving any defence envisaged by the law which he or she might raise; nothing in this provision shall prevent the creation of defences which require the defendant to discharge the evidential burden of proof by raising the issue of defence available to him or her.

#424 
#414

**Comment by terrorist96** [comment]
interpretor -> interpreter
change `rely on` to `utilize` - the reason is that it can be argued that the prosecution isn't 'relying on' the evidence, but merely providing it as supplementary. `Utilize` would cover such situations.
> the Defendant shall take an oath of secrecy for the period **the** relevant information remains classified ~~as a state secret~~

semicolon after `negative inference`, lowercase `In` (or break it off to a separate section) and change the semicolon after criminal proceedings to a comma.

You're retaining the speedy aspect of the trial, but what about the `public and impartial trial by Jury` aspects?
And what about `should any Person be prosecuted in breach of due process of law as enumerated in this and other provisions of this Constitution, the trial Judge or the Supreme Court shall take that under advisement when considering dismissing the charges before the Jury retire to consider their verdict or overturning the verdict.`?

**Comment by KacperZajc** [comment]
I dont think 'utilise' covers more than 'rely'.
But we can use 'submit' which would probably cover the situations you mentioned.

Jury bit is covered in the Judicial Power part of the Constitution.
Dismissing charges on the basis violation of defendant's rights is an integral part of any judicial proceedings IMO so no need to state that.
Overturning verdict on the basis of procedural irregularity is expressly provided for in the Judicial Power part of the Constitution.

**Comment by terrorist96** [comment]
> should the Prosecution wish to submit such evidence

This sounds like the prosecutor has an option of whether or not they want to disclose that they are using classified evidence. I still think `utilize` is the better word here, because it covers any situation that the prosecution wishes to use the evidence. Rely on could mean that the case relies solely on that evidence and no other evidence.
How about `should the Prosecution wish to employ such evidence`? I want this to apply to any situation where the prosecution uses in any way classified evidence, and `submit` doesn't feel like it encompasses that. An example I would cite would be use of Stingrays in the US. The prosecution doesn't submit that evidence, but they use that evidence for [parallel construction](https://en.wikipedia.org/wiki/Parallel_construction).

**Comment by terrorist96** [comment]
> Dismissing charges on the basis violation of defendant's rights is an integral part of any judicial proceedings IMO so no need to state that.

Really? The exclusionary rule wasn't fully implemented in the US until 1961.

**Comment by KacperZajc** [comment]
Im fine with 'employ'. Would that prevent parallel construction or should we deal with it expressly?

**Comment by terrorist96** [comment]
I think it would cover it.

**Comment by KacperZajc** [comment]
Isnt the exclusionary rule covered by §IV.8(2)?

Preliminary Hearings shall be held by one Judge of the relevant Court who may dismiss the case before it proceeds to a full trial on the grounds of the lack of sufficient evidence or clear unconstitutionality of the prosecution or claim.

**Comment by KacperZajc** [comment]
We can amend it to say:

Preliminary Hearings shall be held by one Judge of the relevant Court who may dismiss the case before it proceeds to a full trial on the grounds of the lack of sufficient evidence, clear unconstitutionality of the prosecution or claim.or substantial violation of defendant's rights.

**Comment by terrorist96** [comment]
I'd keep `substantial` out of it. That opens the door to challenge the severity of the rights violation. Any rights violation should be unacceptable.

**Comment by KacperZajc** [comment]
good point
