### ISSUE TITLE
Right to refuse to ID

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#441]
No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest, an articulable suspicion of a violation of the law or pursuant to a Warrant.

**Comment by KacperZajc** [comment]
No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest, a reasonable suspicion of a violation of the law or pursuant to a Warrant or a Court order.

And we add this provision to the Privacy Rights Article of the Bill of Rights.
But I dont promise there are no more exceptions to this rights.

**Comment by terrorist96** [comment]
> No Individual shall be compelled to identify himself or herself to any Agent of the Public Administration, unless upon arrest, a reasonable suspicion of a violation of the law or pursuant to a Warrant or ~~a~~ Court order.

**Comment by liberlandcitizen** [comment]
Why should you have to identify yourself just because a police officer has
"reasonable suspicion?" Cops lie about this all of the time and use it to
harass people.

**Comment by terrorist96** [comment]
Reasonable suspicion requires an articulate set of facts. If he lies about it, then he arrests you, you get out, sue his ass and win.

**Comment by liberlandcitizen** [comment]
​It is often very difficult to prove that an officer lied. You can't
disprove what they what they claim they saw, heard or smelled. These types
of laws/rules do nothing to protect society. In a free nation, a free
person shouldn't have to say ANYTHING to the police if they don't want to.
At least not until they are arrested and only then their name and address.

I think an officer should be able to temporarily detain somebody if they
have reasonable suspicion, but your right to remain silent should not
evaporate just because they suspect something.​

**Comment by terrorist96** [comment]
> but your right to remain silent should not
evaporate just because they suspect something.​

It doesn't. You only need to identify yourself if you're suspected of committing a crime, so they can write you a citation if need be or check you for any outstanding warrants. None of this happens unless there's suspicion of a crime.

**Comment by liberlandcitizen** [comment]
If a citation is issued or an arrest has been made, that moves beyond
suspicion. ​This means an officer has evidence of a crime. At that point, I
think it's fair for citizens to have to identify themselves by name, and by
address. Nothing more, nothing less. However no citizen should have to
identify his or herself just because an officer has *suspicion*. Police can
use this to abuse citizens, or to fish for arrests, people with warrants,
etc. Example from my country: police demanding id from people of a certain
color. Their skin color makes them suspicious they are here illegally.
Obviously many people of that skin color are legal, and yet they are
harassed.

As I said earlier, police should have the right to temporarily detain based
on suspicion, but a citizen should also have the right to remain silent and
the right not to be searched against their will unless and until there is
actual evidence of a crime.

**Comment by terrorist96** [comment]
So I think we just need to distinguish between `probable cause` and `reasonable suspicion`. I would be in favor of changing it to `probable cause`.

> police should have the right to temporarily detain based
on suspicion

I think we had this discussion before where Kacper said that we don't allow for detainment, only arrest. So police can't just stop you and stop you from leaving unless they plan on arresting you.

**Comment by KacperZajc** [comment]
That's correct.
I think probably cause (which is a higher threshold) is more suitable for arrests
but reasonable suspicion (which is a lower standard) is better for identification
after all this is only a request for ID

**Comment by liberlandcitizen** [comment]
You guys must all live somewhere where police are good police and where
they don't harass the public? I wish I could say the same.

I have no issues with the police requesting to see ID, I have issues with
the public being compelled to give it. Is this a free nation or not? If you
are walking down the street and haven't committed a crime, why should you
be *compelled* to do anything at all? Just because an agent of the mighty
government allegedly suspects you of something? What will happen if you
refuse? You'll have to give money to the government in the form of a fine?
You'll have to spent a night or more in jail?

**Comment by KacperZajc** [comment]
Insofar as your post makes sense in principle, it is unworkable in practice.
'If you are walking down the street and haven't committed a crime...' - one can be held to have committed a crime only by a Court so in your visions it would be impossible to demand ID prior to a conviction, which is completely unworkable in practice for obvious reasons. 
One must be identified before he or she is brought before the Court.

Accordingly, the power to demand ID must be triggered by something short of a conviction.
@terrorist96 suggests 'probable cause' which we also use for arrests. It is a high threshold.
I suggest 'reasonable suspicion' which is used by the British police.
I think it is more suitable for a power to demand ID which IMO is not an extensive power after all.

**Comment by terrorist96** [comment]
From my understanding, only 24 states in America have stop and identify laws, which requires you provide an ID upon reasonable suspicion. My question is what about the other 26 states that have no law? They don't require ID, even upon reasonable suspicion, only upon probable cause, it seems. 

According to Texas Penal Code 38.02, a person must identify themselves with a valid name, address, and date of birth to a police officer who has lawfully arrested them. Notice that the person must be under arrest for this to apply. In Texas, if you are not under lawful arrest, you do not have to identify yourself.

https://www.versustexas.com/criminal/texas-dont-identify-police-unless/#Is_it_an_offense_to_fail_to_identify_yourself_to_the_police

Why couldn't we do this in Liberland?

**Comment by KacperZajc** [comment]
well if it works in Texas, why not
I dont have any particular problem with it

**Comment by liberlandcitizen** [comment]
Thank you for posting that. It works very well in Texas and I know it will
work for Liberland too.
