### ISSUE TITLE
use of force by Law Enforcement

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#454]
Agents of Law Enforcement shall not use firearms unless it is necessary (a) in self-defence and defence of health and life of others, (b) to prevent a serious crime from taking place (c) or grave damage to the property or (c) upon apprehension of a suspect, accused, defendant or convict where he or she resists or attempts escape; in any event such use of firearms shall always be proportionate to the end sought and shall not be intended to procure death of a Person targeted unless it is the only possibility to achieve the desired end.

What do you think guys?
Good idea, bad idea?
Unnecessary?

**Comment by liberlandcitizen** [comment]
​If we are going to keep this, I would keep *only* letter a. There is no
higher natural right than the right to your life, and we should be very
careful when giving an instrument of the government (in this case police) a
license to kill. Obviously if their own lives (or the lives of the public)
are in danger they should be allowed to use lethal force. But should
government be allowed to kill because of some alleged damage to property?
Should they be allowed to kill somebody simply because they are running
away? I say they should absolutely not be allowed to use deadly force in
those instances.

**Comment by terrorist96** [comment]
Unnecessary. 

> §III.14(5) The Chief Commissioner shall be under obligation to take all available measures to ensure the enforcement of law in the Free Republic of Liberland by Law Enforcement is conducted in the least intrusive and most peaceful manner possible.

**Comment by KacperZajc** [comment]
good point
