### ISSUE TITLE
power of arrest

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#470]
§X.4. The primary power of arrest shall lie with Agents of Law Enforcement; in the absence of any such Agent, in exigent circumstances, a Person may be arrested by any Citizen or other Resident of the Free Republic of Liberland for so long as reasonably necessary to allow an Agent of Law Enforcement to take custody of the detainee.

**Comment by terrorist96** [comment]
Remove exigent circumstances. That would be a huge barrier to people being able to arrest one another. People would doubt whether such circumstance counts as exigent, etc. If there's a wanted notice for a fugitive, and you have an opportunity to capture that person, you should be able to do it regardless of circumstances or presence of law enforcement. Once you capture them, you turn them into law enforcement and claim your bounty. 

> §X.4. **In general,** the ~~primary~~ power of arrest shall lie with Agents of Law Enforcement; ~~in the absence of any such Agent, in exigent circumstances,~~ a ~~Person~~ **wanted fugitive** may be ~~arrested~~ **subdued** by any ~~Citizen or other Resident of the Free Republic of Liberland~~ **Person** ~~for so long as reasonably necessary to allow~~ **in order to be transferred to** an Agent of Law Enforcement ~~to take custody of the detainee~~.

I chose to use `subdued` because that can include killing, if a wanted posted indicates "wanted: dead or alive" for example (I'm open to better wording if you can think of any). Changed citizen/resident to person because citizen + resident = person (minus illegally present people), but if an illegal immigrant can subdue a wanted fugitive, why not let them?

Overall, this is how my final version would look:

> In general, the power of arrest shall lie with Agents of Law Enforcement; a wanted fugitive may be subdued by any Person in order to be transferred to an Agent of Law Enforcement.

**Comment by terrorist96** [comment]
> In general, the power of arrest shall lie with Agents of Law Enforcement; a wanted fugitive may be subdued**, or a miscreant may be arrested,** by any Person in order to be **expeditiously** transferred to an Agent of Law Enforcement.

I just realized that we may need to allow for detainments of miscreants by persons, such as witnessing a crime take place and being able to legally hold that person

**Comment by KacperZajc** [comment]
miscreants is exactly what I was going for with 'in exigent circumstances'

I prefer my version (with your fugitive example):

§X.4. The primary power of arrest shall lie with Agents of Law Enforcement; in the absence of any such Agent, in exigent circumstances or pursuant to a public arrest warrant, a Person may be arrested by any Citizen or other Resident of the Free Republic of Liberland for so long as reasonably necessary to allow an Agent of Law Enforcement to take custody of the detainee.

This version is based on the old version of this provision (before recent changes) and sounds better to me.

**Comment by terrorist96** [comment]
The only issue I have is what if there's a "WANTED: DEAD OR ALIVE" 'public warrant' out for someone? If a bounty hunter tries to kill that person, they wouldn't be covered by your wording because they'd only be allowed to arrest him, even if it's not practicable.

**Comment by liberlandcitizen** [comment]
I'm of the opinion that even the worst of criminals deserve a fair trial.
Universal rights are universal. If a bounty hunter kills somebody in
self-defense then they are covered as all citizens are.

**Comment by terrorist96** [comment]
A Dead or Alive classification would usually only apply to criminals that have escaped from prison, and the like. They've already had their trials.

**Comment by liberlandcitizen** [comment]
I would still argue they have a right to their life.

**Comment by KacperZajc** [comment]
I dont think we would pursue Dead or Alive classification.
It's not the Wild West after all.
In any event, this provision says nothing about that, it is only concerned with the power to arrest.
