### ISSUE TITLE
register of vehicles

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#472]
We need to create the possibility to conduct a register of vehicles.
I propose we add that to VIII.1 and VIII.3.

**Comment by terrorist96** [comment]
Let's debate why we would need a register of vehicles to begin with.

- Maintaining a register of all births and deaths of Citizens or other Residents makes sense, because the government needs to  know if you're alive or not in order to conduct its work (so for example, it doesn't summon a dead person for jury duty).
- Maintaining a register of owners of land makes sense since we have the possibility of a land fee
- Collecting personal information related to visa procedure makes sense because the PA regulates immigration.

What purpose would a register of vehicles serve the PA?

**Comment by KacperZajc** [comment]
As we discussed in relation to jurisdiction - vehicles registration is relevant.

**Comment by terrorist96** [comment]
Okay, but it feels like a slippery slope.

**Comment by liberlandcitizen** [comment]
All of this is a slippery slope if registration is mandatory. I could
forsee a real need for vehicle registrations of any boats, planes or cars
which will leave Liberland territory and need proof that they are
registered in Liberland. However, within the borders of Liberland I hope
that any such registrations will be optional. Why do most governments
require its citizens to register their property? In my opinion it's so that
they can tax you for owning that property.

**Comment by KacperZajc** [comment]
I agree with both of you
I propose we add 'and a register of vehicles intended to be used outside of the territory of the Free Republic of Liberland'

**Comment by terrorist96** [comment]
Yeah, I agree with @liberlandcitizen here. Vehicle registration should only be required if you intend on taking your vehicle outside the country (so you don't get pulled over for having no license plates in Croatia, etc.) Similar to [constitutional carry](https://en.wikipedia.org/wiki/Constitutional_carry) states in America, a permit is not required unless you intend on leaving that state, registration should not be required unless you think you will drive outside of Liberland.

**Comment by KacperZajc** [comment]
§VIII.3. No Individual shall be required to register and/or share information about his or her whereabouts, be it permanent or temporary, assets, be it tangible or intangible, and/or signed contracts, be it employment, commercial or otherwise, unless pursuant to a Warrant; nor shall any Person be required to register and/or share information about any personal attributes such as medical conditions, fingerprints, DNA, religion, political affiliation or others unless pursuant to a Warrant; nothing in this provision shall prevent the Public Administration from maintaining a register of (a) owners of land within the Free Republic of Liberland, and (b) vehicles intended to be used outside of the territory of the Free Republic of Liberland, (c) or collecting personal information related to visa procedure.

**Comment by terrorist96** [comment]
> nothing in this provision shall prevent the Public Administration from maintaining a register of (a) owners of land within the Free Republic of Liberland, ~~and~~ (b) vehicles intended to be used outside of the territory of the Free Republic of Liberland~~,~~ **(delete comma)** **or** (c) ~~or collecting~~ personal information related to visa procedure.

Also, I feel like it should be merged with VIII.1 since it mentions land register in both sections, for example.

**Comment by KacperZajc** [comment]
I think they are still separate
