### ISSUE TITLE
Chapter IV

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#481]
Chapter 4: Final Provisions

The Constitution of the Free Republic of Liberland shall be construed in the light of Overriding and Interpretive provisions and shall enter into force upon the conditions prescribed in the Transitional provisions.

Article XV: Overriding Provisions

•	§XV.1. Notwithstanding any provision of this Constitution, the Cabinet shall have the exclusive power to sign binding international treaties regulating the flow of Persons, goods, services and capital across the border of the Free Republic of Liberland, and to directly enforce those treaties on the borders of the Free Republic of Liberland; such power shall be reviewable by the Civil Court exclusively on the basis whether a treaty, and/or its enforcement, falls within the scope of this provision and whether the enforcement measures undertaken are the least intrusive measures available.
•	§XV.2. No provision of this Constitution shall be construed as to prevent the Assembly from criminalising any act or omission which does not stem from the inherent right of self-defence but amounts to any (a) physical, or constitutionally recognised form of non-physical, violence towards any person or animal capable of conscious behaviour, or threat thereof, (b) invasion of privacy, (c) fraud, (d) direct and grave interference with enjoyment of one’s property or (e) harm to environment beyond the boundaries of one’s property.
•	§XV.3. The enumeration of certain rights in this Constitution shall not be construed as to deny or disparage others retained by the Citizens and other Residents of the Free Republic of Liberland.

Article XVI: Interpretive Provisions

•	§XVI.1. The jurisdiction of the Free Republic of Liberland shall extend to the whole territory of the Free Republic of Liberland, including premises of any of its extraterritorial diplomatic missions, its airspace, territorial waters, all vehicles registered therein whilst in an international space, and any area under the overall effective control of the Territorial Defence force.
•	§XVI.2. Any ambiguity in this Constitution and any laws passed in accordance therewith shall be resolved so as to give the greatest liberty from restraint imposed by law or this Constitution on any Person's conduct; and so as to provide for the least extensive power for any branch of the Public Administration, their Members and Agents, consistent with the clear meaning of the provision in question.
•	§XVI.3. The Constitution of the Free Republic of Liberland shall be interpreted in good faith and literally, as far as it does not produce any absurd result, with due regard to the original intention behind its provisions; in case of doubt, consideration may be given to any statements or notes related to the text made before or at the time of its adoption.
•	§XVI.4. For the purposes of this Constitution, the term “Person” shall signify any human being whatsoever; the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated for any purpose envisaged in the Constitution; the term “Agent of the Public Administration” shall signify any Person working for any body of the Public Administration, including the Law Enforcement; the term “Member of the Public Administration” shall signify any Person who is holding a public office of one of the branches of the Public Administration; the term “Agent of the Law Enforcement” shall signify any Person working for Law Enforcement or the Office of the Public Prosecutor; the term “Citizen” shall signify any Person holding citizenship of the Free Republic of Liberland; the term “Resident” shall signify any Person within the jurisdiction of the Free Republic of Liberland who is not a Citizen; the term "law" shall signify any Act passed by the Assembly in accordance with Article II and any Executive Measures as issued by the Cabinet in accordance with Article III.

Article XVII: Transitional Provisions

•	§XVII.1. The first General Election shall be called by the Provisional Government of the Free Republic of Liberland in order to elect an Assembly composed of twenty members.
•	§XVII.2. Immediately following the first General Election, the President of the Provisional Government shall put forward to the Assembly a draft of this Constitution of the Free Republic of Liberland along with the nomination of any five Persons for the positions of the first four Justices and the Chief Justice of the Supreme Court.
•	§XVII.3. §XVII.3. The Provisional Government shall disband once the Assembly officially ratifies the draft of the Constitution and judicial nominations or, should such draft be rejected, once another form of Government is established.
•	§XVII.4. The Constitution of the Free Republic of Liberland shall enter into force upon the approval of a simple majority of the Assembly with the quorum of no fewer than fifteen Assembly Representatives. 
•	§XVII.5. The Presidential nominations for the positions of the Justices and the Chief Justice of the Supreme Court shall enter into force upon the approval of the Constitution by the Assembly. 
•	§XVII.6. Following the approval of the Constitution by the Assembly, it shall without delay elect the Chancellor of the Free Republic of Liberland who shall have a one-off power to initiate a legislative procedure with no time constraints. 
•	§XVII.7. All Orders of the Provisional Government of continuous application shall remain binding following the first General Election in so far as they do not contravene the Constitution or their operation is not terminated or altered by an Act of the Assembly passed in accordance with the Constitution.
•	§XVII.8. All Orders of the Provisional Government and decisions of the President, Vice-Presidents and the Ministers of the Provisional Government which have been completed or otherwise fulfilled shall remain fully valid following the first General Election.

As you can see Articles XV and XVI contain provisions transferred from Article I.
Article XVII contains provisions from the Article of the Provisional Government and provides continuity between the current and future Government of the Free Republic of Liberland.
It also resolves the paradox regarding the appointment of first Judges.

Now the Constitution is complete, at least in terms of form.

**Comment by KacperZajc** [comment]
@terrorist96, any suggestions on Article XVI?

**Comment by liberlandcitizen** [comment]
<<§XVII.6. Following the fist General Election the Assembly shall with no
delay elect the Chancellor of the Free Republic of Liberland who shall have
a one-off power to initiate a legislative procedure with no time
constraints. >>

I believe fist is supposed to be first.

If I may....I feel that §XV.2 is vague and could be problematic down the
line. It's especially concerning because it "overrides" the rest of the
constitution. Though not the same thing, I feel this language could be
compared to the US Constitution's "necessary and proper" clause which we
all know is abused and allows for just about anything in US politics. I
feel activist judges could point to this part of our constitution and use
it to essentially enact laws, claiming that they relate to things such as
fraud or protection of property or even protection of the environment.

Judge: "You can't do _____ it's illegal"

Citizen: "Point to the law or the part of the constitution that makes it
illegal"

The judge will say "§XV.2" and bang his or her gavel and that will be the
end of the argument. Do we really want to give this authority to judges?

Rather than being vague I suggest we allow the rest of the constitution to
work, and for anything that we omitted or didn't think of, there is a
legislative process for addressing those issues.

**Comment by KacperZajc** [comment]
The whole point is that without §XV.2, any attempt to legislate would be struck down as breach of the Constitution. This provision does not give judges any direct power, it allows the Assembly to legislate criminal offence which would otherwise be unconstitutional.

**Comment by liberlandcitizen** [comment]
If that's the case, any chance we can clarify that this is for legislators
only and not applicable to any interpretations by the courts?

**Comment by KacperZajc** [comment]
Then we can rephrase: 

Maybe we should clarify by rephrasing:

§XV.2. No provision of this Constitution shall be construed as to prevent the Assembly to criminalising any act or omission...

**Comment by liberlandcitizen** [comment]
Yes please, with that your intentions are clear.

**Comment by KacperZajc** [comment]
for debate on the sunset clause in §XV.1. see #482

**Comment by terrorist96** [comment]
We're adding an additional chapter? That doesn't seem conducive towards limiting the length of our constitution. :stuck_out_tongue_closed_eyes: 

> The Constitution of the Free Republic of Liberland shall be construed in the light of **Overriding** and **Interpretive** provisions and shall enter into force upon the conditions prescribed in **the** transitional provisions.
• §XV.1. Notwithstanding any provision of this Constitution, the Cabinet shall have the exclusive power to sign binding international treaties regulating the flow of Persons, goods, services and capital across the border of the Free Republic of Liberland, and to directly enforce those treaties on the borders of the Free Republic of Liberland; such power shall be reviewable by the Civil Court exclusively on the basis whether a treaty, and/or its enforcement, falls within the scope of this provision and whether the enforcement measures undertaken are the least intrusive measures available.

See #482 for updates to this provision

> • §XVI.3. The Constitution of the Free Republic of Liberland shall be interpreted in good faith and literally, as far as it does not produce any absurd result, with due regard to the original intention behind its provisions; **in case of doubt, consideration may be given to any statements or notes related to the text made before or at the time of its adoption.**

Regarding the bolded part: do you think we should change it to `shall` instead of `may`? Otherwise, it really doesn't say anything. 
Also, it basically refers to the notes posted here on GitHub, right? :grin: 

> • §XVI.4. ....the term “Individual” shall signify a Person of age who does not lack mental capacity and is not incarcerated **for any purpose envisaged in the Constitution**...

Regarding the bolded part: what other kind of incarceration did you think up?

> • §XVII.1. The first General Election shall be called by the Provisional Government of the Free Republic of Liberland in order to elect ~~the~~ **an** Assembly composed of twenty members.

Still no elucidation of the parameters of our elections?

> • §XVII.2. Immediately following the first General Election, the President of the Provisional Government shall put forward to the Assembly a draft of this Constitution of the Free Republic of Liberland along with **the** nomination of any five Persons for the positions of the first four Justices and the Chief Justice of the Supreme Court.

What about the other Judge positions?

> • §XVII.3. The Provisional Government shall disband once the Assembly officially acknowledges the receipt of the draft of the Constitution and judicial nominations. 

Shouldn't the Provisional Government disband once the constitution is ratified, not when it's acknowledged?

> • §XVII.4. The Constitution of the Free Republic of Liberland shall enter into force upon the approval of a simple majority of the Assembly with the quorum of no fewer than fifteen Assembly Representatives. 

So does this override this:
https://github.com/liberland/laws/blob/master/drafts/The_Articles_of_the_Preparatory_Committee.md

> • §XVII.5. The **Presidential** nominations for the positions of the Justices and the Chief Justice of the Supreme Court shall enter into force upon the approval of the Constitution by the Assembly. 

So approval of the constitution is tied to the nomination of the justices? Can't the assembly vote on that separately?

> • §XVII.6. Following the approval of the Constitution by the Assembly, it shall ~~with no~~ **without** delay elect the Chancellor of the Free Republic of Liberland who shall have a one-off power to initiate a legislative procedure with no time constraints. 
• §XVII.7. All Orders of the Provisional Government of continuous application shall remain binding following the first General Election in so far as they do not contravene the Constitution or their operation is not terminated or altered by an Act of the Assembly ~~passed in accordance with the Constitution~~.

What orders would the provisional government propose? And removing the last part as it's redundant since we define how an Act comes into force.

• §XVII.8. All Orders of the Provisional Government and decisions of the President, Vice-Presidents and the Ministers of the Provisional Government which have been completed or otherwise fulfilled shall remain fully valid following the first General Election.

Isn't this redundant with the provision preceding this?

**Comment by KacperZajc** [comment]
§XVI.3: I dont think we should oblige the court to look into comments. I want to allow it as very often (at least in the UK) the court refrains from looking into parliamentary papers etc when it comes to interpretation. So I would go for 'may'. GitHub and other other source of comments.

 §XVI.4: deportation, breach of court order etc.

§XVII.1: OK, 

§XVII.2: OK; once we nominate the Justices, then they can co-create the Appointment Commission and the rest of the judges will be appointed the regular way 

§XVII.3: if it doesnt get ratified, it will be for the Assembly to come up with a new form of Government anyway.

§XVII.4. It's not inconsistent, just qualifying here what the quorum is.

§XVII.5: yes it is tied

§XVII.6: OK

§XVII.7: The Provisional Government makes some binding Orders right now, this provision just ensures continuity.

§XVII.8: fulfilled decision are e.g. those related to citizenship, just making sure here, the Assembly will not revoke citizenships granted by the Provisional Government

**Comment by liberlandcitizen** [comment]
It does seem to make sense that, rather than playing guessing games, the
people interpreting the document should look at the words of the people who
wrote it to find out exactly what their intent was.

**Comment by terrorist96** [comment]
> §XVII.3: if it doesnt get ratified, it will be for the Assembly to come up with a new form of Government anyway.

So there's going to be a potential interregnum if the Assembly doesn't immediately ratify the constitution as soon as it receives it. You don't think that'd be dangerous?

**Comment by KacperZajc** [comment]
This is a very good point.

• §XVII.3. The Provisional Government shall disband once the Assembly officially approves the draft of the Constitution and judicial nominations or, should such a draft be rejected, once another form of Government is established.

???

**Comment by terrorist96** [comment]
Change `approve` to `ratify`. Remove `a` after `such`

**Comment by KacperZajc** [comment]
ok
