### ISSUE TITLE
Maybe we should simplify the preamble, and emphasize liberty more ?

### ISSUE THREAD

**Issue by liberty90** [liberland/constitution#49]
Current preamble is almost directly, with very small changes, copied from the US constitution. We all know how US constitution is currently interpreted... for example, "justice" is very relative and can be easily hijacked by interventionist agenda.

What do you think about shorter and simpler version ?

For example:
"We, the Citizens of the Free Republic of Liberland, hereinafter, "the Citizens", in order to secure the blessings of liberty to ourselves and future generations, do ordain and establish the Constitution of the Free Republic of Liberland, hereinafter “the Constitution”, as its supreme law. Hereby, the Free Republic of Liberland shall be governed by the Public Administration exercising the legislative, executive and judicial powers restricted by the Bill of Rights."

As you can see I only deleted a "few" words.
IMHO it's quite obvious that common defense or justice system are required, all states have them, even socialist hellholes; so (in my opinion) the preamble should talk only about the most important (and rare!) thing above all - liberty. Different emphasis, much more difference from the US constitution, much more original philosophy.

PS. I did not submitted this as an pull request, because this is somewhat matter of philosophy. Are we more Republican or Libertarian ? ; ) Do we want to emphasize liberty above all other things ? I would, but this is only my opinion.

**Comment by tinkyholloway** [comment]
@liberty90 We seem to have a full range of from conservative to randian to rothbardian. Occassionally you'll see some poor well intentioned socialist wander in completely lost.

I too would gain some help in understanding where on the spectrum the vision for Liberland is. At the moment it appears to me to be around randian perhaps a little towards rothbardian depending on the day and topic being discussed.

None of this is a criticism. For Liberland to be recognised internationally and therefore legitimised, it needs to be a state. For that to happen at least some folks will need to accept more state thsn they'd otherwise wish for.

The trick I think is to try and create a mechanism that tends towards a rothbardian condition over time in a similar way that present western constitutions have allowed their states to tend towards marxism over time.

**Comment by Zephram-C** [comment]
Yes, I think the spectral classification of vision is very important. I started special (more broad) [issue #52](https://github.com/liberland/constitution/issues/52) about this.

As to the simplifying... I believe it should not be shortened, because this is exactly the part where Constitution also have to be "beautiful" (familiar, specific, inspiring, informative even for people not fully understanding what liberty stands for). For informed, educated and convinced Rothbardians, perhaps few line, couple points Constitution (simple like Asimov`s Three Laws of Robotics) would be sufficient. But not for general population.

**Comment by liberty90** [comment]
I'm afraid that "general population" understands "justice" somewhat different than libertarians... See "social justice". Liberty, on the other hand, is much more obvious...

**Comment by liberty90** [comment]
So I'm not sure that these "beautiful" passages actually guarantee anything other than weird conflicts about interpretation...

**Comment by tinkyholloway** [comment]
@liberty90: "general population" understands "justice" somewhat different..."social justice"

You're right. Socialists have an established record of redefining language to trojan horse their ideas into established and accepted canon. I agree it's right to avoid ambiguous terms or ones that can obviously be subverted because they are known to be attack points. However, it may be weak to relay on the accepted definitions of key terms since there is nothing to say that tomorrow "liberty" won't be subverted a la "social liberty" to mean all types of things such as "liberty from hunger" and "liberty from a lack of high speed internet".

**Comment by liberty90** [comment]
My questions are partially outdated; new preamble is quite good and better than my proposition. Liberty already seems to be emphatised more than in the first draft.

**Comment by KacperZajc** [comment]
:)
