### ISSUE TITLE
testamentary freedom

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#491]
clarification:

§VIII.4. No law shall establish and/or regulate the institution of marriage made exclusively between Individuals; nor shall any law restrict an Individual’s testamentary freedom; nothing in this provision shall prevent the Assembly from establishing the rules regarding the creation of valid wills or regulating inheritance where no such a will has been produced.

**Comment by Auahi** [comment]
It's okay, I just don't want the Assembly to regulate who can receive a will etc. but I understand it's importance.

**Comment by terrorist96** [comment]
When you say "exclusively between individuals", are you trying to limit marriage to 2 people? Or does this not touch polygamy?

> rules regarding the creation of valid wills

Does the Assembly really need to make laws about what make a will valid or not? If a person writes a will, it should be deemed valid by default, not deemed invalid because they didn't follow some obscure rule for creating wills that the Assembly thought up.

> or regulating inheritance where no such a will has been produced.

I think this can be left out too. Nothing in the provision comes close to touching that, so we don't need an exception clause for that.

**Comment by Auahi** [comment]
I'd say the assembly should deem whether a will is valid or not. If someone is being manipulated or under the influence of a substance, such as a poison etc. I think a will should be invalid. If a person was drugged before death, and because of their altered state of consciousness wrote a will giving all their assets to the person who drugged them, the will should be invalidated. This is what this provision is for.

**Comment by KacperZajc** [comment]
There is nothing in this provision which indicates how many people can get married. It only clarifies that the freedom pertains to Individuals only and the Assembly can prohibit marriages of minors.

The rules regarding the validity of wills are important because they prevent fraudulent claims. We are here to protect the private property and I think it falls within the scope.

I know the original wording probably did not exclude the possibility to regulate inheritance in the absence of a valid will, I just want to clarify.
