### ISSUE TITLE
The salary of an AR

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#492]
Here's an example of why we should give ARs salaries. This is just one scenario that I thought of, I'm sure there are many more problems that can arise with their lack of slaries.

1) ARs will be in session for at least one week a month, for at least nine months (I know this can be extended or shortened). This is problematic for many people who hold **average** jobs. If you owned a company I can guarantee you that you would not hire, pay _(for time being absent)_, or keep a person who has to leave for at least nine weeks out of each year. This is almost as long as maternity leave. Also you cannot expect this to be the sole work of an AR; members of any parliament do much more work outside of being in parliamentary sessions, thus further constraining the average citizen from being an AR.

2) This now leaves the position of being an AR to wealthy individuals, and/or individuals that will take in donations for income.

3) Liberland will now be a plutocracy, and the ARs who accept _"donations"_ will essentially be lobbyists.

I think you should reconsider your stance on the salaries of ARs. Without ARs receiving a salary it will make it very difficult for the average citizen to be an AR.

**Comment by liberlandcitizen** [comment]
I'm not so sure that "in session" would equate to full-time work for the
assembly, I believe this means that those weeks are the weeks they can hold
votes/meetings. Please correct me if I'm off base here.

A small country of just 7 sq km shouldn't need a lot of governance,
especially one that favors limited government. I would think that monthly
meetings for a few hours each month will be enough. Meetings could be held
in evenings or weekends and since we're a modern country I feel meetings
could even be held online.

If we can write the nation's constitution while holding down other jobs,
and do it without pay, I feel assembly members should be able to do it as
well.

**Comment by Auahi** [comment]
As to your first part I don't know the exact time either, but I suspect a meeting would take longer than a couple hours. 

Just because a country is small doesn't mean it's legislation and legal efforts will be small, and if anything because of Liberland being such a different and new country I'd suspect ARs would have a tremendous work load the first decade or so.

What we are doing right now is far different than how parliament behaves. Over the internet we are limited to simple post type _debate_, which is far different from in person debates/conversation, a simple disagreement in parliament can take days of debate and speeches.

**Comment by liberlandcitizen** [comment]
You are correct that it is difficult to estimate the amount of time
assembly members will have to sacrifice in the near future, let alone the
distant future. I would still argue that the more we make this a full-time
job, the more likely they will be to make government bigger.

More time in session = more laws proposed = more laws = bigger government =
less freedom

On the flip side, if we encourage short sessions the assembly members will
stay on in their current professions, stay grounded to their regular life
and community and work on government matters on the side not for money but
for a sense of duty and love of country.

Furthermore, it would likely result in a higher level of quality of
candidates since it takes a "special" type of person to give up their life
to be a full-time politician.

If we dream of a small-government state, we better hope they won't need to
debate new laws for longer than a 3 day weekend session, once a month, 9
months a year.

**Comment by terrorist96** [comment]
Also consider that paying the ARs will not deter a plutocracy. Reps are paid in America, for example, and it's still basically a plutocracy.

**Comment by Auahi** [comment]
@liberlandcitizen Long sessions don't necessarily equate to big government. The session could be about repealing legislation of laws as well, and long session would allow for high scrutiny of the bill being passed/law being repealed.

@terrorist96 Yes that certainly is true for the United States, but the United States has a highly corrupt government and deeply seeded problems of lobbying. MPs in the US also have salaries of $174000, so a lot of people are not only lobbyists but in it for the money. I think an AR salary shouldn't be high but a livable income...

Furthermore large companies could donate to ARs, since they don't receive a salary, which could make the Assembly full of lobbyists. The point which I'm trying to get at is not giving ARs salaries only makes it harder for the **average** citizen to be an AR, and nothing else.

**Comment by KacperZajc** [comment]
“No man's life, liberty, or property are safe while the legislature is in session.”
I hope sessions of the Assembly will be short and sporadic.
Remuneration will be an incentive to prolong sessions and this will support growing of the gov

**Comment by Auahi** [comment]
So if the assembly is more so the volunteer work of a few citizens shouldn't we cut back on it's powers? The way it's being made it out to be is that the legislation process will be simple, clean, and without any hinderance or debate. I feel that this won't be true and the Assembly will be quite different in reality. As of right now the constitution delegates a lot of power to the Assembly, maybe we should think about scaling it back if you don't want long sessions, and a quick legislature.

**Comment by liberlandcitizen** [comment]
Don't think of Liberland like most other nations. In a typical democracy,
the legislators can write a bill for any matter. In Liberland, they are
greatly restricted. It is my expectation and hope that the assembly won't
have many bills before them most of the time. If many of you disagree, then
I think we should limit the government further than we already have.
