### ISSUE TITLE
Long Bills

### ISSUE THREAD

**Issue by KacperZajc** [liberland/constitution#506]
§II.14(4) No Bill which cannot be reasonably read aloud by the Assembly Speaker within eight hours shall be voted on.

???

**Comment by terrorist96** [comment]
Based on a Google search, the average person reads 200 words per minute. That comes to 96,000 words within eight hours (assuming they don't take a break). And Google says the average book has 250-300 words per page, so that limits bills to somewhere between ~320-384 pages.

Just an observation. :smiley: 
Otherwise, I'm indifferent on this proposed provision.

**Comment by KacperZajc** [comment]
Hahahaha, nice calculation :D 
I think Im ok with that :)

**Comment by liberlandcitizen** [comment]
Over 300 pages of a "law" is bad news. What you're probably getting is
hundreds of laws at once. This can complicate things because you either
have to vote for a bill for the good parts, ignoring the bad or vice versa.
​
