### ISSUE TITLE
VIII.1. Free Speech loophole 

### ISSUE THREAD

**Issue by Auahi** [liberland/constitution#518]
From: VIII.1.
> _nothing in this provision shall prevent the Assembly from protecting the interests of Minors and/or those lacking mental capacity_

This addition to VIII.1. could be a loophole allowing for the regulation of free speech.

This text allows for anti-gay-propaganda laws like that of Russia, since it would _shield the children_. Anything deemed to _protect the children_ like how Russia asserts their laws, can potentially regulate free speech.

Pull Request: #517

**Comment by Auahi** [comment]
@KacperZajc @terrorist96

**Comment by terrorist96** [comment]
Seems kinda like a stretch. The government won't be able to regulate gay adults as a way to protect children because it's already forbidden from regulating gay adults (no victimless crimes).

**Comment by Auahi** [comment]
I'm not saying just gay culture, rather I used it as an example. Russia's laws regulating gay culture were drafted under the pretext that it would benefit children. The Assembly can theoretically make any law regulating free speech under the assumption that it will protect the interests of children. I don't see the point of having this in the constitution if all it does is allow the government to regulate free speech.

**Comment by liberlandcitizen** [comment]
I don't want to speak for those who wrote this line, but i'm assuming the
real reasoning behind it is to prevent child pornography. Why not just ban
child pornography in clear language and leave it at that instead of
something that is wide open to misinterpretation and abuse?

**Comment by KacperZajc** [comment]
There is a delicate balance to strike here.
Let me think about that.

**Comment by KacperZajc** [comment]
The broad wording has been used here on purpose.
It is not only about child pornography.

This issue has to sides - 
1) things that a child should not take part in 
2) things that a child should not watch

So this limitation gives the Assembly the power to prevent people or businesses from casting children in things they should not star in and from showing children things they should not see.

**Comment by liberlandcitizen** [comment]
But the limitation doesn't specify it's for those two things only. And so
who knows what they will use it for: regulating if you can smoke in the car
with a child there, how much salt can be in food given to a child, how much
fried food can be included in a child's meal, if commercials can be shown
during children programming.

"Protecting the interests of Minors" is so broad!

**Comment by KacperZajc** [comment]
this is a freedom of speech provision...
where did you get cars and meals from?

**Comment by Auahi** [comment]
Even if it won't regulate what children eat it is still has **ENORMOUS** potential for misuse! With this provision all of the following things can happen:

- The regulation of public display of affection
- Obscene symbols banned in public
- Anything anti-religious banned in public

And **many** more things can be banned or limited based on this text.

This provision even allows sharia-esque laws to be brought into law. If the government decides that children should not see unveiled women or tight fitting clothing on women it can theoretically ban it!

Now yes, it may not be likely for these laws to be drafted, but the mere fact that it allows these laws is absurd.

**Comment by KacperZajc** [comment]
I share your concerns.
Let's find a wording which will reflect the balance we seek here.

**Comment by liberlandcitizen** [comment]
​My bad, the above text is very much out of context and I do not have the
whole constitution memorized. Still, I wish we would just outright ban a
few things in this constitution that we know we're against and leave
everything else off the table. I'm thinking: no child pornography, no
slavery, no nuclear weapons. Anything else?

We're trying to create language so the assembly can ban these certain
things, meanwhile we're opening the door to loopholes.

**Comment by KacperZajc** [comment]
slavery, conscription and nuclear weapons are already forbidden
please focus on the limitation on the freedom of speech in relation to the protection of minors

**Comment by liberlandcitizen** [comment]
But HOW are they forbidden? With direct and clear reference or flowery
language that can be misinterpreted? I see that slavery is directly
mentioned:

"No relationship amounting to slavery or any other form of involuntary
servitude shall exist between any legal or natural Person and any other
Person"

So I would recommend having an equally direct statement with regard to
children. Because what we currently have...

"nothing in this provision shall prevent the Assembly from protecting the
interests of Minors and/or those lacking mental capacity"

is way too indirect. I could see this being used to limit what is
advertised to children, limiting curse words on over-the-air television and
radio in the name of children and other nonsense or even censoring the
internet! If this is to protect against child pornography let's just say
child pornography.

**Comment by KacperZajc** [comment]
Finally my proposed revised version of VIII.1:

All Individuals shall have the right to upload, transmit, display, access and publish any form of information in any medium of exchange thereof;
No law shall introduce the requirement of licensing or registration in respect of any printed materials, radio, television, the Internet or any other medium of exchange of information; 
Materials depicting Minors and Persons lacking mental capacity as well as rules governing accessing different forms of information by such Persons shall be subject to the control by the law; 
information classified as a state secret and related to the work of the of Agents of Law Enforcement operating undercover pursuant to a Warrant shall be subject to control as prescribed in the Constitution.

???

**Comment by liberlandcitizen** [comment]
This is much improved but if I am allowed one gripe it would be the word
depicting. As I understand the meaning of this word, this could mean a the
drawing of a child could be regulated, or a distasteful story about
children could be banned. Is this our goal?

I will again suggest we unabashedly use the term "child pornography"
instead of trying to find ambiguous language for the purpose of preventing
child pornography. If we are to stick with the ambiguous language though,
how about replacing the word depicting with something better?

I do not think it should be legal to create, sell or transmit child
pornography but this is the ONLY thing I think we should have a hand in
regulating as far as the transmission of material. When you say "rules
governing  accessing *different forms* of information by such Persons shall
be subject to the control by the law" what you're really saying is that the
Liberland government can decide what material children may or may not
access on the internet and elsewhere. Pornography or otherwise! Movies with
curse words. Violent video games. Rap music. Controversial literature. Do
we really want to go there?

**Comment by KacperZajc** [comment]
Child pornography is one example only (although the most notable one).
The other would be some non-improvised fights between children (e.g. filmed by a abusive parent in a garage).
Yes, regulating accessing is a slippery slope but I think we have recognised that minors dont enjoy absolute rights even in Liberland and it is vital to protect them. Again, pornography is not the only example of materials children should not access freely.
I think the potential harm done by such regulations is relatively innocuous (banning video games etc.).

**Comment by terrorist96** [comment]
Since we went so far as to enumerate the restrictions on freedom of contract, why not do it here as well? Child porn, child abuse (fighting), what else is there?
Also, child abuse can already be made illegal without having to make videoing child abuse illegal as well.

**Comment by liberlandcitizen** [comment]
Child abuse is clearly illegal in Liberland and we should keep it to that.
We all agree that this is a slippery slope so let's not go down that road.
Non-improvised fights between children? I personally have never heard of
this problem. Censorship is something I have seen a lot of though!

**Comment by KacperZajc** [comment]
@terrorist96 We have enumerated exceptions to the freedom of contract because it is potentially very harmful to leave too much discretion to the government.
Here the harm is rather innocuous.
I am also not sure we can think of everything here and I would not like to leave anything out.

@liberlandcitizen Just because you didnt think of it, it doesnt mean it would never happen xD
And organising such a fight and filming it are two separate things.
I can see a defence attorney arguing that the latter does not fall under the category of a crime with a victim and as such should be protected by the freedom of speech provision.

I think there not much to lose by allowing some discretion here.
