### ISSUE TITLE
Constitutional restrictions on private investigators?

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#536]
We force police to abide by the constitution (no warrentless searches, etc.), but what if someone hires a private investigator? Would the constitution restrict them in their work as well? If not, shouldn't it? It can be pretty big loophole to circumvent the protections we've enumerated.

**Comment by FellowTraveler** [comment]
We restrict the police from kicking down your door without a warrant. Does that mean that private citizens have a right to kick down your door?

That's not my understanding -- my understanding is that I have a right to be secure in my possessions from police AND citizens. The only difference is that police have the ability to go and get a warrant.

**Comment by terrorist96** [comment]
Here's one example:

> §XII.2. Agents of Law Enforcement executing arrests shall act openly and shall inform the detainee about the cause of his or her detention and of relevant rights he or she enjoys under this Constitution and any laws passed in accordance therewith; where a Person is placed under arrest, Agents of Law Enforcement shall immediately inform his or her close ones as prescribed by law about the detention.

What if you are arrested by a citizen or private investigator? Do they have to inform you of your rights?

**Comment by KacperZajc** [comment]
The short answer here is NO.
Citizens arrest you and dont have to do anything. Then the police take you over and they have to comply with XIII.2.
When it comes to wiretapping by PIs, it is a matter for law to say whether two citizens can put each other under surveillance and under what circumstances. 
But I am thinking here about any potential wider consequences just like with #531. It is a similar problem really.
In any event, the PA would not be able to hire PIs to go around their constitutional limitations because of  §II.10.
