### ISSUE TITLE
Better Constitutional Limits

### ISSUE THREAD

**Issue by cpacia** [liberland/constitution#554]
This was a talk given by professor Michael Huemer on constitutional design. He does a pretty good job of documenting the failures of the US Constitution, the specific reasons why it failed as it did, and proposes some ways to fix the problems. 

I would highly suggest anyone working on this repo watch the video. Especially if you are not from the United States and don't have first hand experience with a failed attempt to limit government. 

https://www.youtube.com/watch?v=zd5aJUVZzgw

**Comment by terrorist96** [comment]
@cpacia I watched the video, and his solutions were super-majority requirement for laws (we have that except for financial bills), negative legislature (we don't have this, but I had this on my list here: #107 but since it's already so hard to make laws [supreme court declaration, citizen veto], this isn't really needed), court for constitutional declaration (supreme court already does that), citizens declaring constitutionality (eh, we require unanimous declaration, plus have citizen veto), and assign punishment for unconstitutionality (we have this).
