### ISSUE TITLE
Double jeopardy in vacated conviction

### ISSUE THREAD

**Issue by terrorist96** [liberland/constitution#571]
If a jury convicts a defendant, but upon appeal, the conviction is vacated based on incorrect jury instructions, would the defendant be able to be retried on that charge? Or would it violate double jeopardy?

In the US, apparently it doesn't violate double jeopardy.
http://www.scotusblog.com/case-files/cases/bravo-fernandez-v-united-states/

**Comment by michalptacnik** [comment]
We don't have an Anglo-American system (per se), but a hybrid one. The core judicial system seems currently built on the European notion of professional Judges, rather than juries. Juries are not impossible in Liberland, just not the first choice or the default system. 
Double jeopardy will not be violated unless in case of extraordinary appeal/attraction by the Supreme Court. The Supreme Court will be able to attract otherwise closed cases, reopen them. Still, it is not true double jeopardy in the criminal doctrine sense, it is just close to it (non ne bis in idem). 
Closing the issue.
