### ISSUE TITLE
§II.1. Meaning of "directly harm"

### ISSUE THREAD

**Issue by abcd8488** [liberland/constitution#573]
Section 1 of Article 2 states that:

> No law shall prohibit any act or omission which does not (a) directly harm any other Person, (b) cause unwarranted suffering to an animal capable of conscious behaviour or (c) harm to the environment beyond the boundaries of one’s property; nor shall any law prohibit any act or omission which has been validly consented to by another Individual; no Individual shall be considered a victim of one’s acts or omissions; nothing in this provision shall prevent the Assembly from criminalising conduct interfering with the constitutional functions of the Public Administration or any form of direct or indirect participation in a criminal offence

What exactly does harm mean here? According to [Wiktionary](https://en.wiktionary.org/wiki/harm#English), the word "harm" seems to include only physical injuries.

This would mean that it would be legal to:
 - Steal someone's property (no physical injuries are directly caused). Even if the word "harm" did include financial harm, depending on the object that's stolen, there may be no financial damages. That still isn't a reason to not protect someone's property.
 - Do actions that bother other people but don't directly harm them (such as loud noise at night, light pollution, etc.)
 - Do actions that risk harming others but, out of chance, didn't actually harm anyone (such as drunk driving, or even just taking a gun and randomly shooting in all directions in a crowded place)

**Comment by terrorist96** [comment]
Did you see this provision?

>§XVIII.5. No provision of this Constitution shall be construed as to prevent the Assembly from criminalising any act or omission which does not stem from the inherent right of self-defence but amounts to any (a) physical, or constitutionally recognised form of non-physical, violence towards any Person or animal capable of conscious behaviour, or threat thereof, (b) invasion of privacy, (c) fraud, (d) direct and grave interference with enjoyment of one’s property or (e) harm to environment beyond the boundaries of one’s property.

**Comment by michalptacnik** [comment]
We have a new draft of the constitution here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit

We have this addressed in Book 3: prohibition of victimless crimes/delicts. Stealing something that is not intellectual property harms someone, because he will no longer have it. Stealing intellectual property can harm someone if that intellectual property has been defined consensually. Liberland will likely be more, well, liberal with respect to this than other states. Word harm removed.

Closing this issue, please comment in the document or reopen if you have more questions.
