### ISSUE TITLE
polycentric law

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#58]
The competition between the U.S. states has been an extraordinarily effective check on government power. Political migration has a long history in the USA of providing citizens with a final escape from tyranny, and providing states with a strong incentive (and penalty) towards the liberty of the people.

I suggest that it was a mistake to remove the concept of non-geographical cantons from the Liberland Constitution. Please consider adding it back. Or at least let's have a discussion on this matter.

**Comment by KacperZajc** [comment]
it's too small and that would mean more bureaucracy, as far as I know President's team doesnt like that idea either

**Comment by joshmh** [comment]
I think there's a good chance we'll have polycentric law anyway. This constitution is just one draft, being put forth by "citizens of Liberland". If this works out, there will be many settlers, and they might want to start their own canton and not be bound by the Liberland regime. What's stopping them? Starting off with the non-geographical cantons would avoid any strife this might cause.

I also agree with @FellowTraveler that the competing US states are one of the main reasons the US has been as successful as it is. It works well in Switzerland, as well. Even small states like New Hampshire have competing counties and towns with their own police forces. Exit is much more powerful than Voice.

**Comment by FellowTraveler** [comment]
@joshmh I live in Switzerland and yes it works well here. Competing states in the USA, and competing cantons in Switzerland, are one of the aspects of the U.S. Constitution that have truly been successful.

I understand @KacperZajc saying that Liberland is too small (7 sq km) but if the cantons are non-geographical, and require a certain number of members to become accepted, it should work out.

This is a separate issue from whether the city itself should have a separate city government (it should.)

**Comment by ke7ofi** [comment]
@FellowTraveler At that point, what’s the difference between a canton and a political party?

**Comment by cpacia** [comment]
@ke7ofi Political parties try to influence the policies of a single government which everyone is bound to follow. In a polycentric system, the policies are only binding on those who have consented to live under them.

**Comment by FellowTraveler** [comment]
@ke7ofi Each canton would make its own laws instead of making the laws at the Federal level. That way people can choose which Canton (which laws) they will submit to. You asked what's the difference between that and political parties? The answer is that when the opposing political party wins an election, you are forced to submit to rule by the opposing political party. For example, sometimes a Republican must live in a Democratic state. Whereas with cantons, you are never forced to submit to the opposing canton, but instead always enjoy the benefit of membership in the canton you prefer.

**Comment by Jean-LouisMesic** [comment]
You can also switch between cantons and change the laws under which you are bound, much like how moving and changing states changes the entire state government under which you are bound.

When you change political parties, you just change the set of people you're able to vote for in primaries. When you change cantons, you're fundamentally changing your legal obligations instantaneously.

**Comment by ke7ofi** [comment]
That sounds like a good system, then.

**Comment by andrewgorash** [comment]
I'm 100% in. Adding concept of polycentric law (while being subject to general provisions of the Constitution) is a great tool to limit possibility of Administration misusing their power. At the same time it serves the purpose of fair representation, which is discused in #78.

**Comment by Jean-LouisMesic** [comment]
AND it can leave the issue of levying taxes for the sake of general upkeep up to cantons, rather than the federal government, which keeps taxes voluntary.

**Comment by ke7ofi** [comment]
I assume someone will start a canton which imposes no additional laws?

**Comment by Jean-LouisMesic** [comment]
Naturally, someone will. If there's a will for it, someone can get elected by said will. The lust for power in the federal government would be too great not to refuse.

**Comment by saintego** [comment]
I think cantons are great idea in case of future success. What if some new territory would like to join liberland? And it'll be nice to have cantons with veto power as another level of protection against growing state.

**Comment by cpacia** [comment]
@saintego the cantons could form some kind of organization in which they make collective decisions like that. 

Also, polycentric law would answer the question that Kacper posed:

> Please dont ask we what happens if the majority of citizens dont want their liberty anymore because in that case there is nothing what can be done at all, regardless of the Constitution.

That would not be a worry in a polycentric system.

**Comment by saintego** [comment]
People usually like their liberty, but prefer to take liberty of other people. Yes there can be fully communist canton and rest of people can stay free, but problem will be if majority will like to have communists liberland.

**Comment by cpacia** [comment]
One of the things that like (and the canton idea is largely based on), that Kacper doesn't like is doing away with the concept of "legislation" and merging criminal law into civil law. 

It used to be the case in some countries that crimes against one person and another (such as robbery) were not part of a criminal code drafted by the politicians. Instead criminal complaints were brought to the court in the same manner as civil complaints and the court would decide guilt and innocence and what the punishment would be. 

The "legislation" in those times consisted mainly of defining crimes against the crown or handing out special privileges to favored interest. Criminal law only started being defined by legislation once these societies took a turn down the collectivist path. Then crimes were no longer considered private offences where the was an actual victim, but rather victim was said to be "society" and a government prosecutor was appointed to get justice on behalf of "society" instead of on behalf of the victim. It's that mindset that allows politicians to pass laws and send out enforcers to arrest people who are just minding there own business and which whom nobody has an actual complaint. 

The benefit of doing away with legislation legal action can only be taken if someone feels their rights have been violated, they have brought their complaint to the court, and the court has ruled in their favor. 

It prohibits those situations where politicians have nothing better to do but criminalize behavior that violates nobody's rights and then send out the enforcers to get justice on behalf of "society".

If I had my way there would be no legislation. Just complaints (criminal and civil) brought before a court.

**Comment by FellowTraveler** [comment]
Imagine a murder victim with no family.

Who brings the complaint on his behalf?

**Comment by saintego** [comment]
You can homestead right of killed person and sue murder.

**Comment by cpacia** [comment]
> Imagine a murder victim with no family.
> Who brings the complaint on his behalf?

It could be the victim's estate. I agree with @saintego that from a purely philosophical perspective homesteading is probably the way to. The ability to homestead restitution where no one else claims it creates an incentive to bring a complaint and not let the perp get away with it. 

From a practical perspective, there could just be a social convention which says a public prosecutor (either appointed by the government or your canton (if we are talking a polycentric model)) will be authorized to bring the complaint in absence of a last will and testament instructing otherwise.

**Comment by tinkyholloway** [comment]
@cpacia this idea and the polycentric model are the best ideas I've read since I read "For a New Liberty". Wow. I wish there was a place we could try these out.

**Comment by FellowTraveler** [comment]
I'm curious. Let's say a broke and homeless man murders another broke and homeless man. Neither has any wealth. Neither has any family.

What is the incentive to "homestead" the murder? Seems there is nothing to gain from the murderer, since you _"can't squeeze blood from a rock."_

In this case it seems reasonable to me that a prosecutor (or private party) could present the relevant evidence to a grand jury. From there, if the grand jury chooses to indict, the case is prosecuted as normal.

**Comment by terrorist96** [comment]
> In this case it seems reasonable to me that a prosecutor (or private party) could present the relevant evidence to a grand jury. From there, if the grand jury chooses to indict, the case is prosecuted as normal.

+1

**Comment by Jean-LouisMesic** [comment]
@FellowTraveler That's what restitution is for. If you homestead a claim, you would be entitled to the restitution.

Seems off to me, though. I don't favor the idea of conglomerating civil and criminal law. It allows criminal punishments to be given to civil disputes. I distrust it.

**Comment by cpacia** [comment]
> In this case it seems reasonable to me that a prosecutor (or private party) could present the relevant evidence to a grand jury. From there, if the grand jury chooses to indict, the case is prosecuted as normal.

You could technically claim that the prosecutor is homesteading in that situation. Or it could be any other volunteer group that is will to expend resources to get Justice for someone who they believe was wronged. 

> Seems off to me, though. I don't favor the idea of conglomerating civil and criminal law. It allows criminal punishments to be given to civil disputes. I distrust it.

What it does is it essentially makes a requirement that someome must believe their rights have been violated for there to be any legal charges brought. 

That's much different than where a legislature makes up the list of crimes and sends out people to make arrests and prosecute people. 

The forum is much more likely to only be used when actual crimes have been committed. The later... well we've seen how that abuse that power.

**Comment by Jean-LouisMesic** [comment]
Think about the other side of it, though, there are civil disputes that could no longer be solved under the "must have had rights violated" claim. I don't have time to pose examples, but I will later tonight.

**Comment by cpacia** [comment]
Keep in mind the only different between a civil and a criminal complaint is an allegation of intent. Hard to see why both cases shouldn't be handled the same way.

**Comment by Jean-LouisMesic** [comment]
Not all divorce cases are based around a violation of rights. Does that mean they should not be taken up?

Not all renter or business practice suits involve a violation of rights, but just the same constitute legitimate disputes for which the Court stands as mediator. It is an entirely different set of circumstances. I prefer leaving the two separate. This way, you can have judges more acquainted to civil disputes than to criminal proceedings. Additionally, molding the two together means any court would be able to issue a warrant. Would you want police knocking on your door to investigate nonviolent marital disputes, because a judge in pursuit of the resolution of a divorce claim decided it warranted a search of your home?

Criminal law is inherently different than civil law, and powers concerning either have been smartly and appropriately separated to simplify the system and to protect the rights of both plaintiffs and defendants.

**Comment by mtelka** [comment]
_Not all divorce cases are based around a violation of rights. Does that mean they should not be taken up?_

Since you won't have (state) marriage, you won't have divorce as well.

For civil law (or better: disputes) you do not need a judge, just a mediator.  All decisions by a third party in such cases are heavily arbitrary.  If there is no violation of rights in a case, you do not need a judge, police, etc. to solve that case.

**Comment by cpacia** [comment]
@jean  there's nothing wrong with selecting the court based on the nature of the cases. For example, criminal complaints go to courts that specialize in criminal law. Contract disputes go to courts familiar with contract law etc.

My claim wasn't that there needs to be uniformity, just that the practice of having a group of elected polictians write the criminal law while leaving civil complaints to the court isn't necessary and counter productive.

**Comment by jean** [comment]
Wrong jean ...

**Comment by Jean-LouisMesic** [comment]
@jean Lol, sorry to force you into this conversation, jean.

**Comment by Jean-LouisMesic** [comment]
Honestly, I think we're all going to have to face it that the amount of theoretical material in this thread is just making it less likely for the feasible ideas to actually get accepted. It's too late in the game to completely change our legal system, anyway.

**Comment by FellowTraveler** [comment]
@Jean-LouisMesic *"Not all renter or business practice suits involve a violation of rights, but just the same constitute legitimate disputes for which the Court stands as mediator."*

Well there is the **right to contract.**

Let's say I form a contract with you to mow my lawn for $50, and then you perform the service, and thus I owe you $50.

If I refuse to pay you, then it is your contractual right to the $50 that is being violated. That's why a court has jurisdiction in the case at all. Otherwise there wouldn't be a cause for action and you wouldn't even be able to bring the suit in the first place.

**Comment by mherzl** [comment]
> I'm curious. Let's say a broke and homeless man murders another broke and homeless man. Neither has any wealth. Neither has any family.

>What is the incentive to "homestead" the murder? Seems there is nothing to gain from the murderer, since you "can't squeeze blood from a rock."

Interesting question @FellowTraveler. Clearly the homeless man's rights have been violated and justice demands restitution (or at least punishment), despite the fact that the his estate has nothing to offer in exchange for it. I say the answer of who has incentive to (i.e. who should) pursue the justice is the entity from which the murdered man's rights were derived.

In the cantor-less system the responsibility falls to the state.
In the cantor system, the responsibility falls to the homeless man's cantor.

In each case the relevant entity has some incentive to pursue the appropriate justice. After all, each is essentially in the business of securing the rights of its constituents. I, and I presume many others, wouldn't choose a cantor or want to live in a state which didn't pursue justice for each of its members as a matter of principle.

Arguably the cantor has greater incentive to pursue the justice in this case, the whole idea of cantors being that they offer more choice and competition.
