### ISSUE TITLE
Your papers please...

### ISSUE THREAD

**Issue by FellowTraveler** [liberland/constitution#64]
From David numbering the people, to the notorious example set by the Nazis ("papers, please..."), to the broken promise by the U.S. government that social security numbers would never be used as a form of identification, forcing people to be identified has always been used as a tool of oppression.

Therefore some guarantee must be enshrined in the Constitution that protects people from any requirement to carry identification, to show papers while traveling, to wear a mark in order to buy or sell, etc.

Government will already identify criminals through fingerprinting and other investigative techniques, and people will already develop systems to identify themselves to each other for reputation purposes. The less government is involved in creating official identity systems, the better. Of course Citizens will have to identify themselves in order to obtain a Liberland passport or voter registration, so the Constitution should protect people from those mechanisms later being abused for other purposes.

**Comment by KacperZajc** [comment]
I understand your concern but how about the driving licence?
Maybe can make a provision that the gov will not assign any identification number to a person?
what about gun register?

**Comment by FellowTraveler** [comment]
> what about the gun register?

What about it? Gun registration is a tool for evil:

http://www.nationalreview.com/article/365103/how-nazis-used-gun-control-stephen-p-halbrook

**Comment by mtelka** [comment]
> I understand your concern but how about the driving licence?
What about the driving licence?  To drive a car (or whatever) you do not need a paper.  You need a car and a gas (simplified, of course).

**Comment by jasoneriksen** [comment]
No need for a state issued driving license. Roads should be privately owned anyway. If a bunch of insurance companies coalesce onto a standard set of recommended rules of the road, they might require all drivers they insure to be tested and certified through one of their testing centers. Home Owners Associations and Business Park owners may decide having safe drivers on their roads is in their best interest and will go on to require drivers on their roads to be certified and insured, etc.

**Comment by saintego** [comment]
I think driving licence is needed in same way as passport. For traveling outside of liberland. I don't think there is any need of ID, nor official driving licence in liberland. I think if state have try to punish somebody for driving without licence is victimless crime and therefore against Constitution.

**Comment by liberlandcitizen** [comment]
@KacperZajc I agree with your idea of adding to the constitution that government can not assign a number to people.  I also think any federal documents (passports, and DL if we are to have them) should be optional, and never required.  

More importantly, I think it's important to guarantee the right to NOT have to show your papers, or even identify yourself by name to the police unless and until you have been arrested (and an arrest should only be made when there is enough probable cause that a crime has been committed).  

Last but not least gun registration is a very dangerous idea.  If a government has a list of who has guns, then a government has a list of which houses to raid if they ever move to take the guns away.

**Comment by FellowTraveler** [comment]
_"Government shall not assign numbers to the people, nor compel any traveler to identify himself, nor compel any person to procure or carry identification papers, nor compel any person to bear any mark or wear any badge. Government systems that necessarily track a person's identity, such as for the purposes of issuing Liberland passports or for voter registration, or collecting taxes, shall not share data, but shall adequately protect the data entrusted to them even from other government agencies."_

**Comment by mtelka** [comment]
For all who thinks that _[g]overnment shall not assign numbers to the people_:

Every information stored in a computer system (as we know it today) is represented as numbers. For example, the word **Kacper** is usually stored as this sequence of decimal numbers: 75 97 99 112 101 114.  In other words, in a case the government will store any information about anybody in a computer system, it will technically assign a number to the individual.  So, the requirement to not assign a number to people will effectively block the government to store _anything_ related to _anybody_ in a computer (including internet, of course).

If we will use more generalization, then we might also say that even writing the word **Kacper** on a paper (using normal pen, written on normal paper, as mankind is doing for ages), is just an assignment of a number to the individual.  With even more generalization: even if you remember the word **Kacper** in your head, you assigned a number to the individual.

**Comment by mtelka** [comment]
_... shall not share data, but shall adequately protect the data entrusted to them, even from other government agencies ..._

This is so vague that it would be very hard to find a consensus what exactly that means (for example, what exactly "adequately" means?).  And, it is effectively not possible to enforce it.

I propose the opposite idea of the data protection:

_All (personal) data (IOW, data related to any person, or group of persons, ...) collected by the government must be shared with the public._

This will not create a false perception of safeness of your data (data you provided to the government) or any data related to your person.  This will also (hopefuly) make the people to think twice before sharing their data with government.  It will also not divide people to two sets: first one with no access to your data (almost everybody), the second one with access to your data (the agency).

**Comment by ke7ofi** [comment]
@jasoneriksen Privately owned main roads would make it possible for people to arbitrarily deny others passage, so maybe not.

**Comment by FellowTraveler** [comment]
> the requirement to not assign a number to people will effectively block the government to store anything related to anybody in a computer

@mtelka We can change it to _"Government shall not assign identification numbers to the people."_ The purpose is to prevent the creation of numbers such as social security numbers.

> All (personal) data (IOW, data related to any person, or group of persons, ...) collected by the government must be shared with the public.

@mtelka This is not a bad idea. I'm curious what others think of this.

**Comment by mtelka** [comment]
@FellowTraveler: There is almost no difference between _identification number_ and _a number_ (from technical and mathematical point of view).  I understand what you are trying to achieve here, but I'm afraid it is hardly possible to do that without unclear (fuzzy) statements like that one you suggested.  The bad news is that such unclear statements will make the Constitution weak...

OTOH, I do not undestand what is bad with assignments _person_ <-> _number_ (except that there are some bad, but still irrational, relations in our minds with the number of the beast, and so on).

**Comment by Jean-LouisMesic** [comment]
"No number shall be assigned to any person not consenting in exchange for any good, service, privilege, or other deed, by any agent or agency of the Free Republic of Liberland for any purpose pertaining to the Law of the Free Republic of Liberland."

This allows people to voluntarily give information to voluntarily give information to the republic for express purposes. It also allows agents of the republic to call their neighbor by name when off-duty.

"No person shall be compelled to identify themselves to any agent or agency of the Free Republic of Liberland, otherwise than in pursuit of a Warrant issued by a judge of a Criminal Court of the Free Republic of Liberland, nor shall any person be compelled to procure, carry, or otherwise maintain identification materials, nor shall any person be compelled to bear any mark or wear any badge not consenting in exchange for any good, service, privilege, or other deed."
"No data gathered by any agent or agency of the Free Republic of Liberland that necessarily track a consenting person's identity, such as for the purposes of issuing Liberland passports, or for voter registration, or for the levying of taxes and/or acceptance of voluntary donations, shall be considered confidential and shall not be shared with, or used by, or discussed with any party other than the agency which originally gathered said data. 
"All data collected by any agent or agency of the Free Republic of Liberland shall be used only for the direct and necessary purposes for which it was originally collected."

The final quote extends to other information gathered by the government that does not classify as personal information.

**Comment by KacperZajc** [comment]
Jean-LouisMesic: I like your form but some of it covered by III.2 so it needs a bit of polishing, let me thing about that :)

**Comment by Jean-LouisMesic** [comment]
Thank you! I hope I was helpful.

**Comment by mayapurmedia** [comment]
If government will be forbidden to identify person, how then they will be able to issue warrant for him in case of need?

Seems like government officials should have right to do so, in case of crime.

**Comment by KacperZajc** [comment]
what do you guys think of this?

“No law shall allow any body of any branch of the Public Administration to assign a number to any law-abiding citizen without his or her consent; no person shall be compelled to identify themselves to any agent of the Public Administration, otherwise than in pursuit of a warrant issued by a judge of the Criminal Court; nor shall any person be compelled to procure, carry, or otherwise maintain identification materials of any form; all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner.”

**Comment by liberlandcitizen** [comment]
How do you define lawabiding?  I went over the speed limit today - am I lawabiding?  

Also does this demand that proof of a warrant is shown to the person before they have to identify themselves?

**Comment by KacperZajc** [comment]
yes it does
law-abiding means convicted in a court of law
any better wording?

**Comment by mayapurmedia** [comment]
@KacperZajc But still, when crime is done, how judge can issue warrant without knowing name of suspect?

**Comment by KacperZajc** [comment]
There is a misunderstanding here.
A crime is committed.
The police suspect person X and request a warrant.
The judge issues a warrant for the arrest of person X.
The police take the warrant and approaches person X.
They show him/her the warrant and demand he identify himself.

**Comment by liberlandcitizen** [comment]
Will police (or sheriffs) have arresting powers?  If so can they demand identification upon arrest?

**Comment by KacperZajc** [comment]
well this is a good question, it seems they do if they exercise their power to arrest for no more than 24h

**Comment by liberlandcitizen** [comment]
So then they would either need authority to demand identification, or according to above would still have to go before a judge (which might be a good thing...not sure).

**Comment by KacperZajc** [comment]
unless we construe law-abiding as a person under suspicion but apparently it needs further qualification

**Comment by liberlandcitizen** [comment]
I would not leave it up to police to decide who is and is not law abiding.  This would result in people having to identify themselves to police at all times, because who could say if it was required or not?

**Comment by KacperZajc** [comment]
“No law shall allow any body of any branch of the Public Administration to assign a number to any citizen, nor shall he or she be required to procure, carry, or otherwise maintain identification materials of any form without his or her consent unless upon the conviction in a court of law; 
no person shall be compelled to identify themselves to any agent of the Public Administration, otherwise than upon a probable cause or in pursuit of a warrant issued by a judge of the Criminal Court;
all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner.”

**Comment by liberlandcitizen** [comment]
I would say change "upon probable cause" to "upon arrest with probable cause" 

It's impossible for a citizen to know if police actually have probable cause and police lie.  Example: you are walking down the street and the police stop you and ask you to identify yourself.  Do they have probable cause?  How can you know?  Do you match the description of a criminal?  Are they just picking on you?  There is no way to actually know, so it results in citizens having to ID always, or else they risk breaking the law.

**Comment by KacperZajc** [comment]
yeah I like that :)

so:

“No law shall allow any body of any branch of the Public Administration to assign a number to any citizen, nor shall he or she be required to procure, carry, or otherwise maintain identification materials of any form without his or her consent unless upon the conviction in a court of law; no person shall be compelled to identify themselves to any agent of the Public Administration, otherwise than upon arrest with probable cause or in pursuit of a warrant issued by a judge of the Criminal Court; all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner.”

anyone else wants to comment?

**Comment by liberlandcitizen** [comment]
Sorry for the many comments but "upon conviction in a court of law" - does this mean once convicted you forever lose this right?  Even after you are released?

**Comment by KacperZajc** [comment]
yes and this would be exercise in regard of sexual offenders for example;
I doubt there is any other instance this could be used?

**Comment by liberlandcitizen** [comment]
Under the language above, it could be used for any crime.  Littering.  Speeding.  Not wearing a seatbelt.  I am not saying we'll have those laws, but if we do and then people are convicted of it, they theoretically could forever lose their privacy rights.

Convicted sexual predators will become a matter of public record right?  A private citizen can make a website with the names of sexual preditors.  Concerned parents can study the database.  

Once people are out of jail they should have their full rights restored.  If they are a danger to society they shouldn't be out in public anyway.  Just my two cents on that...

**Comment by KacperZajc** [comment]
we could add "upon the conviction in a court of law and for the duration of the sentence only"
then a judge could make that sexual predators are matter of public database as a part of the sentence but otherwise it would automatically ceased
what do you think?

**Comment by liberlandcitizen** [comment]
I think that's pretty good - but it may contradict the last part of the above text:

"all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner.”

Are arrest records data that is collected by the government?  Sure it is.  And should it be kept confidential unless the arrested party consents?  

What about voting results?  Would that not constitute data collection?

**Comment by KacperZajc** [comment]
voting would be covered by consent, this is not a problem
yeah we should add 'or in pursuit of a court order' at the very end

**Comment by liberlandcitizen** [comment]
Much of this may contradict:

§I.8. The Citizens of the Free Republic of Liberland shall have the access to information which relates to any aspect of the functioning of any body of any branch of the Public Administration which is not classified; and no information shall be classified unless it is absolutely necessary for the purposes of national security.

**Comment by KacperZajc** [comment]
how come?
functioning of a body of PA does not include the list of names of prisoners or anything like that
plus one article can be read subject to another

**Comment by liberlandcitizen** [comment]
I suppose you are right.  Thank you for addressing my concerns.

**Comment by KacperZajc** [comment]
“No law shall allow any body of any branch of the Public Administration to assign a number to any citizen, nor shall he or she be required to procure, carry, or otherwise maintain identification materials of any form without his or her consent unless upon the conviction in a court of law and for the duration of the sentence only; no person shall be compelled to identify themselves to any agent of the Public Administration, otherwise than upon arrest with probable cause or in pursuit of a warrant issued by a judge of the Criminal Court; all data collected by any body of any branch of the Public Administration shall be used only for the direct and necessary purposes for which it was originally collected, and shall be kept confidential and shared only with the consent of the rightful owner or in pursuant to a court order.”

**Comment by liberlandcitizen** [comment]
So I guess we'll choose our own numbers for our passports?  Not have any?

**Comment by KacperZajc** [comment]
consent...

**Comment by liberlandcitizen** [comment]
ok that makes sense.

**Comment by Jean-LouisMesic** [comment]
I suppose we will require visitors and travelers to carry visas, going by the first clause?

**Comment by Jean-LouisMesic** [comment]
I also agree with @liberlandcitizen that I.8 may or may not contradict a bit.

"All data collected [by the state]...shall be kept confidential...and shared only with...consent...or in pursuit of a court order."

I would add "or otherwise in accordance with the provisions of this Constitution" just to be sure that there are no conflicts.

Additionally, does your suggestion of making sex offender data under "rightful owner"ship of the government/public, rather than the offender? Perhaps "rightful owner" should be more strictly defined, in case of seizure of "rightful ownership."

**Comment by KacperZajc** [comment]
this clause is refers to citizens only
yeah we can add "or otherwise in accordance with the provisions of this Constitution" 
sex offenders is not a matter for the constitution I just made an observation that their record could be made public as a part of their sentence
